[[xpack-graph]]
== Graphing Connections in Your Data

{xpack} graph capabilities enable you to discover how items in an {es} index are
related. You can explore the connections between indexed terms and see which
connections are the most meaningful.

For information about the Elasticsearch graph API, see the
{ref}/graph-explore-api.html[Explore API]. For information about
exploring connections in your data from Kibana, see
{kibana-ref}/xpack-graph.html[Graphing connections in your data].

[[xpack-profiler]]
== Profiling your Queries and Aggregations

{xpack} includes the Search Profiler tool, which can transform the output from
the profiler API into a visualization that is easy to navigate.

For more information, see {kibana-ref}/xpack-profiler.html[Profiling queries
and aggregations].

[[xpack-reporting]]
== Reporting from Kibana

{xpack} enables you to generate reports that contain {kib} dashboards,
visualizations, and saved searches. The reports are exported as
print-optimized PDF documents.

For more information, see {kibana-ref}/xpack-reporting.html[Reporting].