[[xpack-introduction]]
== Introduction
X-Pack is an Elastic Stack extension that bundles security, alerting, monitoring, reporting, and
graph capabilities into one easy-to-install package. While the X-Pack components are designed to work
together seamlessly, you can easily enable or disable the features you want to use.

Prior to Elasticsearch 5.0.0, you had to install separate Shield, Watcher, and Marvel plugins
to get the features that are bundled together in X-Pack. With X-Pack, you no longer have to
worry about whether or not you have the right version of each plugin, just install the X-Pack
for the Elasticsearch version you're running, and you're good to go!

[float]
=== Where to Go Next

* <<installing-xpack, Installing X-Pack>>
* <<security-getting-started, Getting Started with Security>>
* <<monitoring-getting-started, Getting Started with Monitoring>>
* <<watcher-getting-started, Getting Started with Alerting and Notification>>
// TO-DO: Update link: * <<reporting-getting-started, Getting Started with Reporting>>
// TO-DP: Update link: * <<graph-getting-started, Getting Started with Graph>>
* <<ml-getting-started, Getting Started with Machine Learning>>

[float]
=== Have Comments, Questions, or Feedback?

Head over to our discussion forums to share you experience, questions, and
suggestions:

* {security-forum}[Security Discussion Forum]
* {monitoring-forum}[Monitoring Discussion Forum]
* {watcher-forum}[Alerting & Notification Discussion Forum]
* {graph-forum}[Graph Discussion Forum]
