[[installing-xpack]]
=== Installing {xpack}

To use {xpack} you need:

* {es} {version} - {ref}/_installation.html[Installing {es}]
* {Es} {version} -  {kibana-ref}/setup.html[Getting {kib} Up and Running]

You must run the version of {xpack} that matches the version of {es}
you are running.

{xpack} also provides a monitoring UI for {logstash-ref}/introduction.html[Logstash].

To install {xpack}:

. {ref}/installing-xpack-es.html[Install {xpack} on {es}]
. {kibana-ref}/installing-xpack-kb.html[Install {xpack} on {kib}]
. {logstash-ref}/installing-xpack-log.html[Install {xpack} on Logstash]

NOTE: The {xpack} installation scripts require direct internet access to
download and install {xpack}. If your servers don’t have internet access, you
can manually download the {xpack} zip file and transfer it to a temporary
directory on the offline machines. The plugins for {es}, {kib} and Logstash are
all included in a single zip file. For more information about installing {xpack}
on offline machines, see the product-specific {xpack} installation instructions.

[float]
[[xpack-enabling]]
==== Enabling and Disabling {xpack} Features

By default, all {xpack} features are enabled. You can enable or disable specific
{xpack} features in the `elasticsearch.yml`, `kibana.yml`, and `logstash.yml`
configuration files.

[options="header"]
|======
| Setting                           | Description
| `xpack.graph.enabled`             | Set to `false` to disable {graph} features.
| `xpack.ml.enabled`                | Set to `false` to disable {xpackml} features.
| `xpack.monitoring.enabled`        | Set to `false` to disable {monitoring} features.
| `xpack.reporting.enabled`         | Set to `false` to disable {reporting} features.
| `xpack.security.enabled`          | Set to `false` to disable {security} features.
| `xpack.watcher.enabled`           | Set to `false` to disable {watcher}.
|======

For more information about which settings exist in each configuration file, see
{xpack-ref}/xpack-settings.html[X-Pack Settings].
