[[license-management]]
= License Management

[partintro]
--
When you initially install X-Pack, a 30 day trial license is installed that allows access to all features. At the end of the trial period, you can https://www.elastic.co/subscriptions/[purchase a subscription] to keep using the full functionality of the X-Pack components.

IMPORTANT:  When your license expires, X-Pack operates in a degraded mode. For more information, see  <<license-expiration, License Expiration>>.
--

[[installing-license]]
== Updating Your License

You can update your license at runtime without shutting down your nodes. License updates take
effect immediately. The license is provided as a _JSON_ file that you install with the `license`
API.

When Security is enabled, you need cluster admin privileges to install the license.
The <<built-in-users, built-in `elastic` user>> has the required privileges.

To update your license:

. Send a request to the `license` API and specify the file that contains your new license:
+
--
[source,shell]
-----------------------------------------------------------------------
curl -XPUT -u elastic 'http://<host>:<port>/_xpack/license' -H "Content-Type: application/json" -d @license.json
-----------------------------------------------------------------------
// NOTCONSOLE

Or on windows machine:

[source,shell]
-----------------------------------------------------------------------
gc .\license.json |  Invoke-WebRequest -uri http://<host>:<port>/_xpack/license -Credential elastic -Method Put
-----------------------------------------------------------------------
// NOTCONSOLE

Where:

* `elastic` is the built-in super user. The default password is `changeme`. If
you haven't already, <<built-in-users, change the default password>>. Any user
with cluster admin privileges can  install the license.
* `<host>` is the hostname of the Elasticsearch node (`localhost` if executing locally)
* `<port>` is the http port (defaults to `9200`)
* `license.json` is the license JSON file
--

. If the license you are installing does not support all of the features available with your
previous license, you will be notified in the response. To complete the license installation,
you must resubmit the license update request and set the `acknowledge` parameter to `true` to
indicate that you are aware of the changes.
+
[source,shell]
-----------------------------------------------------------------------
curl -XPUT -u elastic 'http://<host>:<port>/_xpack/license?acknowledge=true' -H "Content-Type: application/json" -d @license.json
-----------------------------------------------------------------------
// NOTCONSOLE

[[listing-licenses]]
== Viewing the Installed License

You can also use the `license` API to retrieve the currently installed license:

[source,shell]
-----------------------------------------------------
curl -XGET -u elastic:changeme 'http://<host>:<port>/_xpack/license'
{
  "license" : {
    "status" : "active",
    "uid" : "0a98411f-73f4-4c67-954c-724874ed5488",
    "type" : "trial",
    "issue_date" : "2015-10-13T18:18:20.709Z",
    "issue_date_in_millis" : 1444760300709,
    "expiry_date" : "2015-11-12T18:18:20.709Z",
    "expiry_date_in_millis" : 1447352300709,
    "max_nodes" : 1000,
    "issued_to" : "elasticsearch",
    "issuer" : "elasticsearch"
  }
}
--------------------------------------------
// NOTCONSOLE

NOTE: You need cluster admin privileges to retrieve the license.

[[license-expiration]]
== License Expiration

If you're using Monitoring, a license expiration warning is displayed prominently if your license expires
within 30 days. Warnings are also displayed on startup and written to the Elasticsearch log starting 30  days from
the expiration date. These error messages tell you when the license expires and what features will be disabled if
you fail to update it.

=== Watcher
* PUT / GET watch APIs are disabled, DELETE watch API continues to work
* Watches execute and write to the history
* The actions of the watches don't execute

=== Monitoring
* The agent will stop collecting cluster and indices metrics
* The agent will stop automatically cleaning indices older than [xpack.monitoring.history.duration]

=== Graph
* Graph explore APIs are disabled

=== Reporting
* Reporting will no longer be available in the Kibana UI
* Report generation urls will stop working
* Existing reports will no longer be accessible

=== Security
* Cluster health, cluster stats and indices stats operations are blocked
* All data operations (read and write) continue to work

Once the license expires, calls to the cluster health, cluster stats, and index stats APIs
fail with a `security_exception` and return a 403 HTTP status code.

[source,sh]
--------------------------------------------
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "current license is non-compliant for [security]",
        "license.expired.feature": "security"
      }
    ],
    "type": "security_exception",
    "reason": "current license is non-compliant for [security]",
    "license.expired.feature": "security"
  },
  "status": 403
}
--------------------------------------------

This enables  automatic monitoring systems to easily detect the license failure without immediately impacting other users.

IMPORTANT: You should update your license as soon as possible. You're essentially flying blind when running with an expired license. Access to the cluster health and stats APIs is critical
for monitoring and managing an Elasticsearch cluster.
