
[[xpack-release-notes]]
= Release Notes

[partintro]
--
This section summarizes the changes in each release for all of the {xpack}
components: {security}, {monitoring}, {watcher}, {reporting}, {xpackml}, and
{graph}.

As a general rule, we strive to keep backwards compatibility between minor
versions, but there might be breaking changes between major versions. Breaking
changes are listed at the top of the release notes for each version.

--

[[xpack-change-list]]
== Change List

[float]

[[xpack-6.0.0-beta1]]
=== 6.0.0-beta1
August 8, 2017

[float]
[[breaking-6.0.0-beta1]]
==== Breaking Changes
Reporting::
* When {security} is enabled, reports will only be accessible to the user that created them.
* When {security} is enabled, user authorization is controlled by the
`xpack.reporting.roles.allow` setting in the `kibana.yml` which defaults to
`['reporting_user']`. Users will no longer have access to the underlying {reporting}
indices in {es} when assigned to the built-in `reporting_user` role. If using
custom reporting roles, the privileges to the indices will need to be removed, and the
role will need to be added to the `xpack-reporting.roles.allow` setting.

Security::
* A new bootstrap check enforces that TLS/SSL is required for inter-node
communication when running in
{ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
See <<encrypting-communications>>.
* A new bootstrap check enforces that HTTPS is used by the built-in token
service when running in
{ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
To disable the token service, set `xpack.security.authc.token.enabled`
to `false` in your `elasticsearch.yml`. See
{ref}/security-settings.html#token-service-settings[Token Service Settings].


[float]
[[xpack-6.0.0-alpha2]]
=== 6.0.0-alpha2
June 6, 2017

[float]
[[breaking-6.0.0-alpha2]]
==== Breaking Changes

Watcher::
* The watch `_status` field has been renamed to `status`, as underscores in
field names will not be allowed.

[float]
[[features-6.0.0-alpha2]]
==== New Features

Reporting::
* Enabled export as CSV.

Security::
* Added a View Dashboards Only setting to the roles section under
Security management. If a user is assigned a role that has this setting
enabled, when they access Kibana it presents Dashboard Only mode.

[float]
[[enhancements-6.0.0-alpha2]]
==== Enhancements

Machine Learning::
* Added a Datefeed Preview tab to expanded rows in the jobs list under
Job Management. This displays the JSON response from the preview endpoint.

Security::
* Adapted indices resolution to use new `ignoreAliases` index option.
* Added the `logstash_admin` role, which provides access
to `.logstash-*` indices for managing configurations.

Watcher::
* Watcher indices no longer use multiple types.

[float]
[[bugs-6.0.0-alpha2]]
==== Bug Fixes

Graph::
* Reinstated `_xpack/graph/_explore` as the correct graph endpoint. `_xpack/_graph/_explore` is deprecated and will be removed in v7.0.

Machine Learning::
* If the initial cluster state update to install the Machine Learning
Metadata fails, the update is now retried.

[float]
[[xpack-6.0.0-alpha1]]
=== 6.0.0-alpha1
May 9, 2017

[float]
[[breaking-6.0.0]]
==== Breaking Changes

Security::
* A new bootstrap check enforces that <<disabling-default-password, default passwords are disabled>> for the <<built-in-users, built-in users>>
  when running in {ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
  You must set `xpack.security.authc.accept_default_password` to `false` in your `elasticsearch.yml`
* A new configuration setting is available to <<disabling-default-password, disable support for the default password>> (_"changeme"_).

Watcher::
* The built-in HTTP client used in webhooks, the http input and the http email attachment has been replaced.
This results in the need to always escape all parts of an URL.
* The new built-in HTTP client also enforces a maximum request size, which defaults to 10mb.

[float]
[[bugs-6.0.0-alpha1]]
==== Bug Fixes

Watcher::
* The HTTP client respects timeouts now and does not get stuck leading to stuck watches
