[[installing-xpack]]
== Installing X-Pack

To use X-Pack you need:

* Elasticsearch {version} - {ref}/_installation.html[Installing Elasticsearch]
* Kibana {version} -  {kibana-ref}/setup.html[Getting Kibana Up and Running]

You must run the version of {xpack} that matches the version of Elasticsearch
you are running.

{xpack} also provides a monitoring UI for {logstash-ref}/introduction.html[Logstash].

To install {xpack}:

. {ref}/installing-xpack-es.html[Install {xpack} on {es}]
. {kibana-ref}/installing-xpack-kb.html[Install {xpack} on {kib}]
. {logstash-ref}/installing-xpack-log.html[Install {xpack} on Logstash]

[float]
[[xpack-enabling]]
=== Enabling and Disabling {xpack} Features

By default, all {xpack} features are enabled. You can explicitly enable or
disable {xpack} features in `elasticsearch.yml` and `kibana.yml`:

[options="header"]
|======
| Setting                           | Description
| `xpack.graph.enabled`             | Set to `false` to disable {graph} features.
Configure in both `elasticsearch.yml` and `kibana.yml`.
| `xpack.ml.enabled`                | Set to `false` to disable {xpackml} features.
Configure in both `elasticsearch.yml` and `kibana.yml`.
| `xpack.monitoring.enabled`        | Set to `false` to disable {monitoring} features.
Configure in both `elasticsearch.yml` and `kibana.yml`.
| `xpack.reporting.enabled`         | Set to `false` to disable {reporting} features.
Configure in `kibana.yml` only.
| `xpack.security.enabled`          | Set to `false` to disable {security} features.
Configure in both `elasticsearch.yml` and `kibana.yml`.
| `xpack.watcher.enabled`           | Set to `false` to disable {watcher}.
Configure in `elasticsearch.yml` only.
|======

For more information, see <<xpack-settings>>.

[float]
[[xpack-upgrading]]
=== Upgrading {xpack}

To upgrade {xpack}:

. Stop Elasticsearch.

. Uninstall {xpack} from Elasticsearch:
+
[source,shell]
--------------------------------------------------
bin/elasticsearch-plugin remove x-pack
--------------------------------------------------

. Install the new version of {xpack} into Elasticsearch.
+
[source,shell]
----------------------------------------------------------
bin/elasticsearch-plugin install x-pack
----------------------------------------------------------

. Restart Elasticsearch.
+
IMPORTANT:  If you're upgrading a production cluster, perform a
            {ref}/rolling-upgrades.html[rolling upgrade] to ensure recovery is
            as quick as possible. Rolling upgrades are supported when upgrading
            to a new minor version. A full cluster restart is required when
            upgrading to a new major version.

. Uninstall {xpack} from Kibana:
+
[source,shell]
--------------------------------------------------
bin/kibana-plugin remove x-pack
--------------------------------------------------

. Install the new version of {xpack} into Kibana.
+
[source,shell]
----------------------------------------------------------
bin/kibana-plugin install x-pack
----------------------------------------------------------

. Restart Kibana.

[float]
[[xpack-uninstalling]]
=== Uninstalling {xpack}

To uninstall {xpack}:

. Stop Elasticsearch.

. Remove {xpack} from Elasticsearch:
+
[source,shell]
----------------------------------------------------------
bin/elasticsearch-plugin remove x-pack
----------------------------------------------------------

. Restart Elasticsearch.

. Remove {xpack} from Kibana:
+
[source,shell]
----------------------------------------------------------
bin/kibana-plugin remove x-pack
----------------------------------------------------------

. Restart Kibana.

. Remove {xpack} from Logstash:
+
[source,shell]
----------------------------------------------------------
bin/logstash-plugin remove x-pack
----------------------------------------------------------

. Restart Logstash.
