[[xpack-upgrading]]
=== Upgrading {xpack}

You must upgrade all of the Elastic Stack products you are using when upgrading
to a new major version. See
{stack-ref}/upgrading-elastic-stack.html[Upgrading the Elastic Stack].

IMPORTANT: If you use {security} and are upgrading directly to
{version} from 5.5 or earlier, you must upgrade the `.security` index
after you restart Elasticsearch. Native realm users will not be able to
authenticate until the index is upgraded. For instructions, see
{stack-ref}/upgrading-elastic-stack.html#upgrade-internal-indices[Upgrading
internal indices]. You also need to upgrade the `.security` index if
you restore a pre-5.6 snapshot to a fresh 6.0 install.

To upgrade {xpack}:

. Stop any {ml} jobs that are running before starting the upgrade process. See
<<stopping-ml>>.

. Stop {es}.

. Uninstall {xpack} from {es}:
+
[source,shell]
--------------------------------------------------
bin/elasticsearch-plugin remove x-pack
--------------------------------------------------

. {ref}/installing-xpack-es.html[Install the new version of {xpack} into {es}].

. Restart {es}.
+
IMPORTANT:  If you're upgrading a production cluster, perform a
            {ref}/rolling-upgrades.html[rolling upgrade] to ensure recovery is
            as quick as possible. Rolling upgrades are supported when upgrading
            to a new minor version. A full cluster restart is required when
            upgrading to a new major version.

. Uninstall {xpack} from {kib}:
+
[source,shell]
--------------------------------------------------
bin/kibana-plugin remove x-pack
--------------------------------------------------

. {kibana-ref}/installing-xpack-kb.html[Install the new version of {xpack} into {kib}].

. Restart {kib}.

. Uninstall {xpack} from Logstash:
+
[source,shell]
----------------------------------------------------------
bin/logstash-plugin remove x-pack
----------------------------------------------------------

. {logstash-ref}/installing-xpack-log.html[Install the new version of {xpack} into Logstash].

. Restart Logstash.
