
[[xpack-release-notes]]
= Release Notes

[partintro]
--
This section summarizes the changes in each release for all of the {xpack}
components: {security}, {monitoring}, {watcher}, {reporting}, {xpackml}, and
{graph}.

As a general rule, we strive to keep backwards compatibility between minor
versions, but there might be breaking changes between major versions. Breaking
changes are listed at the top of the release notes for each version.

--

[[xpack-change-list]]
== Change List


[float]
[[xpack-6.0.0]]
=== 6.0.0-alpha1
May 9, 2017

[float]
[[breaking-6.0.0]]
==== Breaking Changes

Security::
* A new bootstrap check enforces that <<disabling-default-password, default passwords are disabled>> for the <<built-in-users, built-in users>>
  when running in {ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
  You must set `xpack.security.authc.accept_default_password` to `false` in your `elasticsearch.yml`
* A new configuration setting is available to <<disabling-default-password, disable support for the default password>> (_"changeme"_).

Watcher::
* The built-in HTTP client used in webhooks, the http input and the http email attachment has been replaced.
This results in the need to always escape all parts of an URL.
* The new built-in HTTP client also enforces a maximum request size, which defaults to 10mb.

[float]
[[bugs-6.0.0]]
==== Bug Fixes

Watcher::
* The HTTP client respects timeouts now and does not get stuck leading to stuck watches
