[[xpack-upgrading]]
=== Upgrading {xpack}

You must upgrade all of the Elastic Stack products you are using when upgrading
to a new major version.

****
The steps you need to take to upgrade differ depending on which products you
are using. Want a list that's tailored to your stack? Try out our
{upgrade_guide}[Interactive Upgrade Guide].
****

IMPORTANT: If you use {security} and are upgrading directly to
{version} from 5.5 or earlier, you must upgrade the `.security` index
after you restart {es}. Native realm users will not be able to
authenticate until the index is upgraded. For instructions, see
{stack-ref}/upgrading-elastic-stack.html#upgrade-internal-indices[Upgrading
internal indices]. You also need to upgrade the `.security` index if
you restore a pre-5.6 snapshot to a fresh 6.0 install.

To upgrade {xpack}:

. Stop any {ml} jobs that are running before starting the upgrade process. See
<<stopping-ml>>.

. Stop {es}.

. Uninstall {xpack} from {es}:
+
[source,shell]
--------------------------------------------------
bin/elasticsearch-plugin remove x-pack
--------------------------------------------------

. If you have not already done so,
{ref}/setup-upgrade.html[upgrade {es}].
+
--
IMPORTANT: If you use {monitoring}, re-use the data directory when you upgrade
{es}. Monitoring identifies unique {es} nodes by using the persistent UUID, which
is stored in the data directory. For more information about the location of the
data directory, see {ref}/path-settings.html[path.data and path.logs].

--

. {ref}/installing-xpack-es.html[Install the new version of {xpack} into {es}].

. Restart {es}.
+
--
IMPORTANT:  If you're upgrading a production cluster, perform a
            {ref}/rolling-upgrades.html[rolling upgrade] to ensure recovery is
            as quick as possible. Rolling upgrades are supported when upgrading
            to a new minor version. A full cluster restart is required when
            upgrading to a new major version.

--

. Uninstall {xpack} from {kib}:
+
--
[source,shell]
--------------------------------------------------
bin/kibana-plugin remove x-pack
--------------------------------------------------
--

. If you have not already done so,
{kibana-ref}/upgrade.html[upgrade {kib}].
+
--
IMPORTANT: If you use {monitoring}, you must re-use the data directory when you
upgrade {kib}. Otherwise, the {kib} instance is assigned a new persistent UUID
and becomes a new instance in the monitoring data.

--

. {kibana-ref}/installing-xpack-kb.html[Install the new version of {xpack} into {kib}].

. Restart {kib}.

. Uninstall {xpack} from Logstash:
+
--
[source,shell]
----------------------------------------------------------
bin/logstash-plugin remove x-pack
----------------------------------------------------------
--

. If you have not already done so,
{logstash-ref}/upgrading-logstash.html[upgrade Logstash].
+
--
IMPORTANT: If you use {monitoring}, you must re-use the data directory when you
upgrade Logstash. Otherwise, the Logstash node is assigned a new persistent UUID
and becomes a new node in the monitoring data.

--

. {logstash-ref}/installing-xpack-log.html[Install the new version of {xpack} into Logstash].

. Restart Logstash.
