[[xpack-features]]
= More X-Pack Features in Kibana

[partintro]
--
{xpack} contains additional features such as reporting, graphing, and the
search profiler tool, which is described in the {kib} documentation.
--

== Graphing Connections in Your Data

{xpack} graph capabilities enable you to discover how items in an {es} index are
related. You can explore the connections between indexed terms and see which
connections are the most meaningful.

//TO-DO: Add link to content in Kibana Ref

== Reporting from Kibana

{xpack} enables you to generate reports that contain {kib} dashboards,
visualizations, and saved searches. The reports are exported as
print-optimized PDF documents.
//TO-DO: Re-add Link:
//For more information, see {kibana-ref}/xpack-reporting.html[X-Pack Reporting].

== Profiling your Queries and Aggregations

{xpack} includes the Search Profiler tool, which can transform the output from
the profiler API into a visualization that is easy to navigate.

//TO-DO:  Re-add link:
//For more information, see {kibana-ref}/...
