[[get-started-elastic-stack]]
== Getting started with the {stack}

Looking for a guide that shows how to quickly install and configure the {stack}
("ELK")? You're in the right place! You can install the {stack} on a single VM, 
or even on your laptop. Install each component in the following order:

* <<install-elasticsearch,{es}>>
* <<install-kibana,{kib}>>
* <<install-beats,{beats}>>

TIP: {ls} adds powerful data parsing and transformation features, but usually
isn't required. To get started with {ls}, see
{logstash-ref}/getting-started-with-logstash.html[Getting Started with {ls}].

After completing the installation process, learn how to implement a system
monitoring solution that uses {metricbeat} to collect server metrics and ship
the data to {es}. Then use {kib} to search and visualize the data.

[float]
[[install-prereqs]]
=== Before you begin

* See the https://www.elastic.co/support/matrix[Elastic Support
Matrix] for information about supported operating systems and product
compatibility.

* Verify that your system meets the
https://www.elastic.co/support/matrix#matrix_jvm[minimum JVM requirements] for
{es}.

[float]
[[install-elasticsearch]]
=== Install {es}

https://www.elastic.co/products/elasticsearch[{es}] is a real-time,
distributed storage, search, and analytics engine. It can be used for many
purposes, but one context where it excels is indexing streams of semi-structured
data, such as logs or decoded network packets.

[TIP]
==========
You can run {es} on your own hardware, or use our
https://www.elastic.co/cloud/elasticsearch-service[hosted {es} Service]
on Elastic Cloud. The {es} Service is available on both AWS and GCP.
{ess-trial}[Try out the
{es} Service for free].
==========

To download and install {es}, open a terminal window and use the commands that
work with your system:

* <<deb, deb>> for Debian/Ubuntu
* <<rpm, rpm>> for Redhat/Centos/Fedora
* <<mac, mac>> for OS X
* <<linux, linux>> for Linux
* <<win, win>> for Windows

When you start {es} for the first time, security features such as authentication, authorization and network encryption (TLS) for elasticsearch are enabled by default. The following security configuration
occurs automatically:

* {ref}/configuring-stack-security.html#stack-security-certificates[Certificates and keys] for TLS are
generated for the transport and HTTP layers.
* The TLS configuration settings are written to `elasticsearch.yml`.
* A password is generated for the `elastic` user.
* An enrollment token is generated for {kib}.

You can then start {kib} and enter the enrollment token to securely connect 
{kib} with {es}. The enrollment token is valid for 30 minutes.

[NOTE]
====
On `deb` and `rpm` installations, an enrollment token isn't generated for {kib}
during installation. To generate an enrollment token for {kib}, use the
{ref}/create-enrollment-token.html[`elasticsearch-create-enrollment-token`] tool.
====

[[deb]]*deb:*

ifeval::["{release-state}"=="unreleased"]

Version {elasticsearch_version} of {es} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{elasticsearch_version}-amd64.deb
sudo dpkg -i elasticsearch-{elasticsearch_version}-amd64.deb
sudo /etc/init.d/elasticsearch start
----

endif::[]

[[rpm]]*rpm:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {es} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{elasticsearch_version}-x86_64.rpm
sudo rpm -i elasticsearch-{elasticsearch_version}-x86_64.rpm
sudo service elasticsearch start
----------------------------------------------------------------------

endif::[]

[[mac]]*mac:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {es} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{elasticsearch_version}-darwin-x86_64.tar.gz
tar -xzvf elasticsearch-{elasticsearch_version}-darwin-x86_64.tar.gz
cd elasticsearch-{elasticsearch_version}
./bin/elasticsearch
----------------------------------------------------------------------

endif::[]

[[linux]]*linux:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {es} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{elasticsearch_version}-linux-x86_64.tar.gz
tar -xzvf elasticsearch-{elasticsearch_version}-linux-x86_64.tar.gz
cd elasticsearch-{elasticsearch_version}
./bin/elasticsearch
----------------------------------------------------------------------

endif::[]

[[win]]*win:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {es} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

. Download the {es} {elasticsearch_version} Windows zip file from the
https://www.elastic.co/downloads/elasticsearch[{es} download] page.

. Extract the contents of the zip file to a directory on your computer, for
example, `C:\Program Files`.

. Open a command prompt as an Administrator and navigate to the directory that
contains the extracted files, for example:
+
["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
cd C:\Program Files\elasticsearch-{elasticsearch_version}
----------------------------------------------------------------------

. Start {es}:
+
["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
bin\elasticsearch.bat
----------------------------------------------------------------------

endif::[]

For other operating systems, go to the
https://www.elastic.co/downloads/elasticsearch[{es} download] page.

TIP: The default {ref}/important-settings.html#cluster-name[cluster.name] and
{ref}/important-settings.html#node-name[node.name] are `elasticsearch` and your hostname,
respectively. If you plan to keep using this cluster or add more nodes, it is a
good idea to change these default values to unique names. For details about
changing these and other settings in the `elasticsearch.yml` file, see
{ref}/settings.html[Configuring {es}].

To learn more about installing, configuring, and running {es}, read the
https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html[{es} Reference].

[float]
==== Make sure that {es} is up and running

Open a new terminal and verify that you can connect to your {es} cluster by
making an authenticated call. Enter the password for the `elastic` user when
prompted:

[source,shell]
----
curl --cacert $ES_PATH_CONF/certs/http_ca.crt -u elastic https://localhost:9200 
----
// NOTCONSOLE

`--cacert`::
Path to the generated `http_ca.crt` certificate for the HTTP layer. This file
is created in the {es} configuration directory, which is defined by the
`$ES_PATH_CONF` {ref}/settings.html#config-files-location[environment variable].

On Windows, if you don't have cURL installed, point your browser to the URL.

You should see a response similar to this:

["source","sh",subs="attributes"]
----------------------------------------------------------------------
{
  "name" : "QtI5dUu",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "v8OWkR1OQO-rgV8o_lRhEA",
  "version" : {
    "number" : "{elasticsearch_version}",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "f4d76bd413ecfbd5122c3aa5dc85465960f18afe",
    "build_date" : "2021-10-27T22:47:53.634020433Z",
    "build_snapshot" : false,
    "lucene_version" : "9.0.0",
    "minimum_wire_compatibility_version" : "7.16.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
----------------------------------------------------------------------


[float]
[[install-kibana]]
=== Install {kib}

https://www.elastic.co/products/kibana[{kib}] is an open source analytics and
visualization platform designed to work with {es}. You use {kib} to search,
view, and interact with data stored in {es} indices. You can easily perform
advanced data analysis and visualize your data in a variety of charts, tables,
and maps.

[TIP]
==========
Running our hosted {es} Service on https://www.elastic.co/cloud[Elastic Cloud]?
{kib} is enabled automatically in most templates.
==========

We recommend that you install {kib} on the same server as {es}, but it's not
required. If you install the products on different servers, you'll
need to change the URL (IP:PORT) of the {es} server in the {kib} configuration
file, `kibana.yml`, before starting {kib}.

To download and install {kib}, open a terminal window and use the commands that
work with your system:

* <<deb-rpm-linux,deb>> for Debian/Ubuntu/Redhat/Centos/Fedora
* <<kibana-mac,mac>> for OS X
* <<kibana-win,win>> for Windows

If this is the first time you're starting {kib}, this command generates a 
unique link in your terminal to enroll your {kib} instance with {es}.

. In your terminal, click the generated link to open {kib} in your browser.

. In your browser, paste the enrollment token that was generated in the terminal 
when you started {es}, and then click the button to connect your {kib} instance
with {es}.

. Log in to {kib} as the `elastic` user with the password that was generated
when you started {es}.

[NOTE]
====
If you need to reset the password for the `elastic` user or other
built-in users, run the {ref}/reset-password.html[`elasticsearch-reset-password`] tool.
To generate new enrollment tokens for {kib} or {es} nodes, run the
{ref}/create-enrollment-token.html[`elasticsearch-create-enrollment-token`] tool.
These tools are available in the {es} `bin` directory.
====

[[deb-rpm-linux]]*deb, rpm, or linux:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {kib} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/kibana/kibana-{kibana_version}-linux-x86_64.tar.gz
tar xzvf kibana-{kibana_version}-linux-x86_64.tar.gz
cd kibana-{kibana_version}-linux-x86_64/
./bin/kibana
----------------------------------------------------------------------

endif::[]

[[kibana-mac]]*mac:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {kib} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/kibana/kibana-{kibana_version}-darwin-x86_64.tar.gz
tar xzvf kibana-{kibana_version}-darwin-x86_64.tar.gz
cd kibana-{kibana_version}-darwin-x86_64/
./bin/kibana
----------------------------------------------------------------------

endif::[]

[[kibana-win]]*win:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {kib} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

. Download the {kib} {kibana_version} Windows zip file from the
https://www.elastic.co/downloads/kibana[{kib} download] page.

. Extract the contents of the zip file to a directory on your computer, for
example, `C:\Program Files`.

. Open a command prompt as an Administrator and navigate to the directory that
contains the extracted files, for example:
+
["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
cd C:\Program Files\kibana-{kibana_version}-windows
----------------------------------------------------------------------

. Start {kib}:
+
["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
bin\kibana.bat
----------------------------------------------------------------------

endif::[]

For other operating systems, go to the
https://www.elastic.co/downloads/kibana[{kib} download] page.

To learn more about installing, configuring, and running {kib}, read the
https://www.elastic.co/guide/en/kibana/current/index.html[{kib} Reference].

[float]
==== Access the {kib} web interface

To access the {kib} web interface, point your browser to port `5601`. For example,
http://127.0.0.1:5601[http://127.0.0.1:5601].

[float]
[[install-beats]]
=== Install {beats}

The {beats} are open source data shippers that you install as agents on your
servers to send operational data to {es}. {beats} can send data directly to {es}
or via {ls}, where you can further process and enhance the data.

Each Beat is a separately installable product. In this guide, you learn how
to install and run {metricbeat} with the `system` module enabled to collect system
metrics.

To learn more about installing and configuring other {beats}, see the Getting
Started documentation:

[options="header"]
|=======================
|Elastic {beats} | To capture
|{auditbeat-ref}/auditbeat-installation-configuration.html[{auditbeat}] |Audit data
|{filebeat-ref}/filebeat-installation-configuration.html[{filebeat}] |Log files
|{functionbeat-ref}/functionbeat-installation-configuration.html[{functionbeat}] |Cloud data
|{heartbeat-ref}/heartbeat-installation-configuration.html[{heartbeat}] |Availability monitoring
|{metricbeat-ref}/metricbeat-installation-configuration.html[{metricbeat}] |Metrics
|{packetbeat-ref}/packetbeat-installation-configuration.html[{packetbeat}] |Network traffic
|{winlogbeat-ref}/winlogbeat-installation-configuration.html[{winlogbeat}] |Windows event logs
|=======================


[float]
[[install-metricbeat]]
==== Install {metricbeat}

To download and install {metricbeat}, open a terminal window and use the commands
that work with your system:

*deb:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {metricbeat} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{version}-amd64.deb
sudo dpkg -i metricbeat-{version}-amd64.deb
------------------------------------------------

endif::[]

*rpm:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {metricbeat} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{version}-x86_64.rpm
sudo rpm -vi metricbeat-{version}-x86_64.rpm
------------------------------------------------

endif::[]

*mac:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {metricbeat} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{version}-darwin-x86_64.tar.gz
tar xzvf metricbeat-{version}-darwin-x86_64.tar.gz
------------------------------------------------

endif::[]

*linux:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {metricbeat} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{version}-linux-x86_64.tar.gz
tar xzvf metricbeat-{version}-linux-x86_64.tar.gz
------------------------------------------------

endif::[]

*win:*

ifeval::["{release-state}"=="unreleased"]

Version {version} of {metricbeat} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

. Download the {metricbeat} Windows zip file from the
https://www.elastic.co/downloads/beats/metricbeat[{metricbeat} download] page.

. Extract the contents of the zip file into `C:\Program Files`.

. Rename the ++metricbeat-{version}-windows++ directory to ++{metricbeat}++.

. Open a PowerShell prompt as an Administrator (right-click the PowerShell icon
and select *Run As Administrator*).

. From the PowerShell prompt, run the following commands to install {metricbeat}
as a Windows service:
+
[source,shell]
----------------------------------------------------------------------
PS > cd 'C:\Program Files\Metricbeat'
PS C:\Program Files\Metricbeat> .\install-service-metricbeat.ps1
----------------------------------------------------------------------
+
NOTE: If script execution is disabled on your system, set the execution policy
for the current session to allow the script to run. For example: `PowerShell.exe
-ExecutionPolicy UnRestricted -File .\install-service-metricbeat.ps1`.

endif::[]

For other operating systems, go to the
https://www.elastic.co/downloads/beats[{beats} download] page.

[float]
[[ship-system-logs]]
==== Ship system metrics to {es}

{metricbeat} provides pre-built modules that you can use to rapidly implement
and deploy a system monitoring solution, complete with sample dashboards and
data visualizations, in about 5 minutes.

In this section, you learn how to run the `system` module to collect metrics
from the operating system and services running on your server. The system module
collects system-level metrics, such as CPU usage, memory, file system, disk IO,
and network IO statistics, as well as statistics for every process
running on your system.

*Before you begin*: Verify that {es} and {kib} are running and that {es} is
ready to receive data from {metricbeat}.

To set up the `system` module and start collecting system metrics:

. From the {metricbeat} install directory, enable the `system` module:
+
*deb and rpm:*
+
[source,yaml]
----
sudo metricbeat modules enable system
----
+
*mac and linux:*
+
[source,yaml]
----
./metricbeat modules enable system
----
+
*win:*
+
[source,yaml]
----
PS C:\Program Files\Metricbeat> .\metricbeat.exe modules enable system
----

. Set up the initial environment:
+
*deb and rpm:*
+
[source,yaml]
----
sudo metricbeat setup -e
----
+
*mac and linux:*
+
[source,yaml]
----
./metricbeat setup -e
----
+
*win:*
+
[source,yaml]
----
PS C:\Program Files\Metricbeat> metricbeat.exe setup -e
----
+
The `setup` command loads the {kib} dashboards. If the dashboards are already
set up, omit this command. The `-e` flag is optional and sends output to
standard error instead of syslog.

. [[gs-start-metricbeat]]Start {metricbeat}:
+
*deb and rpm:*
+
[source,yaml]
----
sudo service metricbeat start
----
+
*mac and linux:*
+
[source,yaml]
----
./metricbeat -e
----
+
*win:*
+
[source,yaml]
----
PS C:\Program Files\Metricbeat> Start-Service metricbeat
----


{metricbeat} runs and starts sending system metrics to {es}.

[float]
[[visualize-system-metrics]]
==== Visualize system metrics in {kib}

To visualize system metrics, open your browser and navigate to the {metricbeat}
system overview dashboard: http://localhost:5601/app/kibana#/dashboard/Metricbeat-system-overview-ecs

TIP: If you don’t see data in {kib}, try changing the date range to a larger
range. By default, {kib} shows the last 15 minutes. If you see errors, make
sure {metricbeat} is running, then refresh the page.

Click *Host Overview* to see detailed metrics about the selected host.

[float]
[[whats_next]]
==== What's next?

Congratulations! You've successfully set up the {stack} and securely connected
{kib} with {es}. You learned how to stream system metrics to {es} and visualize
the data in {kib}. 

Next, you'll want to {kibana-ref}/managing-licenses.html[activate your trial license]
to unlock the full capabilities of the {stack}.

Want to get up and running quickly with metrics monitoring and
centralized log analytics? Try out the Metrics app and the Logs app in {kib}.
For more details, see  
{observability-guide}/analyze-metrics.html[Analyze metrics] and  
{observability-guide}/monitor-logs.html[Monitor logs].

Later, when you're ready to set up a production environment, also see the
{stack-ref}/installing-elastic-stack.html[{stack} Installation and Upgrade
Guide].
