[[connection-to-external-network-via-telnet]]
=== Connection to External Network via Telnet

Telnet provides a command line interface for communication with a remote device or server. This rule identifies Telnet network connections to publicly routable IP addresses.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Linux

*Version*: 1

*Added ({stack} release)*: 7.8.0


==== Potential false positives

Telnet can be used for both benign or malicious purposes. Telnet is included by default in some Linux distributions, so its presence is not inherently suspicious. The use of Telnet to manage devices remotely has declined in recent years in favor of more secure protocols such as SSH. Telnet usage by non-automated tools or frameworks may be suspicious.

==== Rule query


[source,js]
----------------------------------
event.action:("connected-to" or "network_flow") and
process.name:telnet and not destination.ip:(127.0.0.0/8 or 10.0.0.0/8
or 172.16.0.0/12 or 192.168.0.0/16 or "FE80::/10" or "::1/128")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Lateral Movement
** ID: TA0008
** Reference URL: https://attack.mitre.org/tactics/TA0008/
* Technique:
** Name: Remote Services
** ID: T1021
** Reference URL: https://attack.mitre.org/techniques/T1021/
