[[hping-process-activity]]
=== Hping Process Activity

Hping ran on a Linux host. Hping is a FOSS command-line packet analyzer and has
the ability to construct network packets for a wide variety of network security
testing applications, including scanning and firewall auditing.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://en.wikipedia.org/wiki/Hping

*Tags*:

* Elastic
* Linux

*Version*: 2 (<<hping-process-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Normal use of hping is uncommon apart from security testing and research. Use by
non-security engineers is very uncommon.

==== Rule query


[source,js]
----------------------------------
process.name:(hping or hping2 or hping3) and event.action:executed
----------------------------------


[[hping-process-activity-history]]
==== Rule version history

Version 2 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
process.name: (hping3 or hping2 or hping) and event.action:executed
----------------------------------

