[[ipsec-nat-traversal-port-activity]]
=== IPSEC NAT Traversal Port Activity

Detects events that could be describing IPSEC NAT Traversal traffic. IPSEC is a
VPN technology that allows one system to talk to another using encrypted
tunnels. NAT Traversal enables these tunnels to communicate over the Internet
where one of the sides is behind a NAT router gateway. This may be common on
your network, but this technique is also used by threat actors to avoid
detection.

*Rule type*: query

*Rule indices*:

* filebeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 2 (<<ipsec-nat-traversal-port-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.6.1


==== Potential false positives

Some networks may utilize these protocols but usage that is unfamiliar to local
network administrators can be unexpected and suspicious. Because this port is in
the ephemeral range, this rule may false under certain conditions, such as when
an application server with a public IP address replies to a client which has
used a UDP port in the range by coincidence. This is uncommon but such servers
can be excluded.

==== Rule query


[source,js]
----------------------------------
network.transport:udp and destination.port:4500
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/

[[ipsec-nat-traversal-port-activity-history]]
==== Rule version history

Version 2 (7.6.1 release)::
* Removed auditbeat-\*, packetbeat-*, and winlogbeat-* from the rule indices.
