[[mknod-process-activity]]
=== Mknod Process Activity

The Linux `mknod` program is sometimes used in the command payload of a remote
command injection (RCI) and other exploits. It is used to export a command shell
when the traditional version of `netcat` is not available to the payload.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://pen-testing.sans.org/blog/2013/05/06/netcat-without-e-no-problem

*Tags*:

* Elastic
* Linux

*Version*: 2 (<<mknod-process-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Mknod is a Linux system program. Some normal use of this program, at varying
levels of frequency, may originate from scripts, automation tools, and
frameworks. Usage by web servers is more likely to be suspicious.

==== Rule query


[source,js]
----------------------------------
process.name:mknod and event.action:executed
----------------------------------


[[mknod-process-activity-history]]
==== Rule version history

Version 2 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
process.name: mknod and event.action:executed
----------------------------------

