[[strace-process-activity]]
=== Strace Process Activity

Strace runs in a privileged context and can be used to escape restrictive
environments by instantiating a shell in order to elevate privileges or move
laterally.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://en.wikipedia.org/wiki/Strace

*Tags*:

* Elastic
* Linux

*Version*: 2 (<<strace-process-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Strace is a dual-use tool that can be used for benign or malicious activity.
Some normal use of this command may originate from developers or SREs engaged in
debugging or system call tracing.

==== Rule query


[source,js]
----------------------------------
process.name:strace and event.action:executed
----------------------------------


[[strace-process-activity-history]]
==== Rule version history

Version 2 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
process.name: strace and event.action:executed
----------------------------------

