[[unusual-linux-web-activity]]
=== Unusual Linux Web Activity

A machine learning job detected an unusual web URL request from a Linux host,
which can indicate malware delivery and execution. Wget and cURL are commonly
used by Linux programs to download code and data. Most of the time, their usage
is entirely normal. Generally, because they use a list of URLs, they repeatedly
download from the same locations. However, Wget and cURL are sometimes used to
deliver Linux exploit payloads, and threat actors use these tools to download
additional software and code. For these reasons, unusual URLs can indicate
unauthorized downloads or threat activity.

*Rule type*: machine_learning

*Machine learning job*: linux_anomalous_network_url_activity_ecs

*Machine learning anomaly threshold*: 50


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* Linux
* ML

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

A new and unusual program or artifact download in the course of software
upgrades, debugging, or troubleshooting could trigger this signal.
