[[unusual-web-request]]
=== Unusual Web Request

A machine learning job detected a rare and unusual URL that indicates unusual
web browsing activity. This can be due to initial access, persistence, command-
and-control, or exfiltration activity. For example, in a strategic web
compromise or watering hole attack, when a trusted website is compromised to
target a particular sector or organization, targeted users may receive emails
with uncommon URLs for trusted websites. These URLs can be used to download and
run a payload. When malware is already running, it may send requests to uncommon
URLs on trusted websites the malware uses for command-and-control communication.
When rare URLs are observed being requested for a local web server by a remote
source, these can be due to web scanning, enumeration or attack traffic, or they
can be due to bots and web scrapers which are part of common Internet background
traffic.

*Rule type*: machine_learning

*Machine learning job*: packetbeat_rare_urls

*Machine learning anomaly threshold*: 50


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* ML
* Packetbeat

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

Web activity that occurs rarely in small quantities can trigger this signal.
Possible examples are browsing technical support or vendor URLs that are used
very sparsely. A user who visits a new and unique web destination may trigger
this signal when the activity is sparse. Web applications that generate URLs
unique to a transaction may trigger this when they are used sparsely. Web
domains can be excluded in cases such as these.
