[[virtual-machine-fingerprinting]]
=== Virtual Machine Fingerprinting

An adversary may attempt to get detailed information about the operating system and hardware. This rule identifies common locations used to discover virtual machine hardware by a non-root user. This technique has been used by Pupy RAT and other malware.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Linux

*Version*: 1

*Added ({stack} release)*: 7.8.0


==== Potential false positives

Certain tools or automated software may enumerate hardware information. These tools can be exempted via user name or process arguments to eliminate potential noise.

==== Rule query


[source,js]
----------------------------------
event.action:executed and
process.args:("/sys/class/dmi/id/bios_version" or
"/sys/class/dmi/id/product_name" or "/sys/class/dmi/id/chassis_vendor"
or "/proc/scsi/scsi" or "/proc/ide/hd0/model") and not user.name:root
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: System Information Discovery
** ID: T1082
** Reference URL: https://attack.mitre.org/techniques/T1082/
