[[license-management]]
= License management

[partintro]
--
When you install the default distribution of the {stack}, you receive a basic 
license. For the full list of free features that are included in the basic 
license, see: https://www.elastic.co/subscriptions

If you want to try the platinum features, you can start a 30-day trial. Go to the 
{kibana-ref}/managing-licenses.html[License Management] page in {kib} or use the 
{ref}/start-trial.html[start trial API].

NOTE: You can initiate a trial license only if your cluster has not already 
activated a trial license for the current major product version. For example, if 
you have already activated a trial for v6.0, you cannot start a new trial until 
v7.0. To check your trial status, use the 
{ref}/get-trial-status.html[get trial status API].

At the end of the trial period, the platinum features operate in a 
<<license-expiration,degraded mode>>. You can revert to a basic license, extend 
the trial, or https://www.elastic.co/subscriptions/[purchase a subscription].

[float]
[[installing-license]]
== Updating your license

You can update your license at runtime without shutting down your nodes. License
updates take effect immediately. The license is provided as a _JSON_ file that
you install in {kib} or by using the {ref}/update-license.html[update license API].

TIP: If you are using a basic or trial license, {security-features} are disabled
by default. In all other licenses, {security-features} are enabled by default;
you must {ref}/secure-cluster.html[secure the {stack}] or disable
the {security-features}. 

--

[[license-expiration]]
== License expiration

Your license is time based and expires at a future date. If you're
using {monitor-features} and your license will expire within 30 days, a license
expiration warning is displayed prominently. Warnings are also displayed on
startup and written to the {es} log starting 30 days from the expiration date.
These error messages tell you when the license expires and what features will be
disabled if you fail to update the license.

[float]
[[expiration-kibana]]
=== Kibana
* Users can still log into {kib}.
* It is still usable for data exploration and visualization, but some features
are disabled.
* The license management UI is available to easily upgrade your license. See
<<installing-license>> and
{kibana-ref}/managing-licenses.html[License management].

[float]
[[expiration-watcher]]
=== Watcher
* The PUT and GET watch APIs are disabled. The DELETE watch API continues to work.
* Watches execute and write to the history.
* The actions of the watches do not execute.

[float]
[[expiration-monitoring]]
=== Monitoring
* The agent stops collecting cluster and indices metrics.
* The agent stops automatically cleaning indices older than
`xpack.monitoring.history.duration`.

[float]
[[expiration-graph]]
=== Graph
* Graph explore APIs are disabled.

[float]
[[expiration-reporting]]
=== Reporting
* Reporting is no longer be available in {kib}.
* Report generation URLs stop working.
* Existing reports are no longer accessible.

[float]
[[expiration-security]]
=== Security
* Cluster health, cluster stats, and indices stats operations are blocked.
* All data operations (read and write) continue to work.

Once the license expires, calls to the cluster health, cluster stats, and index
stats APIs fail with a `security_exception` and return a 403 HTTP status code.

[source,sh]
-----------------------------------------------------
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "current license is non-compliant for [security]",
        "license.expired.feature": "security"
      }
    ],
    "type": "security_exception",
    "reason": "current license is non-compliant for [security]",
    "license.expired.feature": "security"
  },
  "status": 403
}
-----------------------------------------------------

This message enables automatic monitoring systems to easily detect the license
failure without immediately impacting other users.

[float]
[[expiration-ml]]
=== Machine learning
* APIs to create jobs, open jobs, send data to jobs, create {dfeeds}, and start
{dfeeds} are disabled.
* All started {dfeeds} are stopped. All open jobs are closed.
* Existing job results continue to be available by using {kib} or APIs.

[float]
[[expiration-logstash]]
=== Logstash pipeline management
* Cannot create new pipelines or edit or delete existing pipelines from the UI.
* Cannot list or view existing pipelines from the UI.
* Cannot run Logstash instances which are registered to listen to existing pipelines.

IMPORTANT: You should update your license as soon as possible. You are
essentially flying blind when running with an expired license. Access to the
cluster health and stats APIs is critical for monitoring and managing an {es}
cluster.
