[[license-management]]
== License management

When you install the default distribution of the {stack}, you receive a basic 
license. For the full list of free features that are included in the basic 
license, see: https://www.elastic.co/subscriptions

If you want to try the platinum features, you can start a 30-day trial. Go to the 
{kibana-ref}/managing-licenses.html[License Management] page in {kib} or use the 
{ref}/start-trial.html[start trial API].

NOTE: You can initiate a trial license only if your cluster has not already 
activated a trial license for the current major product version. For example, if 
you have already activated a trial for v6.0, you cannot start a new trial until 
v7.0. To check your trial status, use the 
{ref}/get-trial-status.html[get trial status API].

At the end of the trial period, the platinum features operate in a degraded mode.
You can revert to a basic license, extend the trial, or
https://www.elastic.co/subscriptions/[purchase a subscription].

[discrete]
[[installing-license]]
=== Updating your license

See {kibana-ref}/managing-licenses.html#update-license[Update your license].

