["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.


[role="exclude",id="get-started-elastic-stack"]
=== Getting started with the Elastic Stack

See {stack-gs}/get-started-elastic-stack.html[Getting started with the {stack}].

[float]
[[logstash-setup]]
=== Configure Logstash to listen for Beats input

See {stack-gs}/get-started-elastic-stack.html#logstash-setup[Configure Logstash to listen for Beats input].

[role="exclude",id="xpack-security"]
=== Securing the {stack}

See <<elasticsearch-security>>. 

[role="exclude",id="security-reference"]
=== Reference
* <<security-privileges,Security privileges>>
* {ref}/security-settings.html[Security settings]
* {ref}/security-files.html[Security files]
* {ref}/security-api.html[Security API]
* {ref}/xpack-commands.html[Security commands]

[role="exclude",id="security-files"]
=== Security files

This page has moved. 
See {ref}/security-files.html[Security files].

[role="exclude",id="configuring-kerberos-realm"]
=== Kerberos authentication

See {ref}/configuring-kerberos-realm.html[Configuring a Kerberos realm].

[role="exclude",id="dataframe-limitations"]
=== {transform-cap} limitations

This page has moved. 
See {ref}/transform-limitations.html[{transform-cap} limitations].

[role="exclude",id="dataframe-troubleshooting"]
=== Troubleshooting {transforms}

This page has moved. 
See {ref}/transform-troubleshooting.html[Troubleshooting {transforms}].

[role="exclude",id="example-clientips"]
=== Finding suspicious client IPs by using scripted metrics

This page has moved. 
See {ref}/transform-examples.html#example-clientips[Finding suspicious client IPs by using scripted metrics].

[role="exclude",id="example-airline"]
=== Finding air carriers with the most delay

This page has moved. 
See {ref}/transform-examples.html#example-airline[Finding air carriers with the most delays].

[role="exclude",id="example-best-customers"]
=== Finding your best customers

This page has moved. 
See {ref}/transform-examples.html#example-best-customers[Finding your best customers].

[role="exclude",id="ecommerce-dataframes"]
=== Transforming the eCommerce sample data

This page has moved. 
See {ref}/ecommerce-transforms.html[Transforming the eCommerce sample data].

[role="exclude",id="dataframe-examples"]
=== {transform-cap} examples

This page has moved. 
See {ref}/transform-examples.html[{transform-cap} examples]

[role="exclude",id="df-api-quickref"]
=== {transform-cap} API quick reference

This page has moved. 
See {ref}/transform-api-quickref.html[API quick reference].


[role="exclude",id="ml-transforms-usage"]
=== When to use {transforms}

This page has moved. 
See {ref}/transform-usage.html[When to use {transforms}].

[role="exclude",id="ml-transform-overview"]
=== {transform-cap} overview

This page has moved. 
See {ref}/transform-overview.html[Overview].

[role="exclude",id="ml-dataframes"]
=== Transforming data

This page has moved. 
See {ref}/transforms.html[Transforming data].

