["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.


[role="exclude",id="get-started-elastic-stack"]
=== Getting started with the Elastic Stack

See {stack-gs}/get-started-elastic-stack.html[Getting started with the {stack}].

[float]
[[logstash-setup]]
=== Configure Logstash to listen for Beats input

See {stack-gs}/get-started-elastic-stack.html#logstash-setup[Configure Logstash to listen for Beats input].

[role="exclude",id="xpack-security"]
=== Securing the {stack}

See <<elasticsearch-security>>. 

[role="exclude",id="security-reference"]
=== Reference
* <<security-privileges,Security privileges>>
* {ref}/security-settings.html[Security settings]
* {ref}/security-files.html[Security files]
* {ref}/security-api.html[Security API]
* {ref}/xpack-commands.html[Security commands]

[role="exclude",id="security-files"]
=== Security files

This page has moved. 
See {ref}/security-files.html[Security files].

[role="exclude",id="configuring-kerberos-realm"]
=== Kerberos authentication

See {ref}/configuring-kerberos-realm.html[Configuring a Kerberos realm].

[role="exclude",id="dataframe-limitations"]
=== {transform-cap} limitations

This page has moved. 
See {ref}/transform-limitations.html[{transform-cap} limitations].

[role="exclude",id="dataframe-troubleshooting"]
=== Troubleshooting {transforms}

This page has moved. 
See {ref}/transform-troubleshooting.html[Troubleshooting {transforms}].

[role="exclude",id="example-clientips"]
=== Finding suspicious client IPs by using scripted metrics

This page has moved. 
See {ref}/transform-examples.html#example-clientips[Finding suspicious client IPs by using scripted metrics].

[role="exclude",id="example-airline"]
=== Finding air carriers with the most delay

This page has moved. 
See {ref}/transform-examples.html#example-airline[Finding air carriers with the most delays].

[role="exclude",id="example-best-customers"]
=== Finding your best customers

This page has moved. 
See {ref}/transform-examples.html#example-best-customers[Finding your best customers].

[role="exclude",id="ecommerce-dataframes"]
=== Transforming the eCommerce sample data

This page has moved. 
See {ref}/ecommerce-transforms.html[Transforming the eCommerce sample data].

[role="exclude",id="dataframe-examples"]
=== {transform-cap} examples

This page has moved. 
See {ref}/transform-examples.html[{transform-cap} examples]

[role="exclude",id="df-api-quickref"]
=== {transform-cap} API quick reference

This page has moved. 
See {ref}/transform-api-quickref.html[API quick reference].


[role="exclude",id="ml-transforms-usage"]
=== When to use {transforms}

This page has moved. 
See {ref}/transform-usage.html[When to use {transforms}].

[role="exclude",id="ml-transform-overview"]
=== {transform-cap} overview

This page has moved. 
See {ref}/transform-overview.html[Overview].

[role="exclude",id="ml-dataframes"]
=== Transforming data

This page has moved. 
See {ref}/transforms.html[Transforming data].

[role="exclude",id="xpack-alerting"]
=== Alerting on cluster and index events

This page has moved. 
See {ref}/xpack-alerting.html[Alerting on cluster and index events].

[role="exclude",id="watcher-getting-started"]
=== Getting started with Watcher

This page has moved. 
See {ref}/watcher-getting-started.html[Getting started with Watcher].

[role="exclude",id="how-watcher-works"]
=== How Watcher works

[[watch-definition]]
This page has moved.
[[watch-active-state]]
See {ref}/how-watcher-works.html[How Watcher works].

[role="exclude",id="encrypting-data"]
=== Encrypting sensitive data in Watcher

This page has moved. 
See {ref}/encrypting-data.html[Encrypting sensitive data in Watcher].

[role="exclude",id="input"]
=== Inputs

This page has moved. 
See {ref}/input.html[Inputs].

[role="exclude",id="input-simple"]
=== Simple input

This page has moved. 
See {ref}/input-simple.html[Simple input].

[role="exclude",id="input-search"]
=== Search input

This page has moved. 
See {ref}/input-search.html[Search input].

[role="exclude",id="input-http"]
=== HTTP input

This page has moved. 
See {ref}/input-http.html[HTTP input].

[role="exclude",id="input-chain"]
=== Chain input

This page has moved. 
See {ref}/input-chain.html[Chain input].

[role="exclude",id="trigger"]
=== Triggers

This page has moved. 
See {ref}/trigger.html[Triggers].

[role="exclude",id="trigger-schedule"]
=== Schedule trigger

[[schedule-cron]]
This page has moved. 
See {ref}/trigger-schedule.html[Schedule trigger].

[role="exclude",id="condition"]
=== Conditions

This page has moved. 
See {ref}/condition.html[Conditions].

[role="exclude",id="condition-always"]
=== Always condition

This page has moved. 
See {ref}/condition-always.html[Always condition].

[role="exclude",id="condition-never"]
=== Never condition

This page has moved. 
See {ref}/condition-never.html[Never condition].

[role="exclude",id="condition-compare"]
=== Compare condition

This page has moved. 
See {ref}/condition-compare.html[Compare condition].

[role="exclude",id="condition-array-compare"]
=== Array compare condition

This page has moved. 
See {ref}/condition-array-compare.html[Array compare condition].

[role="exclude",id="condition-script"]
=== Script condition

This page has moved. 
See {ref}/condition-script.html[Script condition].

[role="exclude",id="actions"]
=== Actions

[[actions-ack-throttle]]
This page has moved. 
See {ref}/actions.html[Actions].

[role="exclude",id="action-foreach"]
=== Running an action for each element in an array

This page has moved. 
See {ref}/action-foreach.html[Running an action for each element in an array].

[role="exclude",id="action-conditions"]
=== Adding conditions to actions

This page has moved. 
See {ref}/action-conditions.html[Adding conditions to actions].

[role="exclude",id="actions-email"]
=== Email action

[[configuring-email]]
This page has moved. 
[[email-html-sanitization]]
See {ref}/actions-email.html[Email action].
[[email-action-attributes]]
[[configuring-email-actions]]

[role="exclude",id="actions-webhook"]
=== Webhook action

This page has moved. 
See {ref}/actions-webhook.html[Webhook action].

[role="exclude",id="actions-index"]
=== Index action

This page has moved. 
See {ref}/actions-index.html[Index action].

[role="exclude",id="actions-logging"]
=== Logging action

This page has moved. 
See {ref}/actions-logging.html[Logging action].

[role="exclude",id="actions-slack"]
=== Slack action

[[configuring-slack-actions]]
This page has moved. 
See {ref}/actions-slack.html[Slack action].

[role="exclude",id="actions-pagerduty"]
=== PagerDuty action

[[pagerduty-event-trigger-incident-attributes]]
This page has moved. 
[[configuring-pagerduty-actions]]
See {ref}/actions-pagerduty.html[PagerDuty action].

[role="exclude",id="actions-jira"]
=== Jira action

[[jira-action-attributes]]
This page has moved.
[[configuring-jira-actions]]
See {ref}/actions-jira.html[Jira action].

[role="exclude",id="transform"]
=== Watcher transforms

This page has moved. 
See {ref}/transform.html[Watcher transforms].

[role="exclude",id="transform-search"]
=== Search transform

This page has moved. 
See {ref}/transform-search.html[Search transform].

[role="exclude",id="transform-script"]
=== Script transform

This page has moved. 
See {ref}/transform-script.html[Script transform].

[role="exclude",id="transform-chain"]
=== Chain transform

This page has moved. 
See {ref}/transform-chain.html[Chain transform].

[role="exclude",id="managing-watches"]
=== Managing watches

This page has moved. 
See {ref}/managing-watches.html[Managing watches].

[role="exclude",id="example-watches"]
=== Example watches

This page has moved. 
See {ref}/example-watches.html[Example watches].

[role="exclude",id="watch-cluster-status"]
=== Watching the status of an Elasticsearch cluster

This page has moved. 
See {ref}/watch-cluster-status.html[Watching the status of an Elasticsearch cluster].

[role="exclude",id="watching-meetup-data"]
=== Watching event data

This page has moved. 
See {ref}/watching-meetup-data.html[Watching event data].

[role="exclude",id="watcher-troubleshooting"]
=== Troubleshooting Watcher

This page has moved. 
See {ref}/watcher-troubleshooting.html[Troubleshooting Watcher].

[role="exclude",id="watcher-limitations"]
=== Watcher limitations

This page has moved. 
See {ref}/watcher-limitations.html[Watcher limitations].
