[role="xpack"]
[[ml-getting-started]]
== Tutorial: An introduction to machine learning

Ready to get some hands-on experience with the {ml-features}? This
tutorial shows you how to:

* Create single and multi-metric {ml} jobs in {kib}
* Use the results to identify possible anomalies in the data

At the end of this tutorial, you should have a good idea of what {ml} is and
will hopefully be inspired to use it to detect anomalies in your own data.

[float]
[[ml-gs-sysoverview]]
=== Before you begin

. Install {es} and {kib}.
+
--
{es} stores the data and the analysis results. {kib} provides a helpful user 
interface for creating and viewing jobs.

[TIP]
==========
You can run {es} and {kib} on your own hardware, or use our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}] on {ecloud}.
The {ess} is available on both AWS and GCP.
https://www.elastic.co/cloud/elasticsearch-service/signup[Try out the {ess} for free].
==========

For more information, see
{stack-gs}/get-started-elastic-stack.html[Getting started with the {stack}].
--

. Launch the {kib} web interface by pointing your browser to port 5601. For 
example, http://127.0.0.1:5601[http://127.0.0.1:5601].

. Obtain a license that includes the {ml-features}. 
+
--
include::{docdir}/get-started-trial.asciidoc[]
--

. If the {es} {security-features} are enabled in your cluster, you need a user
that has appropriate authority to perform the steps in this tutorial. 
+
--
[[ml-gs-users]]
The {ml-features} use cluster privileges and built-in roles to make it 
easier to control which users have authority to view and manage the jobs,
{dfeeds}, and results.

By default, you can perform all of the steps in this tutorial by using the
built-in `elastic` super user. However, the password must be set before the user
can do anything. For information about how to set that password, see
<<security-getting-started>>.

If you are performing these steps in a production environment, take extra care
because `elastic` has the `superuser` role and you could inadvertently make
significant changes to the system. You can alternatively assign the
`machine_learning_admin` and `kibana_admin` roles to a user ID of your choice.

For more information, see <<built-in-roles>> and <<privileges-list-cluster>>.

--

. Optional: If you have multiple nodes in your cluster, you can optionally 
dedicate nodes to specific purposes. If you want to control which nodes are
_machine learning nodes_ or limit which nodes run resource-intensive
activity related to jobs, see 
{ref}/modules-node.html#ml-node[{ml} node settings]. 

include::getting-started-data.asciidoc[]

include::getting-started-wizards.asciidoc[]

include::getting-started-single.asciidoc[]

////
include::getting-started-multi.asciidoc[]

include::getting-started-forecast.asciidoc[]

include::getting-started-next.asciidoc[]
////
