[role="xpack"]
[[ml-gs-data]]
=== Identifying data for analysis

For the purposes of this tutorial, we provide sample data that you can play with
and search in {es}. When you consider your own data, however, it's important to
take a moment and think about where the {ml-features} will be most
impactful.

The first consideration is that it must be time series data. The {ml-features}
are designed to model and detect anomalies in time series data.

The second consideration, especially when you are first learning to use {ml},
is the importance of the data and how familiar you are with it. Ideally, it is
information that contains key performance indicators (KPIs) for the health,
security, or success of your business or system. It is information that you need
to monitor and act on when anomalous behavior occurs. You might even have {kib}
dashboards that you're already using to watch this data. The better you know the
data, the quicker you will be able to create {ml} jobs that generate useful
insights.

The final consideration is where the data is located. This tutorial assumes you
are using sample data that is stored in {es}. It uses wizards that expedite the
creation of _{dfeeds}_, which pass data to {ml} jobs. If your own data is
outside of {es}, analysis is still possible by using the
{ref}/ml-post-data.html[post data to jobs API].

IMPORTANT: If you want to create {ml} jobs in {kib}, you must use {dfeeds}.
That is to say, you must store your input data in {es}. When you create
a job, you select an existing index pattern and {kib} configures the {dfeed}
for you under the covers.


[float]
[[ml-gs-sampledata]]
==== Obtaining a sample data set

In this step, we add the sample data sets that ship with {kib}: 

. Click the {kib} logo in the upper left hand corner of your browser to navigate
to the {kib} home page.

. Click *Load a data set and a Kibana dashboard*.

. Pick a data set. In this tutorial, we use the *Sample eCommerce orders* and
*Sample web logs*. While you're here, feel free to click *Add* on all of the
available sample data sets.

. If you want to familiarize yourself with the data, click
*View data* > *Dashboard*. 
+
--
For example, the Web Traffic dashboard for the sample web logs is a collection
of charts, graphs, maps, and other visualizations of the data in the
`kibana_sample_data_logs` index.
--

These data sets can now be analyzed in {ml} jobs in {kib}. For more information
about the {kib} sample data sets, see
{kibana-ref}/add-sample-data.html[Get up and running with sample data].
