[role="xpack"]
[[ml-jobs]]
=== {anomaly-jobs-cap}
++++
<titleabbrev>Jobs</titleabbrev>
++++

{anomaly-jobs-cap} contain the configuration information and metadata
necessary to perform an analytics task.

Each {anomaly-job} has one or more _detectors_. A detector applies an analytical
function to specific fields in your data. For more information about the types
of analysis you can perform, see <<ml-functions>>.

A job can also contain properties that affect which types of entities or events
are considered anomalous. For example, you can specify whether entities are
analyzed relative to their own previous behavior or relative to other entities
in a population. There are also multiple options for splitting the data into
categories and partitions. Some of these more advanced job configurations
are described in the following section: <<anomaly-examples>>.

For a description of all the job properties, see the 
{ref}/ml-put-job.html[create {anomaly-jobs} API].

In {kib}, there are wizards that help you create specific types of jobs, such
as _single metric_, _multi-metric_, and _population_ jobs. A single metric job
is just a job with a single detector and limited job properties. To have access
to all of the job properties in {kib}, you must choose the _advanced_ job wizard.

You can also optionally assign jobs to one or more _job groups_. You can use
job groups to view the results from multiple jobs more easily and to expedite
administrative tasks by opening or closing multiple jobs at once.
