[role="xpack"]
[[ootb-ml-jobs-metricbeat]]
= {metricbeat} {anomaly-detect} configurations
++++
<titleabbrev>{metricbeat}</titleabbrev>
++++

// tag::metricbeat-jobs[]
These {anomaly-job} wizards appear in {kib} if you use the 
{metricbeat-ref}/metricbeat-module-system.html[{metricbeat} system module] to 
monitor your servers. For more details, see the
{dfeed} and job definitions in https://github.com/elastic/kibana/tree/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/metricbeat_system_ecs/ml[GitHub].

These configurations are only available if data exists that matches the 
recognizer query specified in the
https://github.com/elastic/kibana/blob/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/metricbeat_system_ecs/manifest.json#L8[manifest file].


high_mean_cpu_iowait_ecs::

* For {metricbeat} data where `event.dataset` is `system.cpu` and 
  `system.filesystem`.
* Models CPU time spent in iowait for every `host.name`.
* Detects unusual increases in cpu time spent in iowait.

max_disk_utilization_ecs::

* For {metricbeat} data where `event.dataset` is `system.cpu` and 
  `system.filesystem`.
* Models disk utilization for each `host.name`.
* Detects unusual increases in disk utilization.

metricbeat_outages_ecs::

* For {metricbeat} data where `event.dataset` is `system.cpu` and 
  `system.filesystem`.
* Models counts of {metricbeat} documents.
* Detects unusual decreases in {metricbeat} documents.

// end::metricbeat-jobs[]