[role="xpack"]
[[ootb-ml-jobs]]
= Supplied {anomaly-detect} configurations
++++
<titleabbrev>Supplied configurations</titleabbrev>
++++

{anomaly-jobs-cap} contain the configuration information and metadata necessary 
to perform an analytics task. {kib} can recognize certain types of data and 
provide specialized wizards for that context. This page lists the categories of 
the {anomaly-jobs} that are ready to use via {kib} in **Machine learning**. 
Refer to <<create-jobs>> to learn more about creating a job by using supplied 
configurations. Logs and Metrics supplied configurations are available and can 
be created via the related solution in {kib}.

* <<ootb-ml-jobs-apache>>
* <<ootb-ml-jobs-apm>>
* <<ootb-ml-jobs-auditbeat>>
* <<ootb-ml-jobs-logs-ui>>
* <<ootb-ml-jobs-metricbeat>>
* <<ootb-ml-jobs-metrics-ui>>
* <<ootb-ml-jobs-nginx>>
* <<ootb-ml-jobs-siem>>
* <<ootb-ml-jobs-uptime>>


NOTE: The configurations are only available if data exists that matches the 
queries specified in the manifest files. These recognizer queries are listed in 
the descriptions of the individual configurations.