[[ootb-ml-jobs-apache]]
=== Apache {anomaly-detect} configurations
++++
<titleabbrev>Apache</titleabbrev>
++++
// tag::apache-jobs[]
These {anomaly-job} wizards appear in {kib} if you use 
{filebeat-ref}/index.html[{filebeat}] to ship access logs from your 
https://httpd.apache.org/[Apache] HTTP servers to {es} and store it using fields 
and data types from the Elastic Common Schema (ECS). For more details, see the
{dfeed} and job definitions in
https://github.com/elastic/kibana/tree/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/apache_ecs/ml[GitHub].

low_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests. 
* Detects unusually low counts of HTTP requests compared to the previous event 
  rate (using the <<ml-count,`low_count` function>>).

source_ip_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high request rates in the HTTP access log 
  compared to the previous rate (using the <<ml-count,`high_count` function>>).

source_ip_url_count_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high distinct count of URLs in the HTTP 
access log (using the <<ml-distinct-count,`high_distinct_count` function>>).

status_code_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the occurrences of HTTP response status codes (`partition_field_name` 
  is `http.response.status_code`).
* Detects unusual status code rates in the HTTP access log compared to previous 
  rates (using the <<ml-count,`count` function>>).

visitor_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models visitor rates.
* Detects unusual visitor rates in the HTTP access log ompared to previous 
  rates (using the <<ml-nonzero-count,`non_zero_count` function>>).
// end::apache-jobs[]