[role="xpack"]
[[ootb-ml-jobs-nginx]]
== Nginx {anomaly-detect} configurations
++++
<titleabbrev>Nginx</titleabbrev>
++++

// tag::nginx-jobs[]
These {anomaly-job} wizards appear in {kib} if you use {filebeat} to ship access 
logs from your http://nginx.org/[Nginx] HTTP servers to {es} and store it using 
fields and datatypes from the Elastic Common Schema (ECS). For more details, see
the {dfeed} and job definitions in
https://github.com/elastic/kibana/tree/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/nginx_ecs/ml[GitHub].

low_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `nginx.access`.
* Models the event rate of http requests. 
* Detects unusually low counts of HTTP requests compared to the previous event 
  rate (using the <<ml-count,`low_count` function>>).

source_ip_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `nginx.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high request rates in the HTTP access log 
  compared to the previous rate (using the <<ml-count,`high_count` function>>). 

source_ip_url_count_ecs::

* For HTTP web access logs where `event.dataset` is `nginx.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high distinct count of URLs in the HTTP 
  access log (using the <<ml-distinct-count,`high_distinct_count` function>>).

status_code_rate_ecs::

* For HTTP web access logs where `event.dataset` is `nginx.access`.
* Models the occurrences of HTTP response status codes (`partition_field_name` 
  is `http.response.status_code`).
* Detects unusual status code rates in the HTTP access log compared to previous 
  rates (using the <<ml-count,`count` function>>).

visitor_rate_ecs::

* For HTTP web access logs where `event.dataset` is `nginx.access`.
* Models visitor rates.
* Detects unusual visitor rates in the HTTP access log ompared to previous 
  rates (using the <<ml-nonzero-count,`non_zero_count` function>>).

// end::nginx-jobs[]