[role="xpack"]
[[ootb-ml-jobs-apache]]
= Apache {anomaly-detect} configurations
++++
<titleabbrev>Apache</titleabbrev>
++++
// tag::apache-jobs[]
These legacy {anomaly-job} wizards appear in {kib} if you use 
{filebeat-ref}/index.html[{filebeat}] to ship access logs from your 
https://httpd.apache.org/[Apache] HTTP servers to {es} and store it using fields 
and data types from the Elastic Common Schema (ECS). The latest versions are
installed with the Apache integration in {Fleet}. 

For more details, see the
{dfeed} and job definitions in
https://github.com/elastic/kibana/tree/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/apache_ecs/ml[GitHub].

These configurations are only available if data exists that matches the 
recognizer query specified in the 
https://github.com/elastic/kibana/blob/{branch}/x-pack/plugins/ml/server/models/data_recognizer/modules/apache_ecs/manifest.json#L8[manifest file].

low_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests. 
* Detects unusually low counts of HTTP requests compared to the previous event 
  rate.

source_ip_request_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high request rates in the HTTP access log 
  compared to the previous rate.

source_ip_url_count_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the event rate of HTTP requests by source IP.
* Detects source IPs with unusually high distinct count of URLs in the HTTP 
access log.

status_code_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models the occurrences of HTTP response status codes.
* Detects unusual status code rates in the HTTP access log compared to previous 
  rates.

visitor_rate_ecs::

* For HTTP web access logs where `event.dataset` is `apache.access`.
* Models visitor rates.
* Detects unusual visitor rates in the HTTP access log compared to previous 
  rates.
// end::apache-jobs[]