[role="xpack"]
[[ootb-ml-jobs]]
== Prebuilt {anomaly-detect} jobs

This page lists the available prebuilt {anomaly-jobs}. Every 
module item in the list contains a name, a short description, information about 
the {ml-docs}/ml-buckets.html#ml-buckets[`bucket_span`] and the 
{ml-docs}/ml-functions.html[analysis function] as well as the influencers – the 
entities that have contributed to, or are to blame for, the anomalies – of the 
{anomaly-detect} job.


[float]
[[ootb-ml-jobs-apache]]
=== Apache
These {anomaly-job} wizards appear in {kib} if you use {filebeat-ref}/index.html[{filebeat}] to ship access logs from your https://httpd.apache.org/[Apache] HTTP servers to {es} and store it using fields and datatypes from the Elastic Common Schema (ECS).
low_request_rate_ecs::
Detects low request rates in HTTP access log.
+
--
Bucket span: 15m.

Function: `low_count`.
--

source_ip_request_rate_ecs::
Detects source IPs with unusually high request rates in the HTTP access log.
+
--
Bucket span: 1h.

Function: `high_count`.

Influencers:

* `source.address`
--

source_ip_url_count_ecs::
Detects source IPs with unusually high distinct count of URLs in the HTTP access 
log.
+
--
Bucket span: 1h.

Function: `high_distinct_count`.

Influencers:

* `source.address`
--

status_code_rate_ecs::
Detects unusual status code rates in the HTTP access log.
+
--
Bucket span: 15m.

Function: `count`.

Influencers:

* `http.response.status_code` 
* `source.address`
--

visitor_rate_ecs::
Detects unusual visitor rates in the HTTP access log.
+
--
Bucket span: 15m.

Function: `non_zero_count`.
--

[float]
[[ootb-ml-jobs-apm]]
=== APM

abnormal_span_durations_jsbase::
abnormal_span_durations_nodejs::
Searches for spans that are taking longer than usual to process.
+
--
Bucket span: 15m.

Function: `high_mean`.

Influencers:

* `service.name` 
* `span.name`
* `span.type` 
* `trace.id`
--

abnormal_trace_durations_nodejs::
Identifies trace transactions that are processing more slowly than usual.
+
--
Bucket span: 15m.

Function: `high_mean`.

Influencers:

* `service.name` 
* `trace.id`
* `transaction.name` 
--

anomalous_error_rate_for_user_agents_jsbase::
Detects user agents that are encountering errors at an above normal rate. This 
can help detect browser compatibility issues.
+
--
Bucket span: 15m.

Function: `high_non_zero_count`.

Influencers:

* `user_agent.name`
* `error.exception.message.keyword`
* `error.page.url`
* `service.name`
--

decreased_throughput_jsbase::
decreased_throughput_nodejs::
Identifies periods during which the application is processing fewer requests 
than normal.
+
--
Bucket span: 15m.

Function: `low_count`.

Influencers:

* `service.name`
* `transaction.name`
--

high_count_by_user_agent_jsbase::
Detects user agents that are making requests at a suspiciously high rate. This 
is useful in identifying bots.
+
--
Bucket span: 15m.

Function: `high_non_zero_count`.

Influencers:

* `service.name`
* `user_agent.name`
--

high_mean_response_time::
Detects anomalies in high mean of transaction duration.
+
--
Bucket span: 15m.

Function: `high_mean`.
--


[float]
[[ootb-ml-jobs-auditbeat]]
=== Auditbeat
> These {anomaly-job} wizards appear in {kib} if you use {auditbeat-ref}/index.html[{auditbeat}] to audit process activity on your systems.
docker_high_count_process_events_ecs::
Detects unusual increases in process execution rates in Docker containers.
+
--
Bucket span: 1h.

Function: `high_count`.

Influencers:

* `container.name`
* `process.executable`
--

docker_rare_process_activity_ecs::
Detects rare process executions in Docker containers.
+
--
Bucket span: 1h.

Function: `rare`.

Influencers:

* `container.name`
* `process.executable`
--

hosts_high_count_process_events_ecs::
Detects unusual increases in process execution rates.
+
--
Bucket span: 1h.

Function: `high_non_zero_count`.

Influencers:

* `host.name`
* `process.executable`
--

hosts_rare_process_activity_ecs::
Detects rare process executions on hosts.
+
--
Bucket span: 1h.

Function: `rare`.

Influencers:

* `host.name`
* `process.executable`
--


[float]
[[ootb-ml-jobs-logs-ui]]
=== Logs UI

log_entry_categories_count::
Detects anomalies in count of log entries by category.
+
--
Bucket span: 15m.

Function: `count`.

Influencers:

* `event.dataset`
* `mlcategory`
--

log_entry_rate::
Detects anomalies in the log entry ingestion rate.
+
--
Bucket span: 15m.

Function: `count`.

Influencers:

* `event.dataset`
--

[float]
[[ootb-ml-jobs-metricbeat]]
=== Metricbeat
These {anomaly-job} wizards appear in {kib} if you use the {metricbeat-ref}/metricbeat-module-system.html[{metricbeat} system module] to monitor your servers.
high_mean_cpu_iowait_ecs::
Detects unusual increases in cpu time spent in iowait.
+
--
Bucket span: 10m.

Function: `high_mean`.

Influencers:

* `host.name`
--

max_disk_utilization_ecs::
Detects unusual increases in disk utilization.
+
--
Bucket span: 10m.

Function: `max`.

Influencers:

* `host.name`
--

metricbeat_outages_ecs::
Detects unusual decreases in Metricbeat documents.
+
--
Bucket span: 10m.

Function: `low_count`.

Influencers:

* `event.dataset`
--


[float]
[[ootb-ml-jobs-nginx]]
=== Nginx
 These {anomaly-job} wizards appear in {kib} if you use {filebeat} to ship access logs from your 
http://nginx.org/[Nginx] HTTP servers to {es} and store it using fields and datatypes from the Elastic Common Schema (ECS).
low_request_rate_ecs::
Detects low request rates in HTTP access log.
+
--
Bucket span: 15m.

Function: `low_count`.
--

source_ip_request_rate_ecs::
Detects source IPs with unusually high request rates in the HTTP access log. 
+
--
Bucket span: 1h.

Function: `high_count`.

Influencers:

* `source.address`
--

source_ip_url_count_ecs::
Detects source IPs with unusually high distinct count of URLs in the HTTP access 
log.
+
--
Bucket span: 1h.

Function: `high_distinct_count`.

Influencers:

* `source.address`
--

status_code_rate_ecs::
Detects unusual status code rates in the HTTP access log.
+
--
Bucket span: 15m.

Function: `count`.

Influencers:

* `http.response.status_code` 
* `source.address`
--

visitor_rate_ecs::
Detects unusual visitor rates in the HTTP access log.
+
--
Bucket span: 15m.

Function: `non_zero_count`.
--


[float]
[[ootb-ml-jobs-siem]]
=== SIEM

linux_anomalous_network_activity_ecs::
windows_anomalous_network_activity_ecs::
Looks for unusual processes using the network which could indicate 
command-and-control, lateral movement, persistence, or data exfiltration 
activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat (Linux)
* Winlogbeat (Windows)

Influencers:

* `destination.ip`
* `host.name` 
* `process.name`
* `user.name`
--

linux_anomalous_network_port_activity_ecs::
Looks for unusual destination port activity that could indicate 
command-and-control, persistence mechanism, or data exfiltration activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat 

Influencers:

* `destination.ip`
* `host.name` 
* `process.name`
* `user.name`
--

linux_anomalous_network_service::
Looks for unusual listening ports that could indicate execution of unauthorized 
services, backdoors, or persistence mechanisms.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat 

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

linux_anomalous_network_url_activity_ecs::
Looks for an unusual web URL request from a Linux instance. Curl and wget web 
request activity is very common but unusual web requests from a Linux server can 
sometimes be malware delivery or execution.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat 

Influencers:

* `destination.ip`
* `destination.port` 
* `host.name`
--

linux_anomalous_process_all_hosts_ecs::
windows_anomalous_process_all_hosts_ecs::
Looks for processes that are unusual to all Linux/Windows hosts. Such unusual 
processes may indicate unauthorized services, malware, or persistence 
mechanisms.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat (Linux)
* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

linux_anomalous_user_name_ecs::
windows_anomalous_user_name_ecs::
Rare and unusual users that are not normally active may indicate unauthorized 
changes or activity by an unauthorized user which may be credentialed access or 
lateral movement.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat (Linux)
* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

packetbeat_dns_tunneling::
Looks for unusual DNS activity that could indicate command-and-control or data 
exfiltration activity.
+
--
Bucket span: 15m.

Function: `high_info_content`.

Beats required on host:

* Packetbeat

Influencers:

* `destination.ip`
* `dns.question.etld_plus_one`
* `host.name`
--

packetbeat_rare_dns_question::
Looks for unusual DNS activity that could indicate command-and-control activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Packetbeat

Influencers:

* `host.name`
--

packetbeat_rare_server_domain::
Looks for unusual HTTP or TLS destination domain activity that could indicate 
execution, persistence, command-and-control or data exfiltration activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Packetbeat

Influencers:

* `destination.ip`
* `host.name`
* `source.ip`
--

packetbeat_rare_urls::
Looks for unusual web browsing URL activity that could indicate execution, 
persistence, command-and-control or data exfiltration activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Packetbeat

Influencers:

* `destination.ip`
* `host.name`
--

packetbeat_rare_user_agent::
Looks for unusual HTTP user agent activity that could indicate execution, 
persistence, command-and-control or data exfiltration activity.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Packetbeat

Influencers:

* `destination.ip`
* `host.name`
--

rare_process_by_host_linux_ecs::
rare_process_by_host_windows_ecs::
Detect unusually rare processes on Linux/Windows.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Auditbeat (Linux) 
* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

suspicious_login_activity_ecs::
Detect unusually high number of authentication attempts.
+
--
Bucket span: 15m.

Function: `high_non_zero_count`.

Beats required on host:

* Auditbeat

Influencers:

* `host.name` 
* `source.ip`
* `user.name`
--

windows_anomalous_path_activity_ecs::
Looks for activity in unusual paths that may indicate execution of malware or 
persistence mechanisms. Windows payloads often execute from user profile paths.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

windows_anomalous_process_creation::
Looks for unusual process relationships which may indicate execution of malware 
or persistence mechanisms.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

windows_anomalous_script::
Looks for unusual powershell scripts that may indicate execution of malware, or 
persistence mechanisms.
+
--
Bucket span: 15m.

Function: `high_info_content`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `user.name`
* `winlog.event_data.Path`
--

windows_anomalous_service::
Looks for rare and unusual Windows services which may indicate execution of 
unauthorized services, malware, or persistence mechanisms.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `winlog.event_data.ServiceName`
--

windows_rare_user_runas_event::
Unusual user context switches can be due to privilege escalation.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--

windows_rare_user_type10_remote_login::
Looks for unusual user rermote logins. Unusual RDP (remote desktop protocol) 
user logins can indicate account takeover or credentialed access.
+
--
Bucket span: 15m.

Function: `rare`.

Beats required on host:

* Winlogbeat (Windows)

Influencers:

* `host.name` 
* `process.name`
* `user.name`
--
