[role="xpack"]
[[ootb-ml-jobs]]
= Supplied {anomaly-detect} configurations
++++
<titleabbrev>Supplied configurations</titleabbrev>
++++

{anomaly-jobs-cap} contain the configuration information and metadata necessary 
to perform an analytics task. {kib} can recognize certain types of data and 
provide specialized wizards for that context. This page lists the categories of 
the {anomaly-jobs} that are ready to use via {kib} in **Machine learning**. 
Refer to <<create-jobs>> to learn more about creating a job by using supplied 
configurations. Logs and Metrics supplied configurations are available and can 
be created via the related solution UI in {kib}.

* <<ootb-ml-jobs-apache>>
* <<ootb-ml-jobs-apm>>
* <<ootb-ml-jobs-auditbeat>>
* <<ootb-ml-jobs-logs-ui>>
* <<ootb-ml-jobs-metricbeat>>
* <<ootb-ml-jobs-metrics-ui>>
* <<ootb-ml-jobs-nginx>>
* <<ootb-ml-jobs-siem>>
* <<ootb-ml-jobs-uptime>>


NOTE: The configurations are only available if data exists that matches the 
queries specified in the manifest files. These recognizer queries are linked in 
the descriptions of the individual configurations.

[discrete]
[[ootb-ml-model-memory]]
== Model memory considerations

By default, these jobs have
{ref}/ml-put-job.html#put-analysislimits[model_memory_limit] values that are
deemed appropriate for typical user environments. If the characteristics of your
data cause these jobs to reach `soft_limit` or
`hard_limit` {ref}/ml-get-job-stats.html#modelsizestats[memory_status] values,
you can clone the job and increase the model memory limit. Before you clone the
job, you might also need to update the
{ref}/ml-settings.html[xpack.ml.max_model_memory_limit] setting.
