[[ootb-ml-jobs]]
= Supplied {anomaly-detect} configurations
++++
<titleabbrev>Supplied configurations</titleabbrev>
++++

{anomaly-jobs-cap} contain the configuration information and metadata necessary 
to perform an analytics task. {kib} can recognize certain types of data and 
provide specialized wizards for that context. This page lists the categories of 
the {anomaly-jobs} that are ready to use via {kib} in **Machine learning**. 
Refer to <<create-jobs>> to learn more about creating a job by using supplied 
configurations. Logs and Metrics supplied configurations are available and can 
be created via the related solution UI in {kib}.

* <<ootb-ml-jobs-apache,Apache>>
* <<ootb-ml-jobs-apm,APM>>
* <<ootb-ml-jobs-auditbeat,{auditbeat}>>
* <<ootb-ml-jobs-logs-ui,Logs>>
* <<ootb-ml-jobs-metricbeat,{metricbeat}>>
* <<ootb-ml-jobs-metrics-ui,Metrics>>
* <<ootb-ml-jobs-nginx,Nginx>>
* <<ootb-ml-jobs-siem,Security>>
* <<ootb-ml-jobs-uptime,Uptime>>


NOTE: The configurations are only available if data exists that matches the 
queries specified in the manifest files. These recognizer queries are linked in 
the descriptions of the individual configurations.

[discrete]
[[ootb-ml-model-memory]]
== Model memory considerations

By default, these jobs have `model_memory_limit` values that are deemed 
appropriate for typical user environments and data characteristics. If your
environment or your data is atypical and your jobs reach a memory status value
of `soft_limit` or `hard_limit`, you might need to update the model memory
limits. For more information, see
<<set-model-memory-limit,Working with {anomaly-detect} at scale>>.
