[[gke-on-prem-introduction]]
== Introduction

{gke}[GKE On-Prem] lets you take advantage of Kubernetes and cloud technology in
your data center. You get the Google Kubernetes Engine (GKE) experience with
quick, managed, simple installs and upgrades validated by Google. Google Cloud
Console gives you a single pane of glass view for managing your clusters across
on-premises and cloud environments.  Integrating the {stack} with GKE On-Prem
enables you to combine the logs and metrics across your traditional systems and
your GKE On-Prem systems to give you greater observability into the services and
applications that you provide to your end users.

Whether you choose to deploy GKE On-Prem for security, compliance, or to benefit
from using the best service regardless of where they run (in your data center of
Google Cloud), you should consider having your logs and metrics indexed, stored,
analyzed, and visualized on premises. The {stack} supports on premises
deployments using the {elasticgetstarted}[downloaded binaries] or using
{ece-url}[{ece}] in your own data center.  

Read on to see how to integrate your logs and metrics from tradional and GKE
On-Prem environments in the {stack}.

[discrete]
[[gke-on-prem-overview]]
=== Assumptions
It is assumed that you have an existing {es} and {kib} deployment in your data
center and that there is network connectivity between your GKE On-Prem systems
and both {es} and {kib}. 