[[gke-on-prem-deploy-beats]]
== Deploy Beats

TIP: If you do not have an {es} cluster with {kib} available, see
 {stack-ref}/installing-elastic-stack.html[Installing the {stack}] and
deploy {es} and {kib}, then come back to this page to deploy Beats.

[discrete]
[[kubernetes-secrets]]
=== Kubernetes secrets

Rather than putting the {es} and {kib} endpoints into the manifest files they
are provided to the {filebeat} pods as k8s secrets. Edit the files
`elasticsearch-hosts-ports` and `kibana-host-port`. The files provided in the
example contain details regarding the file format. You should have two files
resembling:

`elasticsearch-hosts-ports`:
[source,sh]
----
["http://10.1.1.4:9200", "http://10.1.1.5:9200"]
----

`kibana.host.port`:
[source,sh]
----
"http://10.1.1.6:5601"
----

[discrete]
[[kubernetes-create-secret]]
=== Create the secret

[source,sh]
----
kubectl create secret generic elastic-stack \
  --from-file=./elasticsearch-hosts-ports \
  --from-file=./kibana-host-port --namespace=kube-system
----

[discrete]
[[deploy-configuration]]
=== Deploy {data-sources}, visualizations, dashboards, and {ml} jobs

{filebeat} and {metricbeat} provide the configuration for things like web
servers, caches, proxies, operating systems, container environments, databases,
etc. These are referred to as Beats modules. By deploying these configurations
you will be populating {es} and {kib} with {data-sources}, visualizations,
dashboards, {ml} jobs, etc.

[source,sh]
----
kubectl create -f filebeat-setup.yaml
kubectl create -f metricbeat-setup.yaml
----

NOTE: These setup jobs are short lived, you will see them transition to the
completed state in the output of `kubectl get pods -n kube-system`

[discrete]
[[verify-pods]]
=== Verify

[source,sh]
----
kubectl get pods -n kube-system | grep beat
----

Verify that the setup pods complete. Check the logs for the setup pods to ensure
that they connected to {es} and {kib} (the setup pod connects to both).

[discrete]
[[deploy-daemonsets]]
=== Deploy the Beat DaemonSets

[source,sh]
----
kubectl create -f filebeat-kubernetes.yaml
kubectl create -f metricbeat-kubernetes.yaml
----

[discrete]
[[verify-beats]]
=== Verify

Check for the running DaemonSets.
Verify that there is one {filebeat} and {metricbeat} pod per k8s Node running.

[source,sh]
----
kubectl get pods -n kube-system | grep beat
----

