include::{asciidoc-dir}/../../shared/versions.asciidoc[]
include::{asciidoc-dir}/../../shared/attributes.asciidoc[]

:gke: https://cloud.google.com/gke-on-prem/
:elasticgetstarted: {stack-gs}/get-started-elastic-stack.html
:gettingstartedwithelasticstack: {elasticgetstarted}
:ece: https://www.elastic.co/products/ece
:daemonsetdocs: https://cloud.google.com/kubernetes-engine/docs/concepts/daemonset
:beatsdocs: https://www.elastic.co/products/beats
:filebeatmodules: {filebeat-ref}/filebeat-modules.html
:filebeatautodiscoverdocs: {filebeat-ref}/configuration-autodiscover.html
:metricbeatmodules: {metricbeat-ref}/metricbeat-modules.html
:metricbeatautodiscoverdocs: {metricbeat-ref}/configuration-autodiscover.html
:filebeat-getting-started-view-the-sample-dashboards: {filebeat-ref}/view-kibana-dashboards.html#view-kibana-dashboards
:kube-state-metrics: https://github.com/kubernetes/kube-state-metrics
:k8s-rbac: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
:guestbook-app: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
:k8s-metadata-labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

[[gke-on-prem]]
= Combining logs and metrics from Google Cloud's Anthos GKE On-Prem with traditional on premises systems in the Elastic Stack

[[gke-on-prem-introduction]]
== Introduction

{gke}[GKE On-Prem] lets you take advantage of Kubernetes and cloud technology in your data center. You get the Google Kubernetes Engine (GKE) experience with quick, managed, simple installs and upgrades validated by Google. Google Cloud Console gives you a single pane of glass view for managing your clusters across on-premises and cloud environments.  Integrating the Elastic Stack with GKE On-Prem enables you to combine the logs and metrics across your traditional systems and your GKE On-Prem systems to give you greater observability into the services and applications that you provide to your end users.
Introduction
Whether you choose to deploy GKE On-Prem for security, compliance, or to benefit from using the best service regardless of where they run (in your data center of Google Cloud), you should consider having your logs and metrics indexed, stored, analyzed, and visualized on premises.  The Elastic Stack supports on premises deployments using the {elasticgetstarted}[downloaded binaries] or using {ece}[Elastic Cloud Enterprise] in your own data center.  

Read on to see how to integrate your logs and metrics from tradional and GKE On-Prem environments in the Elastic Stack.

include::gke-on-prem-architecture.asciidoc[]

include::gke-on-prem-deploy.asciidoc[]

include::gke-on-prem-view.asciidoc[]
