[[how-monitoring-works]]
== How Monitoring Works

Monitoring collects data from {es} nodes, Logstash nodes, and {kib} instances.
The {es} cluster you are monitoring controls where the monitoring metrics for
the entire stack are stored. By default, they are stored in local indices. In
production, we strongly recommend using a separate monitoring cluster. Using a
separate monitoring cluster prevents production cluster outages from impacting
your ability to access your monitoring data. It also prevents monitoring
activities from impacting the performance of your production cluster.

IMPORTANT: In general, the monitoring cluster and the clusters being monitored
should be running the same version of the stack. A monitoring cluster cannot
monitor production clusters running newer versions of the stack. If necessary,
the monitoring cluster can monitor production clusters running older versions,
but the versions cannot differ by more than one major version.

// If you are monitoring pre-5.5 clusters with a version 5.5 or greater monitoring cluster,
// see Monitoring across versions for more information.

The following diagram illustrates a typical monitoring architecture:

////

TODO: Add an image of the architecture
                      (write)
[ Monitoring Cluster ] <-- [ Production Cluster ]
          |                 ^        ^
          |(read)          /(write)  |(write)
          \/              /          |
[       Kibana             ] [ Logstash ]

////

If you have at least a Gold license, you can route data from multiple production
clusters to a single monitoring cluster:

// TODO: Add an image of the architecture

// The default Trial license is equivalent to a Platinum license, which also
//allows you to test this functionality.

If {kib} is a regular part of your stack, you might want to stand up a dedicated
{kib} instance for monitoring, rather than using a single {kib} instance to
access both your production cluster and monitoring cluster:

// TODO: Add an image of the architecture

// ===	Collecting Monitoring Metrics
// === Exporting Monitoring Metrics
// === Accessing and Visualizing Monitoring Data
// ==== Monitoring Across Versions
