[[xpack-monitoring]]
= Monitoring the Elastic Stack

[partintro]
--

{monitoring} gives you insight into the operation of {es}, Logstash, and {kib}.
All of the monitoring metrics are stored in {es}, which enables you to easily
visualize the data from {kib}. From the {kib} Monitoring UI, you can spot issues
at a glance and delve into the system behavior over time to diagnose operational
issues. In addition to the built-in status warnings, you can set up custom alerts
based on the data in the monitoring indices.
////
High-level overview of monitoring: Describe the architecture and concepts--data
collection, storage, and visualization. Explain how data flows through the
system and how the different components communicate. Show the basic out-of-the-box
monitoring architecture and the recommended production monitoring architecture.
Cross-ref monitoring topics for each product.
////
--

include::how-monitoring-works.asciidoc[]
include::{xkb-repo-dir}/monitoring/getting-started.asciidoc[]
include::production.asciidoc[]
include::{xkb-repo-dir}/monitoring/monitoring-details.asciidoc[]
include::{xkb-repo-dir}/monitoring/monitoring-elasticsearch.asciidoc[]
include::{xkb-repo-dir}/monitoring/monitoring-logstash.asciidoc[]
include::{xkb-repo-dir}/monitoring/monitoring-kibana.asciidoc[]
include::{xkb-repo-dir}/monitoring/configuring-monitoring.asciidoc[]
