[[xpack-monitoring]]
= Monitoring the Elastic Stack

[partintro]
--

{monitoring} gives you insight into the operation of {es}, Logstash, and {kib}.
All of the monitoring metrics are stored in {es}, which enables you to easily
visualize the data from {kib}. From the {kib} Monitoring UI, you can spot issues
at a glance and delve into the system behavior over time to diagnose operational
issues. In addition to the built-in status warnings, you can set up custom alerts
based on the data in the monitoring indices.
////
OLD:
The {monitoring} components enable you to easily monitor the Elastic Stack
from {kibana-ref}/introduction.html[Kibana].
You can view health and performance data for {es}, Logstash, and
{kib} in real time, as well as analyze past performance.

When you install {xpack}, a monitoring agent runs on each {kib},
{kib}, and Logstash instance to collect and index metrics.

By default, metrics are indexed within the cluster you are monitoring.
Setting up a <<monitoring-cluster, dedicated monitoring cluster>> ensures
you can access historical monitoring data even if the cluster you're
monitoring goes down. It also enables you to monitor multiple clusters
from a central location.

When you use a dedicated monitoring cluster, the metrics collected by the
Logstash and {kib} monitoring agents are shipped to the {es}
cluster you're monitoring, which then forwards all of the metrics to
the monitoring cluster.
////
--
