[[getting-started]]
= Get started with {ml}

[partintro]
--
Ready to take {ml} for a test drive? Follow this getting started tutorial to:

* Create single, multi-metric, and population {anomaly-jobs} for the {kib} sample data
* Use the results to identify possible anomalies in the data

At the end of this tutorial, you should have a good idea of what {ml} is and
will hopefully be inspired to use it to detect anomalies in your own data.

Need more context?

Check out the {ref}/elasticsearch-intro.html[{es} introduction] to learn the
lingo and understand the basics of how {es} works. If you're already familiar
with {es} and want to see how it works with the rest of the stack, you might
want to jump to the {stack-gs}/get-started-elastic-stack.html[{stack} tutorial]
to see how to set up a system monitoring solution with {es}, {kib},
{beats}, and {ls}.

--

include::getting-started-enable-ml.asciidoc[]

include::getting-started-data.asciidoc[]

include::getting-started-wizards.asciidoc[]

include::getting-started-single.asciidoc[]

////
include::getting-started-multi.asciidoc[]

include::getting-started-forecast.asciidoc[]

include::getting-started-next.asciidoc[]
////
