[[ml-getting-started]]
= Getting started with {anomaly-detect}
++++
<titleabbrev>Tutorial: Getting started with {anomaly-detect}</titleabbrev>
++++

:frontmatter-description: This tutorial shows you how to create {anomaly-jobs}, interpret the results, and forecast future behavior in {kib}.
:frontmatter-tags-products: [ml] 
:frontmatter-tags-content-type: [tutorial] 
:frontmatter-tags-user-goals: [get-started]

Ready to take {anomaly-detect} for a test drive? Follow this tutorial to:

* Try out the **{data-viz}**
* Create {anomaly-jobs} for the {kib} sample data
* Use the results to identify possible anomalies in the data

At the end of this tutorial, you should have a good idea of what {ml} is and
will hopefully be inspired to use it to detect anomalies in your own data.

Need more context? Check out the
{ref}/elasticsearch-intro.html[{es} introduction] to learn the lingo and
understand the basics of how {es} works.


[discrete]
[[get-started-prereqs]]
== Try it out

. Before you can play with the {ml-features}, you must install {es} and {kib}.
{es} stores the data and the analysis results. {kib} provides a helpful user 
interface for creating and viewing jobs.
+
--
[TIP]
==========
You can run {es} and {kib} on your own hardware, or use our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}] on {ecloud}.
The {ess} is available on both AWS and GCP.
https://www.elastic.co/cloud/elasticsearch-service/signup[Try out the {ess} for free].
==========
--

. Verify that your environment is set up properly to use the {ml-features}. If
the {es} {security-features} are enabled, to complete this tutorial you need a
user that has authority to manage {anomaly-jobs}. See <<setup>>.

. {kibana-ref}/get-started.html#gs-get-data-into-kibana[Add the sample data sets that ship with {kib}]. 

.. From the {kib} home page, click *Try sample data*, then open the 
*Other sample data sets* section.

.. Pick a data set. In this tutorial, you'll use the *Sample web logs*. While
you're here, feel free to click *Add data* on all of the available sample data 
sets.

These data sets are now ready be analyzed in {ml} jobs in {kib}.
