[[anomalous-windows-process-creation]]
=== Anomalous Windows Process Creation

Identifies unusual parent-child process relationships that can indicate malware
execution or persistence mechanisms. Malicious scripts often call on other
applications and processes as part of their exploit payload. For example, when a
malicious Office document runs scripts as part of an exploit payload, Excel or
Word may start a script interpreter process, which, in turn, runs a script that
downloads and executes malware. Another common scenario is Outlook running an
unusual process when malware is downloaded in an email. Monitoring and
identifying anomalous process relationships is a method of detecting new and
emerging malware that is not yet recognized by anti-virus scanners.

*Rule type*: machine_learning

*Machine learning job*: windows_anomalous_process_creation

*Machine learning anomaly threshold*: 50


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* ML
* Windows

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

Users running scripts in the course of technical support operations of software
upgrades could trigger this signal. A newly installed program or one that runs
rarely as part of a monthly or quarterly workflow could trigger this signal.
