[[ftp-file-transfer-protocol-activity-to-the-internet]]
=== FTP (File Transfer Protocol) Activity to the Internet

Detects events that may indicate the use of FTP network connections to
the Internet. The File Transfer Protocol (FTP) has been around in its current
form since the 1980s. It can be a common and efficient procedure on your network
to send and receive files. Because of this, adversaries will also often use this
protocol to exfiltrate data from your network or download new tools.
Additionally, FTP is a plain-text protocol which, if intercepted, may expose
usernames and passwords. FTP activity involving servers subject to regulations
or compliance standards may be unauthorized.

*Rule indices*:

* filebeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 2 (<<ftp-file-transfer-protocol-activity-to-the-internet-history, version history>>)

==== Potential false positives

FTP servers should be excluded from this rule as this is expected behavior. Some
business workflows may use FTP for data exchange. These workflows often have
expected characteristics such as users, sources, and destinations. FTP activity
involving an unusual source or destination may be more suspicious. FTP activity
involving a production server that has no known associated FTP workflow or
business requirement is often suspicious.

==== Rule query


[source,js]
----------------------------------
network.transport: tcp and destination.port: (20 or 21) and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip:
(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/


* Tactic:
** Name: Exfiltration
** ID: TA0010
** Reference URL: https://attack.mitre.org/tactics/TA0010/
* Technique:
** Name: Exfiltration Over Alternative Protocol
** ID: T1048
** Reference URL: https://attack.mitre.org/techniques/T1048/
