[[netcat-network-activity]]
=== Netcat Network Activity

A `netcat` process is engaging in network activity on a Linux host. Netcat is
often used as a persistence mechanism by exporting a reverse shell or by serving
a shell on a listening port. Netcat is also sometimes used for data
exfiltration.

*Rule type*: query

*Rule indices*:

* auditbeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet
* https://www.sans.org/security-resources/sec560/netcat_cheat_sheet_v1.pdf
* https://en.wikipedia.org/wiki/Netcat

*Tags*:

* Elastic
* Linux

*Version*: 2 (<<netcat-network-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Netcat is a dual-use tool that can be used for benign or malicious activity.
Netcat is included in some Linux distributions so its presence is not
necessarily suspicious. Some normal use of this program, while uncommon, may
originate from scripts, automation tools, and frameworks.

==== Rule query


[source,js]
----------------------------------
process.name:(nc or ncat or netcat or netcat.openbsd or
netcat.traditional) and event.action:(bound-socket or connected-to or
socket_opened)
----------------------------------


===== Query changelog

*Version 1 query*

[source]
----------------------------------
process.name: (nc or ncat or netcat or netcat.openbsd or
netcat.traditional) and event.action: (connected-to or bound-socket or
socket_opened)
----------------------------------

