[[network-connection-via-signed-binary]]
=== Network Connection via Signed Binary

Binaries signed with trusted digital certificates can execute on Windows systems
protected by digital signature validation. Adversaries may use these binaries to
'live off the land' and execute malicious files that could bypass application
whitelisting and signature validation.

*Rule type*: query

*Rule indices*:

* winlogbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Windows

*Version*: 2 (<<network-connection-via-signed-binary-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Rule query


[source,js]
----------------------------------
process.name:(expand.exe or extrac.exe or ieexec.exe or makecab.exe)
and event.action:"Network connection detected (rule: NetworkConnect)"
and not destination.ip:(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Signed Binary Proxy Execution
** ID: T1218
** Reference URL: https://attack.mitre.org/techniques/T1218/


* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Signed Binary Proxy Execution
** ID: T1218
** Reference URL: https://attack.mitre.org/techniques/T1218/

[[network-connection-via-signed-binary-history]]
==== Rule version history

Version 2 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
(process.name:expand.exe or process.name:extrac.exe or
process.name:ieexec.exe or process.name:makecab.exe) and
event.action:"Network connection detected (rule: NetworkConnect)" and
not destination.ip:10.0.0.0/8 and not destination.ip:172.16.0.0/12 and
not destination.ip:192.168.0.0/16
----------------------------------

