[[network-connection-via-regsvr]]
=== Network Connection via Regsvr

Identifies the native Windows tools `regsvr32.exe` and `regsvr64.exe` making a
network connection. This may be indicative of an attacker bypassing whitelisting
or running arbitrary scripts via a signed Microsoft binary.

*Rule type*: query

*Rule indices*:

* winlogbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Windows

*Version*: 2 (<<network-connection-via-regsvr-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Security testing may produce events like this. Activity of this kind performed
by non-engineers and ordinary users is unusual.

==== Rule query


[source,js]
----------------------------------
process.name:(regsvr32.exe or regsvr64.exe) and event.action:"Network
connection detected (rule: NetworkConnect)" and not
destination.ip:(10.0.0.0/8 or 169.254.169.254 or 172.16.0.0/12 or
192.168.0.0/16)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Regsvr32
** ID: T1117
** Reference URL: https://attack.mitre.org/techniques/T1117/


* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Regsvr32
** ID: T1117
** Reference URL: https://attack.mitre.org/techniques/T1117/

[[network-connection-via-regsvr-history]]
==== Rule version history

Version 2 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
(process.name:regsvr32.exe or process.name:regsvr64.exe) and
event.action:"Network connection detected (rule: NetworkConnect)" and
not destination.ip:169.254.169.254/32 and not
destination.ip:10.0.0.0/8 and not destination.ip:172.16.0.0/12 and not
destination.ip:192.168.0.0/16
----------------------------------

