[[nmap-process-activity]]
=== Nmap Process Activity

Nmap was executed on a Linux host. Nmap is a FOSS tool for network scanning  and
security testing. It can map and discover networks, and identify listening
services and operating systems. It is sometimes used to gather information in
support of exploitation, execution or lateral movement.

*Rule indices*:

* auditbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://en.wikipedia.org/wiki/Nmap

*Tags*:

* Elastic
* Linux

*Rule version*: 1

*Added ({stack} release)*: 7.6.0

==== Potential false positives

Security testing tools and frameworks may run `Nmap` in the course of security
auditing. Some normal use of this command may originate from security engineers
and network or server administrators. Use of nmap by ordinary users is uncommon.

==== Rule query


[source,js]
----------------------------------
process.name: nmap
----------------------------------

