[[proxy-port-activity-to-the-internet]]
=== Proxy Port Activity to the Internet

Detects events that may describe network events of proxy use to the
Internet. It includes popular HTTP proxy ports and SOCKS proxy ports. Typically,
environments will use an internal IP address for a proxy server. It can also be
used to circumvent network controls and detection mechanisms.

*Rule indices*:

* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 2

==== Potential false positives

Some proxied applications may use these ports but this usually occurs in local
traffic using private IPs which this rule does not match. Proxies are widely
used as a security technology but in enterprise environments this is usually
local traffic which this rule does not match. Internet proxy services using
these ports can be white-listed if desired. Some screen recording
applications may use these ports.

Proxy port activity involving an unusual source or destination may be more 
suspicious. Some cloud environments may use this port when VPNs or direct 
connects are not in use and cloud instances are accessed across the Internet. 
Because these ports are in the ephemeral range, this rule may false under 
certain conditions such as when a NATed web server replies to a client which 
has used a port in the range by coincidence. In this case, such servers can be 
excluded.

==== Rule query


[source,js]
----------------------------------
network.transport: tcp and destination.port: (3128 or 8080 or 1080)
and ( network.direction: outbound or ( source.ip:
(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and not
destination.ip: (10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) )
)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/
