[[rdp-remote-desktop-protocol-to-the-internet]]
=== RDP (Remote Desktop Protocol) to the Internet

Detects network events that may indicate the use of RDP traffic to the Internet.
RDP is commonly used by system administrators to remotely control a system for
maintenance or to use shared resources. It should almost never be directly
exposed to the Internet, as it is frequently targeted and exploited by threat
actors as an initial access or back-door vector.

*Rule type*: query

*Rule indices*:

* filebeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 3 (<<rdp-remote-desktop-protocol-to-the-internet-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

RDP connections may be made directly to Internet destinations in order to access
Windows cloud server instances but such connections are usually made only by
engineers. In such cases, only RDP gateways, bastions or jump servers may be
expected Internet destinations and can be exempted from this rule. RDP may be
required by some workflows such as remote access and support for specialized
software products and servers. Such workflows are usually known and not
unexpected. Usage that is unfamiliar to server or network owners can be
unexpected and suspicious.

==== Rule query


[source,js]
----------------------------------
network.transport:tcp and destination.port:3389 and
source.ip:(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and not
destination.ip:(10.0.0.0/8 or 127.0.0.0/8 or 172.16.0.0/12 or
192.168.0.0/16 or "::1")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Initial Access
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Exploit Public-Facing Application
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/


* Tactic:
** Name: Exfiltration
** ID: TA0010
** Reference URL: https://attack.mitre.org/tactics/TA0010/
* Technique:
** Name: Exfiltration Over Alternative Protocol
** ID: T1048
** Reference URL: https://attack.mitre.org/techniques/T1048/

[[rdp-remote-desktop-protocol-to-the-internet-history]]
==== Rule version history

Version 3 (7.7.0 release)::
Updated query, changed from:
+
[source, js]
----------------------------------
network.transport: tcp and destination.port: 3389 and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip: (10.0.0.0/8
or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

Version 2 (7.6.1 release)::
* Removed auditbeat-\*, packetbeat-*, and winlogbeat-* from the rule indices.
