[[ssh-secure-shell-to-the-internet]]
=== SSH (Secure Shell) to the Internet

Detects network events that may indicate the use of SSH traffic to
the Internet. SSH is commonly used by system administrators to remotely control
a system using the command line shell. If it is exposed to the Internet, it
should be done with strong security controls as it is frequently targeted and
exploited by threat actors as an initial access or back-door vector.

*Rule indices*:

* auditbeat-*
* filebeat-*
* packetbeat-*
* winlogbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 1

==== Potential false positives

SSH connections may be made directly to Internet destinations in order to access
Linux cloud server instances but such connections are usually made only by
engineers. In such cases, only SSH gateways, bastions or jump servers may be
expected Internet destinations and can be exempted from this rule. SSH may
be required by some workflows such as remote access and support for
specialized software products and servers. Such workflows are usually known and
not unexpected. Usage that is unfamiliar to server or network owners can be
unexpected and suspicious.

==== Rule query


[source,js]
----------------------------------
network.transport: tcp and destination.port:22 and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip:
(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/
