[[tcp-port-8000-activity-to-the-internet]]
=== TCP Port 8000 Activity to the Internet

TCP Port 8000 is commonly used for development environments of web server
software. It generally should not be exposed directly to the Internet. If you
are running software like this on the Internet, you should consider placing it
behind a reverse proxy.

*Rule indices*:

* filebeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Version*: 2

==== Potential false positives

Because this port is in the ephemeral range, this rule may false under certain
conditions, such as when a NATed web server replies to a client which has used a
port in the range by coincidence. In this case, such servers can be excluded.
Some applications may use this port but this is very uncommon and usually
appears in local traffic using private IPs, which this rule does not match. Some
cloud environments, particularly development environments, may use this port
when VPNs or direct connects are not in use and cloud instances are accessed
across the Internet.

==== Rule query


[source,js]
----------------------------------
network.transport: tcp and destination.port: 8000 and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip:
(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/
