[[tor-activity-to-the-internet]]
=== Tor Activity to the Internet

Detects network events that may indicate the use of Tor traffic to the
Internet. Tor is a network protocol that sends traffic through a series of
encrypted tunnels used to conceal a user's location and usage. Tor may be used
by threat actors as an alternate communication pathway to conceal the actor's
identity and avoid detection.

*Rule indices*:

* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*Tags*:

* Elastic
* Network

*Rule version*: 2 (<<tor-activity-to-the-internet-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.6.1

==== Potential false positives

Tor client activity is uncommon in managed enterprise networks but may be common
in unmanaged or public networks where few security policies apply. Because these
ports are in the ephemeral range, this rule may false under certain
conditions such as when a NATed web server replies to a client which has
used one of these ports by coincidence. In this case, such servers can be excluded if desired.

==== Rule query


[source,js]
----------------------------------
network.transport: tcp and destination.port: (9001 or 9030) and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip:
(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Commonly Used Port
** ID: T1043
** Reference URL: https://attack.mitre.org/techniques/T1043/


* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Multi-hop Proxy
** ID: T1188
** Reference URL: https://attack.mitre.org/techniques/T1188/
