[[unusual-windows-user-privilege-elevation-activity]]
=== Unusual Windows User Privilege Elevation Activity

A machine learning job detected an unusual user context switch, using the
`runas` command or similar techniques, which can indicate account takeover or
privilege escalation using compromised accounts. Privilege elevation using
tools like `runas` are more commonly used by domain and network administrators
than by regular Windows users.

*Rule type*: machine_learning

*Machine learning job*: windows_rare_user_runas_event


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* ML
* Windows

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

Uncommon user privilege elevation activity can be due to an administrator, help
desk technician, or a user performing manual troubleshooting or reconfiguration.
