[[unusual-linux-network-activity]]
=== Unusual Linux Network Activity

Identifies Linux processes that do not usually use the network but have
unexpected network activity, which can indicate command-and-control, lateral
movement, persistence, or data exfiltration activity. A process with unusual
network activity can denote process exploitation or injection, where the process
is used to run persistence mechanisms that allow a malicious actor remote access
or control of the host, data exfiltration, and execution of unauthorized network
applications.

*Rule type*: machine_learning

*Machine learning job*: linux_anomalous_network_activity_ecs


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* Linux
* ML

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

A newly installed program or one that rarely uses the network could trigger this
signal.

==== Investigation guide

Signals from this rule indicate
the presence of network activity from a Linux process for which network activity
is rare and unusual.  Here are some possible avenues of investigation: -
Consider the IP addresses and ports. Are these used by normal but infrequent
network workflows? Are they expected or unexpected?  - If the destination IP
address is remote or external, does it associate with an expected domain,
organization or geography? Note: avoid interacting directly with suspected
malicious IP addresses. - Consider the user as identified by the username field.
Is this network activity part of an expected workflow for the user who ran the
program? - Examine the history of execution. If this process manifested only
very recently, it might be part of a new software package. If it has a
consistent cadence - for example if it runs monthly or quarterly - it might be
part of a monthly or quarterly business or maintenance process. - Examine the
process arguments, title and working directory. These may provide indications as
to the source of the program or the nature of the tasks it is performing.
