[[unusual-web-user-agent]]
=== Unusual Web User Agent

A machine learning job detected a rare and unusual user agent indicating web
browsing activity by an unusual process other than a web browser. This can be
due to persistence, command-and-control, or exfiltration activity. Uncommon user
agents coming from remote sources to local destinations are often the result of
scanners, bots, and web scrapers, which are part of common Internet background
traffic. Much of this is noise, but more targeted attacks on websites using
tools like Burp or SQLmap can sometimes be discovered by spotting uncommon user
agents. Uncommon user agents in traffic from local sources to remote
destinations can be any number of things, including harmless programs like
weather monitoring or stock-trading programs. However, uncommon user agents from
local sources can also be due to malware or scanning activity.

*Rule type*: machine_learning

*Machine learning job*: packetbeat_rare_user_agent


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* ML
* Packetbeat

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

Web activity that is uncommon, like security scans, may trigger a signal and
may need to be excluded. A new or rarely used program that calls web services
may trigger a signal.
