[[unusual-windows-path-activity]]
=== Unusual Windows Path Activity

Identifies processes started from atypical folders in the file system, which
may indicate malware execution or persistence mechanisms. In corporate Windows
environments, software installation is centrally managed and it is unusual for
programs to be executed from user or temporary directories. Processes executed
from these locations can denote that a user downloaded software directly from
the Internet or a malicious script or macro executed malware.

*Rule type*: machine_learning

*Machine learning job*: windows_anomalous_path_activity_ecs


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* ML
* Windows

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

A new and unusual program or artifact download in the course of software
upgrades, debugging, or troubleshooting could trigger this signal. Users
downloading and running programs from unusual locations, such as temporary
directories, browser caches, or profile paths could trigger this signal.
