[[unusual-linux-username]]
=== Unusual Linux Username

A machine learning job detected activity for a username that is not normally
active, which can indicate unauthorized changes, activity by unauthorized users,
lateral movement, or compromised credentials. In many organizations, new
usernames are not often created apart from specific types of system activities,
such as creating new accounts for new employees. These user accounts quickly
become active and routine. Events from rarely used usernames can point to
suspicious activity. Additionally, automated Linux fleets tend to see activity
from rarely used usernames only when personnel log in to make authorized or
unauthorized changes, or threat actors have acquired credentials and log in for
malicious purposes. Unusual usernames can also indicate pivoting, where
compromised credentials are used to try and move laterally from one host to
another.

*Rule type*: machine_learning

*Machine learning job*: linux_anomalous_user_name_ecs

*Machine learning anomaly threshold*: 50


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://www.elastic.co/guide/en/siem/guide/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* Linux
* ML

*Version*: 1

*Added ({stack} release)*: 7.7.0


==== Potential false positives

Uncommon user activity can be due to an engineer logging in to a server instance
in order to perform manual troubleshooting or reconfiguration.

==== Investigation guide

Signals from this rule indicate activity for a Linux user name that is rare and
unusual. Here are some possible avenues of investigation:

* Consider the user as identified by the username field. Is this program part
of an expected workflow for the user who ran this program on this host? Could
this be related to troubleshooting or debugging activity by a developer or site
reliability engineer?
* Examine the history of user activity. If this user manifested only very
recently, it might be a service account for a new software package. If it has a
consistent schedule - for example if it runs monthly or quarterly - it might be
part of a monthly or quarterly business process.
* Examine the process arguments, title and working directory. These may provide
indications as to the source of the program or the nature of the tasks that the
user is performing.
