[[web-application-suspicious-activity-sqlmap-user-agent]]
=== Web Application Suspicious Activity: sqlmap User Agent

This is an example of how to detect an unwanted web client user agent. This
search matches the user agent for `sqlmap 1.3.11`, which is a popular FOSS tool
for testing web applications for SQL injection vulnerabilities.

*Rule indices*:

* apm-*-transaction*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format])

*Maximum signals per execution*: 100

*References*:

* http://sqlmap.org/

*Tags*:

* Elastic
* APM

*Version*: 1

==== Potential false positives

This rule does not indicate that a SQL injection attack occurred, only that the
`sqlmap` tool was used. Security scans and tests may result in these errors. If
the source is not an authorized security tester, this is generally suspicious or
malicious activity.

==== Rule query


[source,js]
----------------------------------
user_agent.original:"sqlmap/1.3.11#stable (http://sqlmap.org)"
----------------------------------

