[[web-application-suspicious-activity-no-user-agent]]
=== Web Application Suspicious Activity: No User Agent

A request to a web application server contained no identifying user agent
string.

*Rule type*: query

*Rule indices*:

* apm-*-transaction*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum signals per execution*: 100

*References*:

* https://en.wikipedia.org/wiki/User_agent

*Tags*:

* APM
* Elastic

*Version*: 2 (<<web-application-suspicious-activity-no-user-agent-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.7.0


==== Potential false positives

Some normal applications and scripts may contain no user agent. Most legitimate
web requests from the Internet contain a user agent string. Requests from web
browsers almost always contain a user agent string. If the source is unexpected,
the user unauthorized, or the request unusual, these may indicate suspicious or
malicious activity.

==== Rule query


[source,js]
----------------------------------
url.path:*
----------------------------------


===== Query changelog

*Version 1 query*

[source]
----------------------------------
url.path: *
----------------------------------

==== Rule filters

[source,js]
----------------------------------
{
    "$state": {
        "store": "appState"
    },
    "exists": {
        "field": "user_agent.original"
    },
    "meta": {
        "disabled": false,
        "indexRefName": "kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index",
        "key": "user_agent.original",
        "negate": true,
        "type": "exists",
        "value": "exists"
    }
}
----------------------------------

