[[ingest-management-limitations]]
= Limitations of this release

This is an experimental release and there is no migration path for future
releases, so **YOU MUST TEST IN A DEDICATED CLUSTER.** In a future release, we
plan to add support for a new way of managing rolling indices that will make the
experience easier for users. However, any data stored in this release will not
be migrated in our next release, and you must wipe any data and settings changed
in {kib} and {es} to avoid future conflicts. We recommend using a dedicated test
cluster or deployment that can be deleted when you are done.

{ingest-manager} is currently only available to users with the
{es-ref}/built-in-roles.html[superuser role]. This role is necessary to create
indices, install integration assets, and update {agent} configurations. In order
to use {fleet}, the {agent}s must have a direct network connection to {kib} and
{es}. It is also possible to run the {agent}s in standalone mode in cases where
a network connection is not available or not needed.

This feature has several additional limitations at the current time:

*   Support for only 9 integrations (more coming soon)
*   Support for only {filebeat} and {metricbeat}
*   We recommend you enroll no more than 100 Agents
*   No output to {ls}, Kafka, or other remote clusters
*   No proxy support in {agent}
*   {kib} must have internet access to download integration packages
*   No support for advanced {beats} settings like multiline, processors, and so
on
*   No custom index templates or pipelines
*   No support for Kubernetes or Docker autodiscovery

Experimental releases are not officially supported, but we encourage you to
report issues in our [discuss forum](https://ela.st/agent-discuss).
