[[ingest-management-troubleshooting]]
[role="xpack"]
= Troubleshooting

experimental[]

include::getting-started.asciidoc[tag=experimental-warning]

We have collected the most common known problems and frequently asked questions
here. If your question isn't answered here, please review open issues in the
following GitHub repositories:

* https://github.com/elastic/kibana/issues[{kib}]
* https://github.com/elastic/beats/issues[{beats}]
* https://github.com/elastic/package-registry/issues[{package-registry}]

Contact us in the https://ela.st/ingest-manager-feedback[discuss forum]. Your feedback is very
valuable to us.


**Common problems:**

* <<ingest-manager-not-in-kibana>>
* <<ingest-management-setup-fails>>
* <<ingest-manager-app-crashes>>
* <<agent-enrollment-timeout>>

**Frequently asked questions:**

* <<enrolled-agent-not-showing-up>>
* <<where-are-the-agent-logs>>
* <<what-is-my-agent-config>>
* <<where-is-the-data-agent-is-sending>>
* <<i-deleted-my-agent>>
* <<i-need-to-stop-agent>>
* <<i-rebooted-my-host>>
* <<what-is-the-endpoint-package>>

[float]
[[ingest-manager-not-in-kibana]]
== The {ingest-manager} app is not listed in the {kib} side navigation

In 7.8, the {ingest-manager} app is experimental. You must enable the app to
see it in {kib}.

//TODO: Add platform tabs when the tabbed panel widget is stable (possibly after
// 7.8)

**To enable {ingest-manager} on cloud:**

. Go to your deployment in the user console.

. Under the deployment name in the side navigation, click **Edit**.

. In the {kib} section, expand **User setting overrides** and enter the
following setting:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
----

. Click **Save**.

{kib} will restart automatically. When {kib} is available, refresh the browser
to see the {ingest-manager} app in the navigation menu.

**To enable {ingest-manager} on a self-managed cluster:**

. In the {es} configuration file, `config/elasticsearch.yml`, set the following
security settings to enable security and API keys:
+
[source,yaml]
----
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
----

. In the {kib} configuration file, `config/kibana.yml`, enable {ingest-manager}
and specify user credentials:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
xpack.ingestManager.fleet.tlsCheckDisabled: true <1>
xpack.security.enabled: true
elasticsearch.username: "elastic" <2>
elasticsearch.password: "abc123iUnbRftkABC123"
----
<1> This setting is not required if you configure TLS checking.
<2> Specify a user who is authorized to use {ingest-manager}.

[TIP]
=====
To set up passwords, you can use the documented {es} APIs or the
`elasticsearch-setup-passwords` command. For example:

`./bin/elasticsearch-setup-passwords auto`
=====

After running the command, copy the Elastic user name to the {kib} config file.
Then restart {kib}.

[float]
[[ingest-management-setup-fails]]
== The `/api/ingest_management/setup` endpoint returns an error because it can't reach the package registry

In order to install {integrations}, the {ingest-manager} app needs to connect to
an external service called the {package-registry}. For this to work, the {kib}
server must be able to connect to `https://epr-experimental.elastic.co` on port
443.

[float]
[[ingest-manager-app-crashes]]
== The {ingest-manager} app in {kib} crashes

To find more about the error, open your browser's development console, navigate
to the **Network** tab, and refresh the page. One of the requests to the
{ingest-manager} API will most likely have returned an error. If the error
message doesn't give you enough information to fix the problem, please contact
us https://ela.st/ingest-manager-feedback[here].

[float]
[[agent-enrollment-timeout]]
== {agent} enrollment fails on the host with a `Client.Timeout exceeded` message

{agent} must be able to connect to the {kib} instance to enroll in {fleet}.
If the Agent is unable to connect, you will see the following failure:

[source,output]
-----
fail to enroll: fail to execute request to {kib}:Post http://kibana:5601/api/ingest_manager/fleet/agents/enroll?: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
-----

This may occur if the host is unable to connect to {kib}. To troubleshoot the
problem:

. Check for networking problems. Run the `ping` command from the host to confirm
that it can reach the {kib} instance.

. Verify that the URL and port you specified during enrollment are correct for
your environment.

. Check the enrollment key that you specified during enrollment to confirm that
the key is valid. To do this:
.. In {ingest-manager}, go to the {fleet} tab and click **Enrollment Tokens**. 
.. Click the eyeball icon to see the secret. The secret should match the string
that you used to enroll {agent} on your host.
.. If the secret doesn't match, create a new enrollment token and use the new
token when you run the `elastic-agent enroll` command.

[float]
[[enrolled-agent-not-showing-up]]
== Why doesn't my enrolled agent show up in the {ingest-manager} app?

If {agent} was successfully enrolled, but doesn't show up in the {fleet} list,
it might not be started. You need to start the Agent.

// TODO: This should be single sourced. Update it when we add the tabbed widget
// (probably after 7.8).

On linux and macOS hosts, run:

[source,shell]
----
./elastic-agent run
----

On Windows hosts, run:

[source,shell]
----
elastic-agent.exe run
----

[float]
[[where-are-the-agent-logs]]
== Where does {agent} store logs after startup?

When started successfully, {metricbeat} logs are stored in
`data/logs/metricbeat` under the folder where {agent} was started. If that log
path does not exist, the Agent was unable to start {metricbeat}, which is a
higher level problem to triage.

[float]
[[what-is-my-agent-config]]
== What configuration is the {agent} running?

To find the configuration file, inspect the `elastic-agent.yml` file in the
folder where you ran {agent}. If you're running the Agent in {fleet} mode, this
file contains the following citation:

[source,yaml]
----
Management: mode: "fleet"
----

The `action_store.yml` contains the entire, unencrypted configuration:

* To see the {es} location, look at `outputs:hosts`.
* To see the {agent} version, look at the download folder and zip filenames.

This file also shows the version of all packages used by the current
configuration.

[float]
[[where-is-the-data-agent-is-sending]]
== Why can't I see the data {agent} is sending?

If {elastic-agent} is set up and running, but you don't see data in {kib}:



. Go to **Management > Dev Tools** in {kib}, and in the Console, search your
index for data. For example:
+
[source,console]
----
GET metrics-*/_search
----
+
Or if you prefer, go to the **Discover** app.

. Look at the data that {elastic-agent} has sent and see if the `name.host`
field contains your host machine name.

If you don't see data for your host, it's possible that the data is blocked
in the network, or that a firewall or security problem is preventing the {agent}
from sending the data.

Although it's redundant to install stand-alone {metricbeat}, you might want to
try installing it to see if it's able to send data successfully to {es}. For
more information, see
{metricbeat-ref}/metricbeat-getting-started.html[Get started with {metricbeat}].

If {metricbeat} is able to send data to {es}, there is possibly a bug or
problem with {agent}, and you should report it.

[float]
[[i-deleted-my-agent]]
== How do I restore an {agent} that I deleted from {fleet}?

It's ok, we've got your back! The data is still in {es}. To add {agent}
to {fleet} again, stop the Agent, re-enroll the {agent} on the host, then run
{agent}.

[float]
[[i-need-to-stop-agent]]
== How do I stop {agent} and all processes running on my host?

To stop {agent} and its related executables, stop the {agent} process.

On Windows, if you installed the Agent as a service, stop the service. If
necessary, use Task Manager on Windows to stop {agent}. This will kill the
{agent} process and any sub-processes it created (such as {beats}).

On Linux or macOS, run the following command to get the ID of the
`elastic-agent` process:

[source,shell]
----
ps | grep elastic-agent
----

Then kill the process.



[float]
[[i-rebooted-my-host]]
== How do I restart {agent} after rebooting my host?

On Windows, if you used Powershell to install {agent} as a service, the Agent
should still be running after rebooting the host.

On macOS and Linux, you need to restart {agent} from the command line after
rebooting the host.

Support for installing {agent} as a service on all supported systems will be
available in a future release. To achieve this in the meantime, you can add the
start command to a user's startup profile.

[float]
[[what-is-the-endpoint-package]]
== What is the Endpoint integration shown in {ingest-manager}?

In 7.8, the Endpoint integration is non-functional. It cannot be used yet. It
exists as an artifact of the current feature development. Please watch for
announcements during upcoming release cycles. As a teaser, Endpoint is the
integration that will allow the Elastic Security app to have a dedicated
executable running like {beats} to protect the host and respond to detected
security concerns. Endpoint will be managed by {agent} in the same way that
{beats} are managed.
