[[elastic-stack-breaking-changes]]
== Breaking changes

Before you upgrade, you must review the breaking changes for each product you
use and make the necessary changes so your code is compatible with {version}. 

** <<apm-breaking-changes,APM {version} breaking changes>>
** <<beats-breaking-changes,Beats {version} breaking changes>>
** <<elasticsearch-breaking-changes,{es} {version} breaking changes>>
** <<elasticsearch-hadoop-breaking-changes,{es} Hadoop {version} breaking changes>>
** <<kibana-breaking-changes,Kibana {version} breaking changes>>
** <<logstash-breaking-changes,{ls} {version} breaking changes>>

[IMPORTANT]
===============================

* If you're upgrading from 5.n, make sure you check the breaking changes from
5.n to 6.n, as well as from 6.n to 7.n!
* If you are using {ml} {dfeeds} that contain discontinued search or query
domain specific language (DSL), the upgrade will fail. In 5.6.5 and later, the
Upgrade Assistant provides information about which {dfeeds} need to be updated.

===============================

[[apm-breaking-changes]]
=== APM breaking changes
++++
<titleabbrev>APM</titleabbrev>
++++

This list summarizes the most important breaking changes in APM. 
For the complete list, go to {apm-server-ref-70}/breaking-changes.html[APM Server 7.0 breaking changes].

include::{apm-repo-dir}/apm-breaking-changes.asciidoc[tag=notable-v75-breaking-changes]

[[beats-breaking-changes]]
=== Beats breaking changes
++++
<titleabbrev>Beats</titleabbrev>
++++

//This list summarizes the most important breaking changes in Beats.
For the
complete list, go to {beats-ref}/breaking-changes.html[Beats breaking changes].

include::{beats-repo-dir}/release-notes/breaking/breaking-7.5.asciidoc[tag=notable-breaking-changes]


[[elasticsearch-breaking-changes]]
=== {es} breaking changes
[subs="attributes"]
++++
<titleabbrev>{es}</titleabbrev>
++++

This list summarizes the most important breaking changes in {es} {version}. For
the complete list, go to {ref}/breaking-changes.html[{es} breaking changes].

include::{es-repo-dir}/reference/migration/migrate_7_5.asciidoc[tag=notable-breaking-changes]

[[elasticsearch-hadoop-breaking-changes]]
=== {es} Hadoop breaking changes
[subs="attributes"]
++++
<titleabbrev>{es} Hadoop</titleabbrev>
++++

//This list summarizes the most important breaking changes in {es} Hadoop {version}.
For the complete list, go to
{hadoop-ref}/breaking-changes.html[Elasticsearch Hadoop breaking changes].

include::{hadoop-repo-dir}/appendix/breaking.adoc[tag=notable-v7-breaking-changes]

[[kibana-breaking-changes]]
=== {kib} breaking changes
[subs="attributes"]
++++
<titleabbrev>{kib}</titleabbrev>
++++

This page lists the breaking changes in {kib} {version}.

include::{kib-repo-dir}/migration/migrate_7_5.asciidoc[tag=notable-breaking-changes]

[[logstash-breaking-changes]]
=== {ls} breaking changes
[subs="attributes"]
++++
<titleabbrev>{ls}</titleabbrev>
++++

This list summarizes the most important breaking changes in {ls} {version}. For
the complete list, go to
{logstash-ref}/breaking-changes.html[Logstash breaking changes].

include::{ls-repo-dir}/static/breaking-changes.asciidoc[tag=notable-breaking-changes]

