[[elastic-stack-breaking-changes]]
== Breaking changes

Before you upgrade, you must review the breaking changes for each product you
use and make the necessary changes so your code is compatible with {version}. 

** {apm-server-ref}/breaking-changes.html[APM Server {version} breaking changes]
** <<beats-breaking-changes,Beats {version} breaking changes>>
** <<elasticsearch-breaking-changes,{es} {version} breaking changes>>
** {hadoop-ref}/breaking-changes.html[Elasticsearch Hadoop {version} breaking changes]
** <<kibana-breaking-changes,Kibana {version} breaking changes>>
** {logstash-ref}/breaking-changes.html[Logstash {version} breaking changes]

[IMPORTANT]
===============================

* If you're upgrading from 2.n, make sure you check the breaking changes from
2.n to 5.n, as well as from 5.n to 6.n!
* If you are using {ml} {dfeeds} that contain discontinued search or query
domain specific language (DSL), the upgrade will fail. In 5.6.5 and later, the
Upgrade Assistant provides information about which {dfeeds} need to be updated.

===============================

[[beats-breaking-changes]]
=== Beats breaking changes
++++
<titleabbrev>Beats</titleabbrev>
++++

This list summarizes the most important breaking changes in Beats. 
For the complete list, go to {beats-ref}/breaking-changes.html[Beats breaking changes].

include::{beats-repo-dir}/breaking.asciidoc[tag=notable-breaking-changes]


[[elasticsearch-breaking-changes]]
=== {es} breaking changes
[subs="attributes"]
++++
<titleabbrev>{es}</titleabbrev>
++++

coming[8.0.0]

This list summarizes the most important breaking changes in {es} {version}. For
the complete list, go to {ref}/breaking-changes.html[{es} breaking changes].

include::{es-repo-dir}/reference/migration/migrate_8_0.asciidoc[tag=notable-breaking-changes]

[[kibana-breaking-changes]]
=== {kib} breaking changes
[subs="attributes"]
++++
<titleabbrev>{kib}</titleabbrev>
++++

coming[8.0.0]

This list summarizes the most important breaking changes in {kib} {version}. For
the complete list, go to {kibana-ref}/breaking-changes.html[{kib} breaking changes].

include::{kib-repo-dir}/migration/migrate_8_0.asciidoc[tag=notable-breaking-changes]

