[[elastic-stack-breaking-changes]]
== Breaking changes

Before you upgrade, you must review the breaking changes for each product you
use and make the necessary changes so your code is compatible with {version}.

** <<apm-breaking-changes,APM {version} breaking changes>>
** <<beats-breaking-changes,Beats {version} breaking changes>>
** <<elasticsearch-breaking-changes,{es} {version} breaking changes>>
** <<elasticsearch-hadoop-breaking-changes,{es} Hadoop {version} breaking changes>>
** <<kibana-breaking-changes,Kibana {version} breaking changes>>
** <<logstash-breaking-changes,{ls} {version} breaking changes>>

[IMPORTANT]
===============================
* Make sure you check the breaking changes for each point release up to the desired new version.
* If you're upgrading from 5.n, make sure you check the breaking changes from
5.n to 6.n, as well as from 6.n to 7.n!
* If you are using {ml} {dfeeds} that contain discontinued search or query
domain specific language (DSL), the upgrade will fail. In 5.6.5 and later, the
Upgrade Assistant provides information about which {dfeeds} need to be updated.

===============================

[[apm-breaking-changes]]
=== APM breaking changes
++++
<titleabbrev>APM</titleabbrev>
++++

This list summarizes the most important breaking changes in APM.
For the complete list, go to {apm-guide-ref}/apm-breaking.html[APM breaking changes].

include::{apm-repo-dir}/all-breaking-changes.asciidoc[tag=717-bc]

[[beats-breaking-changes]]
=== Beats breaking changes
++++
<titleabbrev>Beats</titleabbrev>
++++

This list summarizes the most important breaking changes in Beats.
For the complete list, go to {beats-ref}/breaking-changes.html[Beats breaking changes].

include::{beats-repo-dir}/release-notes/breaking/breaking-7.17.asciidoc[tag=notable-breaking-changes]


[[elasticsearch-breaking-changes]]
=== {es} breaking changes
[subs="attributes"]
++++
<titleabbrev>{es}</titleabbrev>
++++

This list summarizes the most important breaking changes in {es} {version}. For
the complete list, go to {ref}/breaking-changes.html[{es} breaking changes].

include::{es-repo-dir}/migration/migrate_7_17.asciidoc[tag=notable-breaking-changes]

[[elasticsearch-hadoop-breaking-changes]]
=== {es} Hadoop breaking changes
[subs="attributes"]
++++
<titleabbrev>{es} Hadoop</titleabbrev>
++++

No breaking changes.

[[kibana-breaking-changes]]
=== {kib} breaking changes
[subs="attributes"]
++++
<titleabbrev>{kib}</titleabbrev>
++++

This list summarizes the most important breaking changes in {kib} {version}.
For the complete list, go to {kibana-ref}/release-notes-7.17.0.html#breaking-changes-v7.17.0[{kib} breaking changes].

include::{kib-repo-dir}/CHANGELOG.asciidoc[tag=notable-breaking-changes]

[[logstash-breaking-changes]]
=== {ls} breaking changes
[subs="attributes"]
++++
<titleabbrev>{ls}</titleabbrev>
++++

This list summarizes the most important breaking changes in {ls} {version}. For
the complete list, go to
{logstash-ref}/breaking-changes.html[Logstash breaking changes].

include::{ls-repo-dir}/static/breaking-changes.asciidoc[tag=notable-breaking-changes]
