[[elastic-stack-highlights]]
== Highlights 

Each release brings new features and product improvements. This section
highlights notable new features and enhancements in {version}.

//** <<apm-highlights,APM>>
** <<beats-highlights,Beats>>
** <<elasticsearch-highlights,{es}>>
** <<kibana-higlights,{kib}>>

////
[[apm-highlights]]
=== APM highlights
++++
<titleabbrev>APM</titleabbrev>
++++

This list summarizes the most important enhancements in APM.
For the complete list, go to
{apm-overview-ref-v}/apm-release-notes.html[APM release highlights].

include::{apm-repo-dir}/apm-release-notes.asciidoc[tag=notable-v7-highlights]
////

[[beats-highlights]]
=== Beats highlights
++++
<titleabbrev>Beats</titleabbrev>
++++

coming::[7.8.0]

This list summarizes the most important enhancements in Beats.
For the complete list, go to {beats-ref}/release-highlights.html[Beats release highlights].

//include::{beats-repo-dir}/release-notes/highlights/highlights-7.8.0.asciidoc[tag=notable-highlights]

[[elasticsearch-highlights]]
=== {es} highlights
[subs="attributes"]
++++
<titleabbrev>{es}</titleabbrev>
++++

coming::[7.8.0]

This list summarizes the most important enhancements in {es} {version}.
For the complete list, go to {ref}/release-highlights.html[{es} release highlights].

:leveloffset: +1

include::{es-repo-dir}/reference/release-notes/highlights-7.8.0.asciidoc[tag=notable-highlights]

:leveloffset: -1

[[kibana-higlights]]
=== {kib} highlights
[subs="attributes"]
++++
<titleabbrev>{kib}</titleabbrev>
++++

coming::[7.8.0]

This list summarizes the most important enhancements in {kib} {version}.

////
:leveloffset: +1

include::{kib-repo-dir}/release-notes/highlights-7.3.0.asciidoc[tag=notable-highlights]

:leveloffset: -1
////