[[elastic-stack-highlights]]
== Highlights 

Each release brings new features and product improvements. This section
highlights notable new features and enhancements in {version}.

** <<beats-highlights,Beats>>
** <<elasticsearch-highlights,{es}>>
** <<kibana-higlights,{kib}>>

[[beats-highlights]]
=== Beats highlights
++++
<titleabbrev>Beats</titleabbrev>
++++

This list summarizes the most important enhancements in Beats.
For the complete list, go to {beats-ref}/release-highlights.html[Beats release highlights].


//include::{beats-repo-dir}/highlights-7.1.0.asciidoc[tag=notable-highlights]

[[elasticsearch-highlights]]
=== {es} highlights
[subs="attributes"]
++++
<titleabbrev>{es}</titleabbrev>
++++

This list summarizes the most important enhancements in {es} {version}.
For the complete list, go to {ref}/release-highlights.html[{es} release highlights].


:leveloffset: +1

include::{es-repo-dir}/reference/release-notes/highlights-7.1.0.asciidoc[tag=notable-highlights]

:leveloffset: -1

[[kibana-higlights]]
=== {kib} highlights
[subs="attributes"]
++++
<titleabbrev>{kib}</titleabbrev>
++++

This list summarizes the most important enhancements in {kib} {version}.
For the complete list, go to {kibana-ref}/release-highlights.html[{kib} release highlights].


:leveloffset: +1

include::{kib-repo-dir}/release-notes/highlights-7.1.0.asciidoc[tag=notable-highlights]

:leveloffset: -1
