[[installing-elastic-stack]]
== Installing the Elastic Stack

This guide is intended for users seeking to install all or part of the Elastic Stack as part of
clean or fresh installation. If you are upgrading, then please refer to <<upgrading-elastic-stack>>.

Beginning with 5.0, installing the Elastic Stack and understanding the compatibility between products
has been dramatically simplified. All products are now part of a unified release process, so when
any product is released, then all products are released with it. This helps to guarantee compatibility as
well as avoid confusion surrounding version numbers.

As a result, when performing any Elastic Stack installation, you should always start with the same
version across the entire stack. For example, if you select Elasticsearch 5.1.2, then you should also
select Kibana 5.1.2, Logstash 5.1.2, and Beats 5.1.2.

[cols="2", options="header"]
|===
|Component |Version
|Beats
|{branch}
|Elasticsearch
|{branch}
|Elasticsearch Hadoop
|{branch}
|Kibana
|{branch}
|Logstash
|{branch}
|X-Pack
|{branch}
|===

[[install-order-elastic-stack]]
=== Installation Order

We recommend that you install the Elastic Stack in the following order.

1. Elasticsearch
    * X-Pack for Elasticsearch
2. Kibana
    *  X-Pack for Kibana
3. Logstash
4. Beats
5. Elasticsearch Hadoop

This helps to ensure that the right parts of your infrastructure are running before other parts
attempt to use them (e.g., Logstash sending data to Elasticsearch).

The table below lists the installation instructions, per component:

[cols="2", options="header"]
|===
|Product |Installation
|Elasticsearch
|{esref}/install-elasticsearch.html[Installing Elasticsearch 5.0]
|X-Pack
|{xpackref}/installing-xpack.html[Installing X-Pack 5.0]
|Kibana
|{kibanaref}/setup.html[Installing Kibana 5.0]
|Logstash
|{logstashref}/installing-logstash.html[Installing Logstash 5.0]
|Beats
|{beatsref}/installing-beats.html[Installing Beats 5.0]
|Elasticsearch Hadoop
|{hadoopref}/float.html[Installing Elasticsearch Hadoop 5.0]
|===

[[install-elastic-stack-for-elastic-cloud]]
=== Installing on Elastic Cloud

Elastic Cloud is the official hosted Elasticsearch and Kibana offering from Elastic and it's designed to be easy. A single click creates an Elasticsearch cluster configured to the size you want, with or without high availability. X-Pack is always installed and provides features such as security and monitoring. Kibana can be enabled on a cluster with a click, and a number of commonly requested plugins are readily available.

Some Elastic Cloud features can be used only with a specific  link:https://www.elastic.co/cloud/as-a-service/subscriptions[subscription level]. For example, you can install custom plugins, dictionaries, and scripts only if you are a Gold or Platinum customer.

To learn more about Elastic Cloud, see our {cloudref}/ec-getting-started.html[getting started documentation]. Or link:https://www.elastic.co/cloud/as-a-service/signup[sign up for a free trial] and start exploring hosted Elasticsearch within minutes.
