[[installing-elastic-stack]]
== Installing the Elastic Stack

When installing the Elastic Stack, you must use the same version
across the entire stack. For example, if you are using Elasticsearch
{version}, you install Beats {version}, APM Server {version}, Elasticsearch Hadoop {version},
Kibana {version}, and Logstash {version}.

If you're upgrading an existing installation, see <<upgrading-elastic-stack, Upgrading the Elastic Stack>> for information about how to ensure compatibility with {version}.

[[install-order-elastic-stack]]
=== Installation Order

Install the Elastic Stack products you want to use in the following order:

. Elasticsearch ({ref}/install-elasticsearch.html[install instructions])
. Kibana ({kibana-ref}/install.html[install])
. Logstash ({logstash-ref}/installing-logstash.html[install])
. Beats ({beats-ref}/getting-started.html[install instructions])
. APM Server ({apm-server-ref-70}/installing.html[install instructions])
. Elasticsearch Hadoop ({hadoop-ref}/install.html[install instructions])

Installing in this order ensures that the components each product depends
on are in place.

[[install-elastic-stack-for-elastic-cloud]]
=== Installing on Elastic Cloud

The https://www.elastic.co/cloud/elasticsearch-service[Elasticsearch Service]
on Elastic Cloud is the official hosted Elasticsearch and Kibana offering from
Elastic. The Elasticsearch Service is available on both AWS and GCP.

Installing on Elastic Cloud is easy: a single click creates an Elasticsearch
cluster configured to the size you want, with or without high availability.
{xpack} is always installed, so you automatically have the ability to secure
and monitor your cluster. Kibana can be enabled on a cluster with a click, and
a number of popular plugins are readily available.

Some Elastic Cloud features can be used only with a specific
link:https://www.elastic.co/cloud/as-a-service/subscriptions[subscription level].
For example, installing custom plugins, dictionaries, and scripts requires a Gold
or Platinum subscription.

You can https://www.elastic.co/cloud/elasticsearch-service/signup[try out the
Elasticsearch Service for free]. For more information, see
{cloud}/ec-getting-started.html[Getting Started with Elastic Cloud].

