[[installing-elastic-stack]]
== Installing the Elastic Stack

When installing the Elastic Stack, you must use the same version
across the entire stack. For example, if you are using Elasticsearch
{version}, you install Beats {version}, APM Server {version}, Elasticsearch Hadoop {version},
Kibana {version}, and Logstash {version}.

If you're upgrading an existing installation, see <<upgrading-elastic-stack, Upgrading the Elastic Stack>> for information about how to ensure compatibility with {version}.

[discrete]
[[network-requirements]]
=== Network requirements

// https://support.elastic.dev/knowledge/view/CfT70cu9

The following ports need to be open for components of the Elastic Stack.

[cols="1,1,1"]
|===
|Default ports |Access type| Component

|5601
|HTTP
|{kib}

|8200
|HTTP
|APM Server

|9200-9300
|HTTP
|{es} REST API

|9300-9400
|TCP
|Transport interfact used for communication between nodes in a cluster.

|9600-9700
|HTTP
|{ls}

|===

For more information on supported network configurations, see {ingest-guide}[{es} Ingest Architectures].

[discrete]
[[install-order-elastic-stack]]
=== Installation order

Install the Elastic Stack products you want to use in the following order:

. Elasticsearch ({ref}/install-elasticsearch.html[install instructions])
. Kibana ({kibana-ref}/install.html[install])
. Logstash ({logstash-ref}/installing-logstash.html[install])
. Beats ({beats-ref}/getting-started.html[install instructions])
. APM ({apm-guide-ref}/apm-quick-start.html[install instructions])
. Elasticsearch Hadoop ({hadoop-ref}/install.html[install instructions])

Installing in this order ensures that the components each product depends
on are in place.

[discrete]
[[install-elastic-stack-for-elastic-cloud]]
=== Installing on {ecloud}

{ess-leadin-short}

Installing on {ecloud} is easy: a single click creates an {es} cluster
configured to the size you want, with or without high availability. The
subscription features are always installed, so you automatically have the
ability to secure and monitor your cluster. {kib} is enabled automatically,
and a number of popular plugins are readily available.

Some {ecloud} features can be used only with a specific subscription. For more
information, see https://www.elastic.co/pricing/.

