["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

[role="exclude",id="elasticsearch-hadoop-breaking-changes"]
=== {es} Hadoop breaking changes

This page no longer exists. For the latest breaking changes, refer to
{hadoop-ref}/breaking-changes.html[{es} Hadoop breaking changes].

[role="exclude",id="apm-highlights"]
=== APM highlights

This page no longer exists.
See {observability-guide}/whats-new.html[Observability highlights] for a list of what's new in Elastic Observability.

[role="exclude",id="beats-highlights"]
=== Beats highlights

This page no longer exists.
See the {observability-guide}/whats-new.html[Observability highlights] page for a list of what's new in Elastic Observability.

[role="exclude",id="elastic-stack-highlights"]
=== Highlights

This page no longer exists.
Go to {estc-welcome}/new.html[Check out the latest from Elastic].

[role="exclude",id="apm-breaking-changes"]
=== APM breaking changes

This page no longer exists.
See {apm-guide-ref}/apm-breaking.html[APM breaking changes] instead.

[role="exclude",id="beats-breaking-changes"]
=== Beats breaking changes

This page no longer exists.
See {beats-ref}/breaking-changes.html[{beats} breaking changes] instead.

[role="exclude",id="elasticsearch-breaking-changes"]
=== {es} breaking changes

This page no longer exists.
See {ref}/breaking-changes.html[{es} migration guide] instead.

[role="exclude",id="security-breaking-changes"]
=== {elastic-sec} breaking changes

This page no longer exists.
See {security-guide}/release-notes.html[{elastic-sec} release notes] instead.

[role="exclude",id="kibana-breaking-changes"]
=== {kib} breaking changes

This page no longer exists.
See {kibana-ref}/release-notes.html[{kib} release notes] instead.

[role="exclude",id="logstash-breaking-changes"]
=== {ls} breaking changes

This page no longer exists.
See {logstash-ref}/breaking-changes.html[{ls} breaking changes] instead.
