[[upgrade-on-ece]]
=== Upgrade on Elastic Cloud Enterprise (ECE)

Similar to {ecloud} Hosted, a single click in the {ecloud} console can upgrade a deployment running on ECE to a newer version. During the upgrade process, {es}, {kib}, and all of your deployment components are upgraded simultaneously.

Once you're <<prepare-upgrade-9.0,prepared to upgrade>>, do the following: 

. Ensure your current ECE and Docker versions are https://www.elastic.co/support/matrix/#matrix_os[compatible] with {version} (the minimum required version for 9.x is ECE 3.0). If you don’t have a compatible version installed, <<upgrade-orchestrator,upgrade your orchestrator>>. 
. Download the most recent {ece-ref}/ece-manage-elastic-stack.html#ece_most_recent_elastic_stack_packs[stack pack] for the version you're upgrading to, then {ece-ref}/ece-manage-elastic-stack.html#ece-manage-elastic-stack-add[add the stack pack] to your installation via the Cloud UI. 
. Back up your data to a snapshot. First, {ece-ref}/ece-manage-repositories.html[configure a snapshot repository] to enable snapshots. 

[discrete]
[[perform-upgrade-ece]]
==== Perform the upgrade

. Log in to the {ece-ref}/ece-login.html[Cloud UI]. 
. On the Deployments page, select your deployment. 
+
Narrow the list by name, ID, or choose from several other filters. To further define the list, use a combination of filters.

To upgrade a deployment:

. In the *Deployment version* section, click *Upgrade*.
. Select version {version}.
. Click *Upgrade*, then *Confirm upgrade*. The new configuration takes a few minutes to create.
+
NOTE: If any incompatibilities are detected when you attempt to upgrade to {version}, the UI provides a link to the Upgrade Assistant, which checks for deprecated settings in your cluster and indices and helps you resolve them. After resolving the issues, return to the deployments page and restart the upgrade. 

Security realm settings::
During the upgrade process, you are prompted to update the security realm settings if your user settings include a `xpack.security.authc.realms` value. 
+
If the security realms are configured in `user_settings`, you'll be prompted to modify the settings:
+
.. On the *Update security realm settings* window, edit the settings.
+
.. Click *Update settings*.
+
If the security realm settings are located in `user_settings_override`, contact Support to help you upgrade.

After you're done upgrading, upgrade your ingest components in the following order: 

. Logstash: {logstash-ref}/upgrading-logstash.html[upgrade instructions]
. Beats: {beats-ref}/upgrading.html[upgrade instructions]
. {agent}: {fleet-guide}/upgrade-elastic-agent.html[upgrade instructions]
. APM agents: {observability-guide}/apm-upgrade.html[upgrade instructions]

