[id="cloud-upgrading-v7"]
=== Upgrade to Elasticsearch 7.x on Elastic Cloud

If you have a cluster and want to upgrade to version 7.x, there are a few things you must do to prepare for the upgrade. Preparing for your upgrade ahead of time ensures that you can enjoy the new features and improved usability of Elasticsearch 7.x as quickly as possible.

[float]
=== Before you begin

{n} upgrades differ from your on-premise installation because all major configuration changes for Elasticsearch, Kibana, and the security features are handled for you.

When you upgrade, {n} automatically runs the deprecation API to retrieve information about the cluster, node, and index-level settings that need to be removed or changed. If there are any deprecation issues that would prevent the upgraded deployment from successfully performing, the upgrade fails. To resolve the deprecation issues, use the Upgrade Assistant in Kibana. 

//If your cluster does not include a Kibana instance yet, you can 
//ifeval::["{p}"=="ece"]
//<<{p}-manage-kibana,enable Kibana first,>>
//endif::[]
//ifeval::["{p}"!="ece"]
//<<{p}-enable-kibana,enable Kibana first,>>
//endif::[]
//then use the Upgrade Assistant. After you resolve the deprecation issues, try the upgrade again.

For more information, refer to:

* link:https://www.elastic.co/guide/en/elastic-stack/7.0/upgrading-elastic-stack.html[Upgrading the Elastic Stack]
* link:https://www.elastic.co/guide/en/elasticsearch/reference/7.0/setup-upgrade.html[Upgrading Elasticsearch]

[float]
==== Snapshot behavior during upgrades

To keep your data safe, {n} takes a snapshot before making any changes to your cluster. After a major version upgrade is complete, and the first successful snapshot with the new major version is available, all snapshots taken with the previous version of Elasticsearch are removed.

For example, before upgrading from Elasticsearch version 6.7 to version 7.x, a snapshot is taken. After the upgrade to version 7.x is complete, and a snapshot is available, all snapshots taken with version 6.x are removed.

//ifeval::["{p}"=="ece"]
//TIP: To enable snapshots, configure the snapshot repository.
//endif::[]

[float]
[id="cloud-upgrading-v7-reindex"]
==== Reindex indices

Elasticsearch 7.x is compatible with indices created in version 6.0 or later. If you have indices from version 5.x or earlier, you must remove or reindex them before you upgrade. 

TIP: If prompted by {n}, use the Upgrade Assistant in Kibana to reindex your data.

[float]
[id="cloud-upgrading-v7-breaking"]
==== Review breaking changes

Major version upgrades can include changes that expose the upgrading process to possible risk. A breaking change is the result of a functional change between major Elasticsearch versions, and requires you to perform additional steps to ensure that you can use the new version as intended. 

For more information, refer to link:https://www.elastic.co/guide/en/elasticsearch/reference/{version7}/breaking-changes.html[Breaking changes in {version7}].

[float]
[id="cloud-upgrading-v7-issues"]
==== Review the known issues

The following known issues apply to the Elastic Stack 7.x releases:

* There are deprecated APIs that are still available for use. If you see warnings in the {n} logs about the deprecated APIs, you can ignore them.

* {n} does not support the ability to upgrade to or from release candidate builds, such as 7.0.0-rc1.

//ifeval::["{p}"!="ech"]
//* For Elasticsearch 7.8 and later the Index Lifecycle Managment (ILM) API is always enabled, even if the cluster is still using the deprecated index curation. If index curation and ILM are both configured to process the same indices the outcome can be unpredictable. As other stack products default to using ILM when it is available in Elasticsearch, we strongly encourage you to <<{p}-migrate-index-management,migrate to index lifecycle management>>. It also has a superior feature set.
//endif::[]

[float]
[id="cloud-log-in-kibana"]
==== Log in to Kibana

//When you upgrade from version 6.7 to 7.0, you must first <<{p}-access-kibana,log in to Kibana>> to make sure that your upgrade is successful.

[float]
[id="cloud-update-security-realm-settings"]
==== Update the security realm settings

During the upgrade process, you are prompted to update the security realm settings when your `user_settings` include a `xpack.security.authc.realms` value. 

There are two settings that prompt you to update:

* If the security realm settings are located in `user_settings_override`, contact support to help you upgrade.

* If the security realm settings are located in `user_settings`, you'll receive a message that allows you modify these settings. 

To modify the `user_settings`:

. On the *Update security realm settings* window, edit the settings.

. Click *Update settings*.

[float]
==== A note about X-Pack

*In Elasticsearch version 7.0 and later*, the security features to keep your {n} deployments safe are now referred to simply as security features instead of X-Pack.

//For information about the security features in Elasticsearch version 7.0 and earlier, refer to
//ifeval::["{p}"!="ece"]
//<<{p}-security,Securing your deployment>>.
//endif::[]
//ifeval::["{p}"=="ece"]
//<<{p}-securing-clusters,Secure your clusters>>.
//endif::[] 
