[[upgrading-kibana]]
=== Upgrade {kib}

[WARNING]
====
{kib} automatically runs saved object migrations when required. To roll back to an
earlier version in case of an upgrade failure, you **must** have a
{ref}/snapshot-restore.html[backup snapshot] that includes the `kibana` feature
state. Snapshots include this feature state by default.

For more information, check {kibana-ref}/saved-object-migrations.html[Migrate saved objects].
====

Before you start, <<upgrading-elastic-stack,take the upgrade preparation
steps>>. To upgrade {kib}:

. Shut down all {kib} instances. {kib} does not support rolling upgrades.
**Upgrading while older {kib} instances are running can cause data loss or upgrade failures.**

. To install the `deb` or `rpm` package:

.. Use `rpm` or `dpkg`. This installs all files in their proper locations 
and will not overwrite the config files.
.. Upgrade any plugins by removing the existing plugin and reinstalling the
  appropriate version using the `kibana-plugin` script. For more information, 
  see {kibana-ref}/kibana-plugins.html[{kib} plugins].
   
. To install from a `zip` or `tar.gz` archive:

.. **Extract the archive to a new directory** to be sure that you
  don't overwrite the `config` or `data` directories. 

.. Copy the files from the `config` directory from your old installation to your
  new installation. 
.. Copy the files from the `data` directory from your old installation to your
  new installation.
+
IMPORTANT: If you use {monitor-features}, you must re-use the data directory when you upgrade {kib}. 
  Otherwise, the {kib} instance is assigned a new persistent UUID and becomes a new instance in the monitoring data.

.. Install the appropriate versions of all your plugins for your new
  installation using the `kibana-plugin` script. For more information, 
  see {kibana-ref}/kibana-plugins.html[{kib} plugins].

. Start {kib}.

IMPORTANT: {kib} has a new logging system in 8.0 and the log formats have changed. 
For additional information, see {kibana-ref}/logging-config-changes.html[Logging configuration changes].
