[id="{p}-upgrading-v6"]
=== Upgrade to Elasticsearch 6.x

If you have an existing cluster and want to upgrade to version 6.x, there are a few things you need to keep in mind. Preparing for your upgrade ahead of time ensures that you can enjoy the major new features and improved usability of Elasticsearch 6.x as quickly as possible.

[float]
=== Before you begin

Upgrading on {n} differs from upgrading your on-premise installation in that all major configuration changes to upgrade Elasticsearch, Kibana, and X-Pack are handled for you. Your responsibility when preparing to upgrade to version 6.x is to make sure that your indices are ready for version 6.x by reindexing, if necessary, and that you are aware of breaking changes that could affect you.

The upgrade process to Elasticsearch 6.x is a two-step process that uses version 5.6 as an intermediate upgrade step. To upgrade to version 6.x, you must:
ifeval::["{p}"=="ece"]
. Upgrade from Elasticsearch version 2.x or version 5.x to version 5.6.
endif::[]
ifeval::["{p}"!="ece"]
. Upgrade from Elasticsearch version 5.x to version 5.6.
endif::[]
. Upgrade from Elasticsearch version 5.6 to version 6.x.

When upgrading to version 6.x, {n} automatically runs the deprecation API to retrieve information about different cluster, node, and index level settings that are removed or changed. If there are any deprecation issues that would prevent the upgraded cluster from performing correctly, {n} does not perform the upgrade and instead asks you to resolve the issues through the Upgrade Assistant in Kibana first. If your cluster does not include a Kibana instance yet, you can 
ifeval::["{p}"=="ece"]
<<{p}-manage-kibana,enable Kibana first>>
endif::[]
ifeval::["{p}"!="ece"]
<<{p}-enable-kibana,enable Kibana first>>
endif::[]
and then use the Upgrade Assistant. After resolving the issues flagged by the deprecation API, you should be able to perform the upgrade successfully.

Steps you might need to perform before upgrading:

ifeval::["{p}"=="ece"]
* At least the default *Enable sandboxed inline scripts* option must be set on the *Configuration* page for your cluster or the upgrade to version 6.x cannot proceed.
endif::[]
ifeval::["{p}"!="ece"]
* <<{p}-scripting,Enable inline scripting>>. At least the default *Enable sandboxed inline scripts* option must be set on the *Configuration* page for your cluster or the upgrade to version 6.x cannot proceed.
endif::[]

* <<{p}-upgrading-v6-reindex,Reindex indices created in older versions of Elasticsearch>> to ensure compatibility with version 6.x.

* <<{p}-upgrading-v6-breaking,Review breaking changes in Elasticsearch 6.x>> before upgrading.

* Check the <<{p}-upgrading-v6-issues,known issues>> on {n}.

In version 6.x, TLS between Elasticsearch cluster nodes is always enabled on {n}. To enable internal TLS between cluster nodes, Elasticsearch cluster must perform a full cluster restart on {n}, even if you are upgrading from version 5.6.

Additional background information about upgrading the Elastic Stack is available, but keep in mind that most steps are handled for you, unless they are specifically called out in the {n} documentation that you are currently reading:

* link:https://www.elastic.co/guide/en/elastic-stack/{version6}/upgrading-elastic-stack.html[Upgrading the Elastic Stack]
* link:https://www.elastic.co/guide/en/elasticsearch/reference/6.0/setup-upgrade.html[Upgrading Elasticsearch]

[float]
==== Snapshot behavior during upgrades

To ensure an upgrade process that always keeps your data safe, {n} takes a snapshot before making any changes to your cluster. After a major version upgrade is complete and the first successful snapshot with the new major version is available, all snapshots taken with previous version of Elasticsearch are removed.

For example, before upgrading from Elasticsearch version 5.6 to version 6.x, a snapshot is taken. After the upgrade to version 6.x is complete and a first snapshot with the new version is available, all snapshots taken with version 5.x are removed.
ifeval::["{p}"=="ece"]
Similar behavior applies if you first upgrade from version 2.x to 5.6 and then to 6.x.

TIP: To enable snapshots, you need to configure a snapshot repository.
endif::[]

[float]
[id="{p}-upgrading-v6-breaking"]
=== Review breaking changes in Elasticsearch 6.x

Elastic is always working on making upgrades across major versions easier, but major version upgrades often include so many changes that upgrading can carry some risk. A breaking change is the result of a functional change between major Elasticsearch versions that requires you to perform some additional step or steps in order to ensure that you can use the new version as intended. To learn more, see link:https://www.elastic.co/guide/en/elasticsearch/reference/{version6}/breaking-changes.html[Breaking changes in {version6}].

[float]
[id="{p}-upgrading-v6-reindex"]
=== Reindex indices created in older versions of Elasticsearch

Elasticsearch 6.x can read indices created in version 5.0 or above. An Elasticsearch 6.x node will not start if indices created in a version of Elasticsearch before 5.0 are present.
ifeval::["{p}"=="ece"]
Indices created in Elasticsearch 2.x or before need to be reindexed with Elasticsearch 5.x in order to be readable by Elasticsearch 6.x. 
endif::[]
If prompted by {n}, use the Upgrade Assistant in Kibana to reindex your data.

[float]
[id="{p}-upgrading-v6-issues"]
=== Known issues with {version6-long} on {n}

The following known problems apply to the Elastic Stack {version6-long} release:

* The Transport Client is not supported in {version6-long}. While we work on adding support, you can continue to use the  link:https://www.elastic.co/guide/en/elasticsearch/client/java-rest/{version6}/index.html[Java REST client] as a workaround.

// We expect to fix all of these issues in either an upcoming release candidate or in the GA release.

[float]
[id="{p}-upgrading-v6-steps"]
=== Upgrade to Elastic Stack {version6}

To deploy {version6}, excluding Elastic Stack {version6-long} and earlier releases:

. {login}

. Upgrade from Elasticsearch version 2.x or version 5.x to version 5.6.

. Upgrade from version 5.6 to version 6.x.

. Test Elasticsearch and Kibana 6.x!
