[[upgrade-orchestrator]]
=== Upgrade your orchestrator

NOTE: This topic applies only to customers running the {stack} on {ece} (ECE) or {eck} (ECK). 

Elastic provides customers with two major self-managed orchestrators to manage the {stack}. Before you can upgrade the products in the stack, you need to ensure your orchestrator is running a compatible version.If it's incompatible, you'll need to upgrade the orchestrator first before you can upgrade the stack.  

==== Upgrade ECE

{ece} (ECE) provides an easy way to provision, manage, and scale a fleet of Elasticsearch deployments from a central place. It can be installed on a public cloud platform, such as AWS, GCP or Microsoft Azure, on your own private cloud, or on bare metal.

If you’re planning to upgrade to {version}, the minimum required version is ECE 3.0.0. If you're running an earlier version, refer to {ece-ref}/ece-upgrade.html[Upgrade your installation] for instructions on how to upgrade.   

==== Upgrade ECK

{eck} (ECK) is built on the Kubernetes operator pattern and extends the basic Kubernetes orchestration capabilities to support the setup and management of Elastic products and solutions on Kubernetes.

If you're planning to upgrade to {version}, refer to the list of {eck-ref}/k8s-supported.html[supported versions] to ensure your current ECK version is compatible. If it isn't, refer to {eck-ref}/k8s-upgrading-eck.html[Upgrade ECK] for instructions on how to upgrade. 
