[role="xpack"]
[[ml-getting-started]]
== Getting started with machine learning
++++
<titleabbrev>Getting started</titleabbrev>
++++

Ready to get some hands-on experience with the {ml-features}? This
tutorial shows you how to:

* Load a sample data set into {es}
* Create single and multi-metric {ml} jobs in {kib}
* Use the results to identify possible anomalies in the data

At the end of this tutorial, you should have a good idea of what {ml} is and
will hopefully be inspired to use it to detect anomalies in your own data.

You might also be interested in these video tutorials, which use the same sample
data:

* https://www.elastic.co/videos/machine-learning-tutorial-creating-a-single-metric-job[Machine Learning for the Elastic Stack: Creating a single metric job]
* https://www.elastic.co/videos/machine-learning-tutorial-creating-a-multi-metric-job[Machine Learning for the Elastic Stack: Creating a multi-metric job]

[float]
[[ml-gs-sysoverview]]
=== Before you begin

. Install {es} and {kib}. You can follow the steps in 
{stack-gs}/get-started-elastic-stack.html[Getting started with the {stack}]. 
{es} stores the data and the analysis results. {kib} provides a helpful user 
interface for creating and viewing jobs. 
+
--
NOTE: To get started, you can install {es} and {kib} on a single VM or even on 
your laptop (requires 64-bit OS). As you add more data and your traffic grows,
you'll want to replace the single {es} instance with a cluster.

--

. Launch the {kib} web interface by pointing your browser to port 5601. For 
example, http://127.0.0.1:5601[http://127.0.0.1:5601].

. Obtain a license that includes the {ml} features. 
+
--
include::{docdir}/get-started-trial.asciidoc[]
--

. If the {es} {security-features} are enabled in your cluster, you need a user
that has appropriate authority to perform the steps in this tutorial. 
+
--
[[ml-gs-users]]
The {ml-features} use cluster privileges and built-in roles to make it 
easier to control which users have authority to view and manage the jobs,
{dfeeds}, and results.

By default, you can perform all of the steps in this tutorial by using the
built-in `elastic` super user. However, the password must be set before the user
can do anything. For information about how to set that password, see
<<security-getting-started>>.

If you are performing these steps in a production environment, take extra care
because `elastic` has the `superuser` role and you could inadvertently make
significant changes to the system. You can alternatively assign the
`machine_learning_admin` and `kibana_user` roles to a user ID of your choice.

For more information, see <<built-in-roles>> and <<privileges-list-cluster>>.

--

. Optional: If you have multiple nodes in your cluster, you can optionally 
dedicate nodes to specific purposes. If you want to control which nodes are
_machine learning nodes_ or limit which nodes run resource-intensive
activity related to jobs, see 
{ref}/modules-node.html#modules-node-xpack[{ml} node settings]. 

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-data.asciidoc
include::getting-started-data.asciidoc[]

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-wizards.asciidoc
include::getting-started-wizards.asciidoc[]

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-single.asciidoc
include::getting-started-single.asciidoc[]

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-multi.asciidoc
include::getting-started-multi.asciidoc[]

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-forecast.asciidoc
include::getting-started-forecast.asciidoc[]

:edit_url: https://github.com/elastic/elasticsearch/edit/{branch}/x-pack/docs/en/ml/getting-started-next.asciidoc
include::getting-started-next.asciidoc[]