["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

[role="exclude",id="ml-dfeeds"]
=== Datafeeds

This page has moved. See <<ml-datafeeds>>.

[role="exclude",id="ml-configuring-pop"]
=== Performing population analysis

This page has moved. See <<ml-configuring-populations>>.

[role="exclude",id="ml-inference-models"]
=== Trained {ml} models as functions

This content has moved. See <<ml-trained-models>>.

[role="exclude",id="stopping-ml"]
=== Stop {ml} {anomaly-detect}

This content has moved. See <<ml-ad-close-job>>.

[role="exclude",id="create-jobs"]
=== Create {anomaly-jobs}

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-restart-failed-jobs"]
=== Restart failed {anomaly-jobs}

This content has moved. See <<ml-ad-restart-failed-jobs>>.

[role="exclude",id="ml-configuration"]
=== Configure {anomaly-detect}

This content has moved. See <<ml-ad-setup>>.

[role="exclude",id="ml-jobs"]
=== {anomaly-jobs-cap}

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-datafeeds"]
=== {dfeeds-cap}

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-buckets"]
=== Buckets

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-bucket-results"]
=== Bucket results

This content has moved. See <<ml-ad-bucket-results>>.

[role="exclude",id="ml-influencers"]
=== Influencers

This content has moved. See <<influencers>>.

[role="exclude",id="ml-influencer-results"]
=== Influencer results

This content has moved. See <<ml-ad-influencer-results>>.

[role="exclude",id="ml-calendars"]
=== Calendars and scheduled events

This content has moved. See <<ml-ad-calendars>>.

[role="exclude",id="ml-rules"]
=== Custom rules

This content has moved. See <<ml-configuring-detector-custom-rules>>.

[role="exclude",id="ml-model-snapshots"]
=== Model snapshots

This content has moved. See <<ml-ad-model-snapshots>>.

[role="exclude",id="ml-concepts"]
=== Concepts

This content has moved. See <<ml-ad-finding-anomalies>>.