["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

[role="exclude",id="ml-dfeeds"]
=== Datafeeds

This page has moved. See <<ml-ad-datafeeds>>.

[role="exclude",id="ml-datafeeds"]
=== Datafeeds

This page has moved. See <<ml-ad-datafeeds>>.

[role="exclude",id="ml-inference-models"]
=== Trained {ml} models as functions

This content has moved. See <<ml-trained-models>>.

[role="exclude",id="stopping-ml"]
=== Stop {ml} {anomaly-detect}

This content has moved. See <<ml-ad-close-job>>.

[role="exclude",id="create-jobs"]
=== Create {anomaly-jobs}

This content has moved. See <<ml-ad-create-job>>.

[[bucket-span]]
==== Bucket span

This content has moved. See <<ml-ad-bucket-span>>.

[[cardinality]]
==== Cardinality

This content has moved. See <<ml-ad-cardinality>>.

[[detectors]]
==== Detectors

This content has moved. See <<ml-ad-detectors>>.

[[job-tips]]
==== Job tips

This content has moved. See <<ml-ad-job-tips>>.

[[model-memory-limits]]
==== Model memory limits

This content has moved. See <<ml-ad-model-memory-limits>>.


[role="exclude",id="ml-restart-failed-jobs"]
=== Restart failed {anomaly-jobs}

This content has moved. See <<ml-ad-restart-failed-jobs>>.

[role="exclude",id="ml-configuration"]
=== Configure {anomaly-detect}

This content has moved. See <<ml-ad-setup>>.

[role="exclude",id="ml-jobs"]
=== {anomaly-jobs-cap}

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-buckets"]
=== Buckets

This content has moved. See <<ml-ad-create-job>>.

[role="exclude",id="ml-bucket-results"]
=== Bucket results

This content has moved. See <<ml-ad-bucket-results>>.

[role="exclude",id="ml-influencers"]
=== Influencers

This content has moved. See <<ml-ad-influencers>>.

[role="exclude",id="ml-influencer-results"]
=== Influencer results

This content has moved. See <<ml-ad-influencer-results>>.

[role="exclude",id="ml-calendars"]
=== Calendars and scheduled events

This content has moved. See <<ml-ad-calendars>>.

[role="exclude",id="ml-rules"]
=== Custom rules

This content has moved. See <<ml-ad-rules>>.

[role="exclude",id="ml-model-snapshots"]
=== Model snapshots

This content has moved. See <<ml-ad-model-snapshots>>.

[role="exclude",id="ml-concepts"]
=== Concepts

This content has moved. See <<ml-ad-overview>>.

[role="exclude",id="xpack-ml"]
=== Anomaly detection

This content has moved. See <<ml-ad-overview>>.

[role="exclude",id="ml-overview"]
=== Anomaly detection overview

This content has moved. See <<ml-ad-overview>>.

[role="exclude",id="ml-gs-visualizer"]
=== Explore the data in {kib}

This content has moved. See <<sample-data-visualizer>>.

[role="exclude",id="ml-gs-jobs"]
=== Create sample {anomaly-jobs} in {kib}

This content has moved. See <<sample-data-jobs>>.

[role="exclude",id="ml-gs-results"]
=== View {anomaly-detect} results

This content has moved. See <<sample-data-results>>.

[role="exclude",id="ml-gs-forecasts"]
=== Create forecasts

This content has moved. See <<sample-data-forecasts>>.

[role="exclude",id="ml-ges-next"]
=== Next steps

This content has moved. See <<sample-data-next>>.

[role="exclude",id="ml-dfa-lang-ident"]
=== Language identification

This content has moved. See <<ml-nlp-lang-ident>>.

[role="exclude",id="auditbeat-process-hosts-ecs"]
=== Auditbeat host processes

These {anomaly-jobs} were removed in 8.3.0.

[role="exclude",id="security-auditbeat-jobs"]
=== Security: {auditbeat}

These {anomaly-jobs} were removed in 8.3.0.

[role="exclude",id="security-auditbeat-authentication-jobs"]
=== Security: {auditbeat} authentication

These {anomaly-jobs} were removed in 8.3.0.

[role="exclude",id="security-winlogbeat-jobs"]
=== Security: {winlogbeat}

These {anomaly-jobs} were removed in 8.3.0.

[role="exclude",id="security-winlogbeat-authentication-jobs"]
=== Security: {winlogbeat} authentication

These {anomaly-jobs} were removed in 8.3.0.

[role="exclude",id="anomaly-examples"]
=== Examples

This page has moved. See <<anomaly-how-tos>>.