[role="xpack"]
[[setup]]
= Set up {ml-features}
++++
<titleabbrev>Setup and security</titleabbrev>
++++

To use the {stack} {ml-features}, you must have the
{subscriptions}[appropriate license] and at least one <<ml-nodes,{ml} node>> in
your cluster.

If you use {kib}, the {ml} feature must be visible in your
{kibana-ref}/xpack-spaces.html[space] and your source indices must exist in the
same space as your {ml} jobs.

If {stack} {security-features} are enabled, you must also
ensure your users have the <<setup-privileges,necessary privileges>>.

TIP: The fastest way to get started with {ml-features} is to
{ess-trial}[start a free 14-day trial of {ess}] in the cloud.

[discrete]
[[ml-nodes]]
== Machine learning nodes

To use {ml-features}, there must be at least one {ml} node in your cluster. A
{ml} node is a node that has `xpack.ml.enabled` set to `true` and `ml` in
`node.roles`.

If nodes do not have the {ml} role, they cannot run {ml} jobs. If
`xpack.ml.enabled` is `true`, however, they can service API requests. For more
information, see {ref}/modules-node.html#ml-node[Machine learning nodes].

[discrete]
[[setup-privileges]]
== Security privileges

The {stack-security-features} provide {ref}/built-in-roles.html[built-in roles]
and {ref}/security-privileges.html[privileges] that make it easier to control
which users can manage or view {ml} objects such as jobs, {dfeeds}, results, and
model snapshots. {kibana-ref}/kibana-privileges.html[{kib} privileges] enable
you to control access to the {ml-features} within each space.

To _view_ the configuration, status, and results of the {ml-features}, you
must have:

[%interactive]
* [ ] `machine_learning_user` or `machine_learning_admin` built-in roles (if you
use {es} {ml} APIs)
* [ ] `kibana_admin` built-in role or a custom role that has `read` privileges
for the {ml-features} in the appropriate spaces (if you use {kib})
* [ ] `read` and `view_index_metadata` index privileges on source indices
* [ ] `read` index privileges on destination indices (for {dfanalytics-jobs}
only)

To _manage_ {ml-features}, you must have:

[%interactive]
* [ ] `machine_learning_admin` built-in role (if you use {es} {ml} APIs)
* [ ] `kibana_admin` built-in role or a custom role that has `all` privileges
for the {ml-features} in the appropriate spaces (if you use {kib})
* [ ] `read` and `view_index_metadata` index privileges on source indices
* [ ] `read`, `manage`, and `index` index privileges on destination indices (for
  {dfanalytics-jobs} only)

If you use the *File Data Visualizer* to upload files in {kib}, you must have:

[%interactive]
* [ ] `kibana_admin` built-in role or a custom role that has `all` privileges
for the {ml-features} in the appropriate spaces
* [ ] `monitor` and `manage_ingest_pipelines` cluster privileges
* [ ] `read`, `manage`, and `index` index privileges for the destination index
