[role="xpack"]
[[setup]]
== Set up {ml-features}
++++
<titleabbrev>Setup</titleabbrev>
++++

To use the {stack} {ml-features}, you must have the
{subscriptions}[appropriate license] and at least one <<ml-nodes,{ml} node>> in
your {es} cluster. If {stack} {security-features} are enabled, you must also
ensure your users have the <<setup-privileges,necessary privileges>>.

TIP: The fastest way to get started with {ml-features} is to
https://www.elastic.co/cloud/elasticsearch-service/signup[start a free 14-day
trial of {ess}] in the cloud.

[discrete]
[[ml-nodes]]
=== Machine learning nodes

To use {ml-features}, there must be at least one {ml} node in your cluster. A
{ml} node is a node that has `xpack.ml.enabled` and `node.ml` set to `true`,
which is the default behavior.

You can limit which nodes run resource-intensive activity related to {ml} jobs
by setting `node.ml` to `false` on some nodes. In that case, they can service
API requests but cannot run {ml} jobs. For more information, see
{ref}/modules-node.html#ml-node[Machine learning nodes].

[discrete]
[[setup-privileges]]
=== Security privileges

The {es} {security-features} provide `machine_learning_admin` and
`machine_learning_user` {ref}/built-in-roles.html[built-in roles] and
`manage_ml` and `monitor_ml` {ref}/security-privileges.html[cluster privileges].
These roles and privileges make it easier to control which users can manage or
view {ml} objects such as jobs, {dfeeds}, results, and model snapshots.

Some actions might require additional authority. For example, if you are viewing
the results of {anomaly-jobs}, you must also have `read` index privileges on the
index that stores the results. If you are creating {dfanalytics-jobs}, you must
have specific privileges with respect to the source and destination indices.
For more information, see the prerequisites for each
{ref}/ml-apis.html[{anomaly-detect} API] and
{ref}/ml-df-analytics-apis.html[{dfanalytics} API].
