[role="xpack"]
[[setup]]
== Set up {ml-features}
++++
<titleabbrev>Setup</titleabbrev>
++++

To use the {stack} {ml-features}, you must have the
{subscriptions}[appropriate license] and at least one <<ml-nodes,{ml} node>> in
your {es} cluster. If {stack} {security-features} are enabled, you must also
ensure your users have the <<setup-privileges,necessary privileges>>.

TIP: The fastest way to get started with {ml-features} is to
https://www.elastic.co/cloud/elasticsearch-service/signup[start a free 14-day
trial of {ess}] in the cloud.

[discrete]
[[ml-nodes]]
=== Machine learning nodes

To use {ml-features}, there must be at least one {ml} node in your cluster. A
{ml} node is a node that has `xpack.ml.enabled` and `node.ml` set to `true`,
which is the default behavior.

You can limit which nodes run resource-intensive activity related to {ml} jobs
by setting `node.ml` to `false` on some nodes. In that case, they can service
API requests but cannot run {ml} jobs. For more information, see
{ref}/modules-node.html#ml-node[Machine learning nodes].

[discrete]
[[setup-privileges]]
=== Security privileges

The {es} {security-features} provide built-in roles and privileges that make it
easier to control which users can manage or view {ml} objects such as jobs,
{dfeeds}, results, and model snapshots. 

To have view the configuration, status, and results of the {ml-features}, you
must have:

* `machine_learning_user` {ref}/built-in-roles.html[built-in role]
* `read` and `view_index_metadata`
{ref}/security-privileges.html#privileges-list-indices[index privileges] on the
indices that contain the source data
* `read` index privileges on the destination indices
(for {dfanalytics-jobs} only)

To manage {ml-features}, you must have:

* `machine_learning_admin` or `machine_learning_user`
{ref}/built-in-roles.html[built-in roles]
* `read` and `view_index_metadata` index privileges on the indices that
contain the source data
* `read`, `manage`, and `index` index privileges on the destination indices
(for {dfanalytics-jobs} only)

If you use {ml-features} in {kib}, you must also have:

* `kibana_user` built-in role or a custom role that
{kibana-ref}/xpack-security-authorization.html[grants access to {kib}]
* `monitor` and `manage_ingest_pipelines` cluster privileges and `read`,
`manage`, and `index` index privileges for the destination index when you upload
files to the *Data Visualizer*
* `monitor` cluster privilege and `monitor` index privilege for the
destination index when you use the *{dfanalytics-cap}* tab