[role="xpack"]
[[setup]]
== Set up {ml-features}
++++
<titleabbrev>Setup</titleabbrev>
++++

To use the {stack} {ml-features}, you must have the
{subscriptions}[appropriate license] and at least one <<ml-nodes,{ml} node>> in
your {es} cluster. If {stack} {security-features} are enabled, you must also
ensure your users have the <<setup-privileges,necessary privileges>>.

TIP: The fastest way to get started with {ml-features} is to
https://www.elastic.co/cloud/elasticsearch-service/signup[start a free 14-day
trial of {ess}] in the cloud.

[discrete]
[[ml-nodes]]
=== Machine learning nodes

To use {ml-features}, there must be at least one {ml} node in your cluster. A
{ml} node is a node that has `xpack.ml.enabled` and `node.ml` set to `true`,
which is the default behavior.

You can limit which nodes run resource-intensive activity related to {ml} jobs
by setting `node.ml` to `false` on some nodes. In that case, they can service
API requests but cannot run {ml} jobs. For more information, see
{ref}/modules-node.html#ml-node[Machine learning nodes].

[discrete]
[[setup-privileges]]
=== Security privileges

The {es} {security-features} provide {ref}/built-in-roles.html[built-in roles]
and {ref}/security-privileges.html[privileges] that make it easier to control
which users can manage or view {ml} objects such as jobs, {dfeeds}, results, and
model snapshots. 

To _view_ the configuration, status, and results of the {ml-features}, you
must have:

[%interactive]
* [ ] `machine_learning_user` or `machine_learning_admin` built-in roles
* [ ] `read` and `view_index_metadata` index privileges on source indices
* [ ] `read` index privileges on destination indices (for {dfanalytics-jobs}
  only)

To _manage_ {ml-features}, you must have:

[%interactive]
* [ ] `machine_learning_admin` built-in role
* [ ] `read` and `view_index_metadata` index privileges on source indices
* [ ] `read`, `manage`, and `index` index privileges on destination indices (for
  {dfanalytics-jobs} only)

If you use {ml-features} in {kib}, you must also have:

[%interactive]
* [ ] `kibana_admin` built-in role or a custom role that
{kibana-ref}/xpack-security-authorization.html[grants access to {kib}]
* [ ] `monitor` cluster privilege to manage {dfanalytics-jobs}
* [ ] `monitor` and `manage_ingest_pipelines` cluster privileges when you upload
files in the *Data Visualizer*
* [ ] `read`, `manage`, and `index` index privileges for the destination index
when you upload files in the *Data Visualizer*

[discrete]
==== Alternative layout

If {stack} {security-features} are enabled, the following roles and privileges
are required to use {ml-features}:

|===
2+| Required roles or privileges | Description

.2+| Built-in role | `machine_learning_admin` | Required to manage {ml-features}

| `machine_learning_user` | Minimal authority necessary to view {ml}
configuration, status, and results.

.3+| Index privileges | `read` and `view_index_metadata` | Required on source
indices to manage {dfanalytics-jobs}

| `read`, `manage`, and `index` | Required on destination indices to manage
{dfanalytics-jobs} 

| `read` | Required on destination indices to view the results of
{dfanalytics-jobs} 

|===

There are additional authorization requirements when you use {ml-features} in
{kib}:

|===
2+| Required roles or privileges | Description

.2+| Cluster privileges | `monitor` and `manage_ingest_pipelines` | Required to
upload files to the *Data Visualizer*

| `monitor` | Required to manage {dfanalytics-jobs}

| Index privileges | `read`, `manage`, and `index` | Required on
destination indices to upload files to the *Data Visualizer*

|===