[[ml-nlp-limitations]]
= Limitations

:frontmatter-description: List of limitations of the Elastic NLP features.
:frontmatter-tags-products: [ml] 
:frontmatter-tags-content-type: [troubleshooting] 
:frontmatter-tags-user-goals: [analyze]

The following limitations and known problems apply to the {version} release of 
the Elastic {nlp} trained models feature.

[discrete]
[[ml-nlp-elser-v1-limit-512]]
== ELSER semantic search is limited to 512 tokens per field that inference is applied to

When you use ELSER for semantic search, only the first 512 extracted tokens from 
each field of the ingested documents that ELSER is applied to are taken into 
account for the search process. If your data set contains long documents, divide 
them into smaller segments before ingestion if you need the full text to be 
searchable.


[discrete]
[[ml-nlp-elser-autoscale]]
== ELSER deployments don't autoscale

Currently, ELSER deployments do not scale up and down automatically depending on
the resource requirements of the ELSER processes. If you want to configure
available resources for your ELSER deployments, you can manually set the number
of allocations and threads per allocation by using the Trained Models UI in
{kib} or the 
{ref}/update-trained-model-deployment.html[Update trained model deployment API].