[role="xpack"]
[[ml-dfa-limitations]]
== {dfanalytics-cap} limitations
[subs="attributes"]
++++
<titleabbrev>Limitations</titleabbrev>
++++

experimental[]

The following limitations and known problems apply to the {version} release of 
the Elastic {dfanalytics} feature:

[float]
[[dfa-ccs-limitations]]
=== {ccs-cap} is not supported

{ccs-cap} is not supported for {dfanalytics}.

[float]
[[dfa-deletion-limitations]]
=== Deleting a {dfanalytics-job} does not delete the destination index

The {ref}/delete-dfanalytics.html[delete {dfanalytics-job} API] does not delete
the destination index that contains the annotated data of the {dfanalytics}. 
That index must be deleted separately.

[float]
[[dfa-update-limitations]]
=== {dfanalytics-jobs-cap} cannot be updated

You cannot update {dfanalytics-cap} configurations. Instead, delete the 
{dfanalytics-job} and create a new one.

[float]
[[dfa-dataframe-size-limitations]]
=== {dataframe-cap} memory limitation

{dfanalytics-cap} can analyze {dataframes} that fit into the memory limit 
dedicated for {ml} processes. For general {ml} settings, see 
{ref}/ml-settings.html[{ml-cap} settings in {es}].

[float]
[[dfa-time-limitations]]
=== {dfanalytics-jobs-cap} runtime may be vary

The runtime of the {dfanalytics-jobs} depends on numerous factors, such as the 
size of the dataset, the analytics type, the number of fields that are included 
in the analysis, the used hyperparameters, and so on. For this reason, a 
general runtime value that applies to all or most of the situations does not 
exist. The runtime of a {dfanalytics-job} may take from a couple of minutes up 
to tens of hours in extreme cases.

[float]
[[dfa-missing-fields-limitations]]
=== Documents with missing values in analyzed fields are skipped

If there are missing values in feature fields (fields that are subjects of the 
{dfanalytics}), then the document that contains the fields with the missing 
values will be skipped during the analysis.

[float]
[[dfa-od-field-type-docs-limitations]]
=== {oldetection-cap} field types

{oldetection-cap} requires numeric or boolean data to analyze. The algorithms 
don't support missing values (see also <<dfa-missing-fields-limitations>>), 
therefore fields that have data types other than numeric or boolean are ignored. 
Documents where included fields contain missing values, null values, or an array 
are also ignored. Therefore a destination index may contain documents that don't 
have an {olscore}. These documents are still reindexed from the source index to 
the destination index, but they are not included in the {oldetection} analysis 
and therefore no {olscore} is computed.

[float]
[[dfa-regression-field-type-docs-limitations]]
=== {regression-cap} field types

{regression-cap} supports fields that are numeric, boolean, text, keyword and 
ip. It is also tolerant of missing values. Fields that are supported are 
included in the analysis, other fields are ignored. Documents where included 
fields contain an array are also ignored. Documents in the destination index 
that don't contain a results field are not included in the {reganalysis}.

[float]
[[dfa-classification-field-type-docs-limitations]]
=== {classification-cap} field types

{classification-cap} supports fields that have numeric, boolean, text, keyword, 
or ip data types. It is also tolerant of missing values. Fields that are supported are 
included in the analysis, other fields are ignored. Documents where included 
fields contain an array are also ignored. Documents in the destination index 
that don't contain a results field are not included in the {classanalysis}.
