[role="xpack"]
[[ml-feature-encoding]]
= Feature encoding

{ml-cap} models can only work with numerical values. For this reason, it is 
necessary to transform the categorical values of the relevant features into 
numerical ones. This process is called _feature encoding_.

{dfanalytics-cap} automatically performs feature encoding. The input data is 
pre-processed with the following encoding techniques:

* one-hot encoding: Assigns vectors to each category. The vector represent 
  whether the corresponding feature is present (1) or not (0).

* target-mean encoding: Replaces categorical values with the mean value of the 
  target variable.
  
* frequency encoding: Takes into account how many times a given categorical 
  value is present in relation with a feature.

When the model makes predictions on new data, the data needs to be processed in 
the same way it was trained. {ml-cap} model <<ml-inference,inference>> in the 
{stack} does this automatically, so the automatically applied encodings are used 
in each call for inference.

<<ml-feature-importance>> is calculated for the original categorical fields, not 
the automatically encoded features.