[role="xpack"]
[[ml-feature-importance]]
=== {feat-imp-cap}

{feat-imp-cap} values indicate which fields had the biggest impact on each 
prediction that is generated by <<dfa-classification,{classification}>> or 
<<dfa-regression,{regression}>> analysis. This value provides further insight 
into the results of a {dfanalytics-job} and therefore helps interpret these 
results. There are multiple features of a data point that are analyzed during 
{dfanalytics}. These features are responsible for a particular prediction to 
varying degrees. {feat-imp-cap} shows to what degree a given feature of a data 
point contributes to the prediction. The {feat-imp} value of a feature can be 
either positive or negative depending on its effect on the prediction. If the 
feature reduces the prediction value, the value is negative. If the feature 
increases the prediction, the {feat-imp} value positive. The magnitude of the 
{feat-imp} value shows how significantly the feature affects the prediction both 
locally (for a given data point) or generally (for the whole data set).

{feat-imp-cap} in the {stack} is calculated using the SHAP (SHapley Additive 
exPlanations) method as described in
https://papers.nips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions.pdf[Lundberg, S. M., & Lee, S.-I. A Unified Approach to Interpreting Model Predictions. In NeurIPS 2017].

By default, {feat-imp} values are not calculated when you configure the job via 
the API. To generate this information, when you create a {dfanalytics-job} you 
must specify the `num_top_feature_importance_values` property. When you 
configure the job in {kib}, {feat-imp} values are calculated automatically by 
using the default value of 2 for `num_top_feature_importance_values`. The 
{feat-imp} values are stored in the {ml} results field for each document in the 
destination index.

NOTE: The number of {feat-imp} values for each document might be less than the 
`num_top_feature_importance_values` property value. For example, it returns only 
features that had a positive or negative effect on the prediction.

[discrete]
==== Further readings

https://www.elastic.co/blog/feature-importance-for-data-frame-analytics-with-elastic-machine-learning[{feat-imp-cap} for {dfanalytics} with Elastic {ml}]
