
[discrete]
[[e-glos]]
=== E

[[glossary-edge]] edge::
A connection between nodes in a graph that shows that they are related. The line
weight indicates the strength of the relationship.  See
{kibana-ref}/xpack-graph.html[Graph].
//Source: Kibana

[[glossary-elastic-agent]] {agent}::
A single, unified way to add monitoring for logs, metrics, and other types of
data to a host. It can also protect hosts from security threats, query data from
operating systems, forward data from remote services or hardware, and more. See
{fleet-guide}/fleet-overview.html[{agent} overview].
//Source: Observability

[[glossary-ecs]] Elastic Common Schema (ECS)::
A document schema for Elasticsearch, for use cases such as logging and metrics.
ECS defines a common set of fields, their datatype, and gives guidance on their
correct usage. ECS is used to improve uniformity of event data coming from
different sources.

[[glossary-ems]] Elastic Maps Service (EMS)::
A service that provides basemap tiles, shape files, and other key features that
are essential for visualizing geospatial data.
//Source: Kibana

[[glossary-epr]] Elastic Package Registry (EPR)::
A service hosted by Elastic that stores Elastic package definitions in a central location.
See the https://github.com/elastic/package-registry[EPR GitHub repository].
//Source: Observability

[[glossary-element]] element::
A <<glossary-canvas,Canvas>> workpad object that displays an image, text, or
visualization.
//Source: Kibana

[[glossary-event]] event::
A single unit of information, containing a timestamp plus additional data. An
event arrives via an input, and is subsequently parsed, timestamped, and
passed through the {ls} <<glossary-pipeline,pipeline>>.
//Source: Logstash

[[glossary-eql]] Event Query Language (EQL)::
<<glossary-query,Query>> language for event-based time series data, such as
logs, metrics, and traces. EQL supports matching for event sequences. See
{ref}/eql.html[EQL].
//Source: Elasticsearch
