
[discrete]
[[g-glos]]
=== G

[[glossary-gem]] gem::
A self-contained package of code that's hosted on
https://rubygems.org[RubyGems.org]. {ls} <<glossary-plugin,plugins>> are
packaged as Ruby Gems. You can use the {ls}
<<glossary-plugin-manager,plugin manager>> to manage {ls} gems.
//Source: Logstash

[[glossary-geojson]] GeoJSON::
A format for representing geospatial data. GeoJSON is also a file-type, commonly
used in the *Maps* application to upload a file of geospatial data. See
{kibana-ref}/indexing-geojson-data-tutorial.html[GeoJSON data].
//Source: Kibana

[[glossary-geo-point]] geo-point::
A field type in {es}. A geo-point field accepts latitude-longitude pairs for
storing point locations. The latitude-longitude format can be from a string,
geohash, array, well-known text, or object. See {ref}/geo-point.html[geo-point].
//Source: Kibana

[[glossary-geo-shape]] geo-shape::
A field type in {es}. A geo-shape field accepts arbitrary geographic primitives,
like polygons, lines, or rectangles (and more). You can populate a geo-shape
field from GeoJSON or well-known text. See {ref}/geo-shape.html[geo-shape].
//Source: Kibana

[[glossary-graph]] graph::
A data structure and visualization that shows interconnections between a set of
entities. Each entity is represented by a node. Connections between nodes are
represented by <<glossary-edge,edges>>. See {kibana-ref}/xpack-graph.html[Graph].
//Source: Kibana

[[glossary-grok-debugger]] Grok Debugger::
A tool for building and debugging grok patterns. Grok is good for parsing syslog,
Apache, and other webserver logs. See
{kibana-ref}/xpack-grokdebugger.html[Debugging grok expressions].
//Source: Kibana
