
[discrete]
[[h-glos]]
=== H

[[glossary-heat-map]] heat map::
A layer type in the *Maps* application. Heat maps cluster locations to show
higher (or lower) densities. Heat maps describe a visualization with color-coded
cells or regions to analyze patterns across multiple dimensions. See
{kibana-ref}/heatmap-layer.html[Heat map layer].
//Source: Kibana

[[glossary-hidden-index]] hidden data stream or index::
<<glossary-data-stream,Data stream>> or <<glossary-index,index>> excluded from
most <<glossary-index-pattern,index patterns>> by default. See
{ref}/api-conventions.html#multi-hidden[Hidden data streams and indices].
//Source: Elasticsearch

[[glossary-hot-phase]] hot phase::
First possible phase in the <<glossary-index-lifecycle,index lifecycle>>. In
the hot phase, an <<glossary-index,index>> is actively updated and queried. See
{ref}/ilm-index-lifecycle.html[Index lifecycle].
//Source: Elasticsearch

[[glossary-hot-thread]] hot thread::
A Java thread that has high CPU usage and executes for a longer than normal
period of time.
//Source: Logstash

[[glossary-hot-tier]] hot tier::
<<glossary-data-tier,Data tier>> that contains <<glossary-node,nodes>> that
handle the <<glossary-index,indexing>> load for time series data, such as logs or
metrics. This tier holds your most recent, most frequently accessed data. See
{ref}/data-tiers.html[Data tiers].
//Source: Elasticsearch
