
[discrete]
[[i-glos]]
=== I

[[glossary-id]] ID::
Identifier for a <<glossary-document,document>>. Document IDs must be unique
within an <<glossary-index,index>>. See the {ref}/mapping-id-field.html[`_id`
field].
//Source: Elasticsearch

[[glossary-index]] index::
. Collection of JSON <<glossary-document,documents>>. See
{ref}/documents-indices.html[Documents and indices].
//Source: Elasticsearch
. To add one or more JSON documents to {es}. This process is called indexing.
//Source: Elasticsearch

[[glossary-index-lifecycle]] index lifecycle::
Five phases an <<glossary-index,index>> can transition through:
<<glossary-hot-phase,hot>>, <<glossary-warm-phase,warm>>,
<<glossary-cold-phase,cold>>, <<glossary-frozen-phase,frozen>>,
and <<glossary-delete-phase,delete>>. See {ref}/ilm-policy-definition.html[Index
lifecycle].
//Source: Elasticsearch

[[glossary-index-lifecycle-policy]] index lifecycle policy::
Specifies how an <<glossary-index,index>> moves between phases in the
<<glossary-index-lifecycle,index lifecycle>> and what actions to perform during
each phase. See {ref}/ilm-policy-definition.html[Index lifecycle].
//Source: Elasticsearch

[[glossary-index-pattern]] index pattern::
In {es}, a string containing a wildcard (`*`) pattern that can match multiple
<<glossary-data-stream,data streams>>, <<glossary-index,indices>>, or
<<glossary-alias,aliases>>. See {ref}/multi-index.html[Multi-target syntax].
//Source: Elasticsearch

[[glossary-index-template]] index template::
Automatically configures the <<glossary-mapping,mappings>>,
{ref}/index-modules.html[index settings], and <<glossary-alias,aliases>>
of new <<glossary-index,indices>> that match its <<glossary-index-pattern,index
pattern>>. You can also use index templates to create
<<glossary-data-stream,data streams>>. See {ref}/index-templates.html[Index
templates].
//Source: Elasticsearch

[[glossary-indexer]] indexer::
A {ls} instance that is tasked with interfacing with an {es} cluster in
order to index <<glossary-event,event>> data.
//Source: Logstash

[[glossary-inference]] inference::
A {ml} feature that enables you to use supervised learning processes – like
{classification}, {regression}, or <<glossary-nlp,{nlp}>> – in a continuous
fashion by using <<glossary-trained-model,trained models>> against incoming data.
//Source: Machine learning

[[glossary-inference-aggregation]] inference aggregation::
A pipeline aggregation that references a <<glossary-trained-model>> in an
aggregation to infer on the results field of the parent bucket aggregation. It
enables you to use supervised {ml} at search time.
//Source: Machine learning

[[glossary-inference-processor]] inference processor::
A processor specified in an ingest pipeline that uses a
<<glossary-trained-model>> to infer against the data that is being ingested in
the pipeline.
//Source: Machine learning

[[glossary-influencer]] influencer::
Influencers are entities that might have contributed to an anomaly in a specific
bucket in an {anomaly-job}. For more information, see
{ml-docs}/ml-influencers.html[Influencers].
//Source: Machine learning

[[glossary-ingestion]] ingestion::
The process of collecting and sending data from various data sources to {es}.
//Source: Observability

[[glossary-input-plugin]] input plugin::
A {ls} <<glossary-plugin,plugin>> that reads <<glossary-event,event>> data
from a specific source. Input plugins are the first stage in the {ls}
event processing <<glossary-pipeline,pipeline>>. Popular input plugins include
file, syslog, redis, and beats.
//Source: Logstash

[[glossary-instrumentation]] instrumentation::
Extending application code to track where your application is spending time.
Code is considered instrumented when it collects and reports this performance data to APM.
//Source: Observability

[[glossary-integration]] integration::

An easy way for external systems to connect to the {stack}.
Whether it's collecting data or protecting systems from security threats,
integrations provide out-of-the-box assets to make setup easy--many with just a single click.
//Source: Observability

[[glossary-integration-policy]] integration policy::
An instance of an <<glossary-integration,integration>> that is configured for a specific use case,
such as collecting logs from a specific file.
//Source: Observability
