
[discrete]
[[l-glos]]
=== L

[[glossary-labs]] labs::
An in-progress or experimental feature in *Canvas* or *Dashboard* that you can
try out and provide feedback. When enabled, you’ll see *Labs* in the toolbar.
//Source: Kibana

[[glossary-leader-index]] leader index::
Source <<glossary-index,index>> for <<glossary-ccr,{ccr}>>. A leader index
exists on a <<glossary-remote-cluster,remote cluster>> and is replicated to
<<glossary-follower-index,follower indices>>. See
{ref}/xpack-ccr.html[{ccr-cap}].
//Source: Elasticsearch

[[glossary-lens]] Lens::
Enables you to build visualizations by dragging and dropping data fields. Lens
makes makes smart visualization suggestions for your data, allowing you to
switch between visualization types. See {kibana-ref}/dashboard.html[Lens].
//Source: Kibana

[[glossary-local-cluster]] local cluster::
<<glossary-cluster,Cluster>> that pulls data from a
<<glossary-remote-cluster,remote cluster>> in <<glossary-ccs,{ccs}>> or
<<glossary-ccr,{ccr}>>. See {ref}/modules-remote-clusters.html[Remote clusters].
//Source: Elasticsearch

[[glossary-lucene]] Lucene query syntax::
The query syntax for {kib}’s legacy query language. The Lucene query syntax is
available under the options menu in the query bar and from
<<glossary-advanced-settings,Advanced Settings>>.
//Source: Kibana
