
[discrete]
[[m-glos]]
=== M

[[glossary-ml-nodes]] machine learning node::
A {ml} node is a node that has `xpack.ml.enabled` set to `true` and `ml` in `node.roles`.
If you want to use {ml-features}, there must be at least one {ml} node in your
cluster. See {ref}/modules-node.html#ml-node[Machine learning nodes].
//Source: Machine learning

[[glossary-map]] map::
A representation of geographic data using symbols and labels. See
{kibana-ref}/maps.html[Maps].
//Source: Kibana

[[glossary-mapping]] mapping::
Defines how a <<glossary-document,document>>, its <<glossary-field,fields>>, and
its metadata are stored in {es}. Similar to a schema definition. See
{ref}/mapping.html[Mapping].
//Source: Elasticsearch

[[glossary-master-node]] master node::
Handles write requests for the cluster and publishes changes to other nodes in
an ordered fashion. Each cluster has a single master node which is chosen
automatically by the cluster and is replaced if the current master node fails.
Also see <<glossary-node,node>>.
//Source: Cloud

[[glossary-merge]] merge::
Process of combining a <<glossary-shard,shard>>'s smaller Lucene
<<glossary-segment,segments>> into a larger one. {es} manages merges
automatically.
//Source: Elasticsearch

[[glossary-message-broker]] message broker::
Also referred to as a _message buffer_ or _message queue_, a message broker is
external software (such as Redis, Kafka, or RabbitMQ) that stores messages
from the {ls} shipper instance as an intermediate store, waiting to be
processed by the {ls} indexer instance.
//Source: Logstash

[[glossary-metric-aggregation]] metric aggregation::
An aggregation that calculates and tracks metrics for a set of documents.
//Source: Kibana

[[glossary-metadata]] @metadata::
A special field for storing content that you don't want to include in output
<<glossary-event,events>>. For example, the `@metadata` field is useful for
creating transient fields for use in <<glossary-conditional,conditional>>
statements.
//Source: Logstash

[[glossary-module]] module::
Out-of-the-box configurations for common data sources to simplify the collection,
parsing, and visualization of logs and metrics.
//Source: Observability

[[glossary-monitor]] monitor::
A network endpoint which is monitored to track the performance and availability of
applications and services.
//Source: Observability

[[glossary-multi-field]] multi-field::
A <<glossary-field,field>> that's <<glossary-mapping,mapped>> in multiple ways.
See the {ref}/multi-fields.html[`fields` mapping parameter].
//Source: Elasticsearch
