
[discrete]
[[t-glos]]
=== T

[[glossary-timelion]] Timelion::
A tool for building a time series visualization that analyzes data in time order.
See {kibana-ref}/dashboard.html[Timelion].
//Source: Kibana

[[glossary-time-series-data]] time series data::
A series of data points, such as logs, metrics and events, that is indexed in
time order. Time series data can be indexed in a 
<<glossary-data-stream,data stream>>, where it can be accessed as a single named
resource with the data stored across multiple backing indices. A
<<glossary-time-series-data-stream,time series data stream>> is optimized for
indexing metrics data.
//Source: Elasticsearch

[[glossary-time-series-data-stream]] time series data stream::
A type of <<glossary-data-stream,data stream>> optimized for indexing metrics
<<glossary-time-series-data,time series data>>. A TSDS allows for reduced storage
size and for a sequence of metrics data points to be considered efficiently as a
whole. See {ref}/tsds.html[Time series data stream].
//Source: Elasticsearch

[[glossary-token]] token::
A chunk of unstructured <<glossary-text,text>> that's been optimized for search.
In most cases, tokens are individual words. Tokens are also called terms. See
{ref}/analysis.html[Text analysis].
//Source: Elasticsearch

[[glossary-tokenization]] tokenization::
Process of breaking unstructured text down into smaller, searchable chunks
called <<glossary-token,tokens>>. See
{ref}/analysis-overview.html#tokenization[Tokenization].
//Source: Elasticsearch

[[glossary-trace]] trace::
Defines the amount of time an application spends on a request.
Traces are made up of a collection of transactions and spans that have a common root.
//Source: Observability

[[glossary-tracks]] tracks::
A layer type in the *Maps* application. This layer converts a series of point
locations into a line, often representing a path or route.
//Source: Kibana

[[glossary-trained-model]] trained model::
A {ml} model that is trained and tested against a labeled data set and can be
referenced in an ingest pipeline or in a pipeline aggregation to perform
{classification} or {reganalysis} or <<glossary-nlp,{nlp}>> on new data.
//Source: Machine learning

[[glossary-transaction]] transaction::
A special kind of <<glossary-span,span>> that has additional attributes associated with it.
{apm-guide-ref}/data-model-transactions.html[Transactions] describe an event captured by an
Elastic <<glossary-apm-agent,APM agent>> instrumenting a service.
//Source: Observability

[[glossary-tsvb]] TSVB::
A time series data visualizer that allows you to combine an infinite number of
aggregations to display complex data. See {kibana-ref}/dashboard.html[TSVB].
//Source: Kibana
