
[discrete]
[[w-glos]]
=== W

[[glossary-warm-phase]] warm phase::
Second possible phase in the <<glossary-index-lifecycle,index lifecycle>>. In
the warm phase, an <<glossary-index,index>> is generally optimized for search
and no longer updated. See {ref}/ilm-policy-definition.html[Index lifecycle].
//Source: Elasticsearch

[[glossary-warm-tier]] warm tier::
<<glossary-data-tier,Data tier>> that contains <<glossary-node,nodes>> that hold
time series data that is accessed less frequently and rarely needs to be
updated. See {ref}/data-tiers.html[Data tiers].
//Source: Elasticsearch

[[glossary-watcher]] Watcher::
The original suite of alerting features. See
{kibana-ref}/watcher-ui.html[Watcher].
//Source: Kibana

[[glossary-wms]] Web Map Service (WMS)::
A layer type in the *Maps* application. Add a WMS source to provide
authoritative geographic context to your map. See the
https://www.ogc.org/standards/wms[OpenGIS Web Map Service].
//Source: Kibana

[[glossary-worker]] worker::
The filter thread model used by {ls}, where each worker receives an
<<glossary-event,event>> and applies all filters, in order, before emitting
the event to the output queue. This allows scalability across CPUs because
many filters are CPU intensive.
//Source: Logstash

[[glossary-workpad]] workpad::
A workspace where you build presentations of your live data in
<<glossary-canvas,Canvas>>. See {kibana-ref}/canvas.html[Create a workpad].
//Source: Kibana
