[[cases-api-overview]]
[role="xpack"]
== Cases API

The cases API is used to open action items about security issues for specific 
people.

The RESTful API endpoint is:

`<kibana URL>/api/cases`

Where `<kibana URL>` is the URL and port number of your Kibana instance.

NOTE: In dev mode, the Kibana server runs behind a proxy which adds a random 
path component to its URL.
{kibana-ref}/development-basepath.html[Considerations for basePath] describes 
how to work with and disable the random path component.

[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the API.

[float]
=== API calls

All calls to the API are stateless. Each call must include all the information {siem-soln} needs to perform the request.

All requests must contain these headers:

* `kbn-xsrf: <value>`, where `<value>` can be any alphanumeric string (for 
example, `kbn-xsrf: kibana`)
* `Content-Type: application/json` (when the request contains a JSON payload)

For example, the following call retrieves the first 20 cases:

[source,sh]
--------------------------------------------------
curl -X GET "<kibana URL>/api/cases"
-H 'kbn-xsrf: kibana' -u <username>:<password>
--------------------------------------------------