[[assign-connector]]
=== Set connector

Sets the default connector in the {siem-ui}.

Connectors are used to interface with external systems. You can only call this
method after you have created a connector (see <<register-connector>>). After a
connector has been created and assigned, call <<cases-actions-api-execute>> to
send cases to the external system.

==== Request URL

`POST <kibana host>/<port>/api/cases/configure`

==== Request body

A JSON object with these fields:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`connector_id` |String |The connector ID. |Yes
|`connector_name` |String |The connector name. |Yes
|`closure_type` |String a|Determines whether a case is automatically closed in
the {siem-app} when it is pushed to {sn}. Valid values are:

* `close-by-pushing`: {siem-app} cases are automatically closed when they
are pushed to {sn}.
* `close-by-user`: {siem-app} cases are not automatically closed.

|Yes
|==============================================

NOTE: Call <<cases-api-find-connectors>> to retrieve connector IDs and names.

==== Example request

[source,sh]
--------------------------------------------------
POST api/cases/configure
{
  "connector_id": "61787f53-4eee-4741-8df6-8fe84fa616f7",
  "closure_type": "close-by-user",
  "connector_name": "ServiceNow"
}
--------------------------------------------------

==== Response code

`200`:: 
   Indicates a successful call.
   
==== Example response

[source,json]
--------------------------------------------------
{
  "connector_id": "61787f53-4eee-4741-8df6-8fe84fa616f7",
  "closure_type": "close-by-user",
  "connector_name": "ServiceNow",
  "created_at": "2020-03-30T13:31:38.083Z",
  "created_by": {
    "email": "moneypenny@hms.gov.uk",
    "full_name": "Ms Moneypenny",
    "username": "moneypenny"
  },
  "updated_at": null,
  "updated_by": null,
  "version": "WzE3NywxXQ=="
}
--------------------------------------------------
