[[cases-api-update]]
=== Update case

Updates existing cases.

==== Request URL

`PATCH <kibana host>:<port>/api/cases`

==== Request body

A JSON array containing one or more case objects with updated field values:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`cases` |<<update-cases-schema, cases[]>> |Array containing one or more case objects. |Yes
|==============================================

[[update-cases-schema]]
===== `cases` schema
|==============================================
|Name |Type |Description |Required

|`id` |String |The ID of the case being updated. |Yes
|`title` |String |The updated case title. |No
|`description` |String |The updated case description. |No
|`status` |String a|The updated case status, which can be:

* `open`
* `closed`

|No
|`tags` |String[] |The updated case tags. |No
|`version` |String |The current case version (returned when calling
<<cases-api-get-case>> or <<cases-api-find-cases>>). |Yes
|==============================================

===== Example request

Updates the `description` and `tags` fields of case ID
`a18b38a0-71b0-11ea-a0b2-c51ea50a58e2`:

[source,sh]
--------------------------------------------------
PATCH api/cases
{
  "cases": [
    {
      "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
      "description": "James Bond clicked on a highly suspicious email
      banner advertising cheap holidays for underpaid civil servants.
      Operation bubblegum is active. Repeat - operation bubblegum is
      now active!",
      "tags": [
        "phishing",
        "social engineering",
        "bubblegum"
      ],
      "version": "WzIzLDFd"
    }
  ]
}
--------------------------------------------------
// KIBANA

==== Response code

`200`:: 
   Indicates a successful call.

==== Response payload

The updated case with a new `version` value.

===== Example response

[source,json]
--------------------------------------------------
[
  {
    "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
    "version": "Wzk4LDFd",
    "comments": [],
    "totalComment": 0,
    "closed_at": null,
    "closed_by": null,
    "created_at": "2020-03-29T11:30:02.658Z",
    "created_by": {
      "email": "ahunley@imf.usa.gov",
      "full_name": "Alan Hunley",
      "username": "ahunley"
    },
    "external_service": null,
    "updated_at": "2020-03-29T12:01:50.244Z",
    "updated_by": {
      "email": "classified@hms.oo.gov.uk",
      "full_name": "Classified",
      "username": "M"
    },
    "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants. Operation bubblegum is active. Repeat - operation bubblegum is now active!",
    "title": "This case will self-destruct in 5 seconds",
    "status": "open",
    "tags": [
      "phishing",
      "social engineering",
      "bubblegum"
    ]
  }
]
--------------------------------------------------