[[cases-api-overview]]
[role="xpack"]
== Cases API

You can create, manage, configure, and send cases to external systems with
these APIs:

* Cases API: Used to open and manage security action items. The API endpoint is
`<kibana host>/<port>/api/cases`, where `<kibana URL>` is the host name and
`<port>` is the port number of your Kibana instance.

* Actions API: Used to send cases to external systems. The API endpoint
is `<kibana host>/<port>/api/actions`. <<cases-actions-api-connectors>>
describes how to set up integrations with third-party systems, and
<<cases-actions-api-execute>> describes how to push {siem-app} cases to third
party systems (currently, ServiceNow).

NOTE: In dev mode, the Kibana server runs behind a proxy which adds a random 
path component to its URL.
{kibana-ref}/development-basepath.html[Considerations for basePath] describes 
how to work with and disable the random path component.

[float]
=== {kib} space API calls

Cases are created and managed per {kib} space. If you are making calls to a
{kib} space *other than* the `Default` space, the space identifier is part of 
the endpoint's URL:

`<kibana host>:<port>/s/<space URL>/api/cases`

Where `<space URL>` is the URL identifier for the space.

NOTE: You can find space URL identifiers on
{kibana-ref}/xpack-spaces.html[*Edit space*] pages (Management -> Spaces -> 
<space name>) or by calling
{kibana-ref}/spaces-api-get-all.html[`GET /api/spaces/space`].

[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the API.

[float]
=== API calls

All calls to the API are stateless. Each call must include all the information
{siem-soln} needs to perform the request.

All requests must contain these headers:

* `kbn-xsrf: <value>`, where `<value>` can be any alphanumeric string (for 
example, `kbn-xsrf: kibana`)
* `Content-Type: application/json` (when the request contains a JSON payload)

For example, the following call retrieves the first 20 cases:

[source,sh]
--------------------------------------------------
curl -X GET "<kibana host>/<port>/api/cases"
-H 'kbn-xsrf: kibana' -u <username>:<password>
--------------------------------------------------