[[cases-api-update]]
=== Update case

Updates existing cases.

==== Request URL

`PATCH /api/cases`

==== Request body

A JSON array containing one or more case objects with updated field values:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`cases` |<<update-cases-schema, cases[]>> |Array containing one or more case objects. |Yes
|==============================================

[[update-cases-schema]]
===== `cases` schema
|==============================================
|Name |Type |Description |Required

|`id` |String |The case ID of the case being updated. |Yes
|`title` |String |The updated case title. |No
|`description` |String |The updated case description. |No
|`state` |String a|The updated case status, which can be:

* `open`
* `closed`

|No
|`tags` |String[] |The updated case tags. |No
|`version` |String |The current case version (returned when calling
<<cases-api-get-case>> or <<cases-api-find-cases>>) |Yes
|==============================================

===== Example request

Updates the `description` and `tags` fields of case ID
`eb696730-66a2-11ea-be1b-2bd3fef48984`:

[source,sh]
--------------------------------------------------
PATCH api/cases
{
  "cases": [
    {
      "id": "eb696730-66a2-11ea-be1b-2bd3fef48984",
      "description": "James Bond clicked on a highly suspicious email
      banner advertising cheap holidays for underpaid civil servants.
      Operation bubblegum is active. Repeat - operation bubblegum is
      now active!",
      "tags": [
        "phishing",
        "social engineering",
        "bubblegum"
      ],
      "version": "WzIzLDFd"
    }
  ]
}
--------------------------------------------------
// KIBANA

==== Response code

`200`:: 
   Indicates a successful call.

==== Response payload

The updated case with a new `version` value.

===== Example response

[source,json]
--------------------------------------------------
[
  {
    "id": "eb696730-66a2-11ea-be1b-2bd3fef48984",
    "version": "WzI0LDFd",
    "comments": [],
    "comment_ids": [
      "35180680-66a7-11ea-be1b-2bd3fef48984"
    ],
    "created_at": "2020-03-15T09:54:10.654Z",
    "created_by": {
      "full_name": "Alan Hunley",
      "username": "ahunley"
    },
    "updated_at": "2020-03-15T10:39:02.360Z",
    "updated_by": {
      "full_name": "Classified",
      "username": "M"
    },
    "description": "James Bond clicked on a highly suspicious email
    banner advertising cheap holidays for underpaid civil servants.
    Operation bubblegum is active. Repeat - operation bubblegum is
    now active!",
    "title": "This case will self-destruct in 5 seconds",
    "status": "open",
    "tags": [
      "phishing",
      "social engineering",
      "bubblegum"
    ]
  }
]
--------------------------------------------------