[[cases-api-find-cases]]
=== Find cases

Retrieves a paginated subset of cases. By default, the first page is returned 
with 20 results per page.

==== Request URL

`GET /api/cases/_find`

===== URL query parameters

All parameters are optional:

[width="100%",options="header"]
|==============================================
|Name |Type |Description

|`page` |Integer |The page number to return.

|`perPage` |Integer |The number of rules to return per page.

|`sortField` |String |Determines which field is used to sort the results,
`createdAt` or `updatedAt`.

|`sortOrder` |String |Determines the sort order, which can be `desc` or `asc`.

|`status` |String |Filters the returned cases by state, which can be `open` or
`closed`.

|`tags` |String |Filters the returned cases by tags.

|==============================================

NOTE: Even though the JSON case object uses `created_at` and `updated_at`
fields, you must use `createdAt` and `updatedAt` fields in the URL
query.

===== Example request

Retrieves the first five cases with the `phishing` tag, in ascending order by 
last update time.

[source,sh]
--------------------------------------------------
GET api/cases/_find?page=1&perPage=5&sortField=updatedAt&sortOrder=asc&tags=phishing
--------------------------------------------------
// KIBANA

==== Response code

`200`:: 
   Indicates a successful call.

==== Response payload

A JSON object listing all cases.

===== Response example

[source,json]
--------------------------------------------------
{
  "page": 1,
  "per_page": 5,
  "total": 2,
  "cases": [
    {
      "id": "eb696730-66a2-11ea-be1b-2bd3fef48984",
      "version": "WzI0LDFd",
      "comments": [],
      "comment_ids": [
        "35180680-66a7-11ea-be1b-2bd3fef48984"
      ],
      "created_at": "2020-03-15T09:54:10.654Z",
      "created_by": {
        "full_name": "Alan Hunley",
        "username": "ahunley"
      },
      "updated_at": "2020-03-15T10:39:02.360Z",
      "updated_by": {
        "full_name": "Classified",
        "username": "M"
      },
      "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants. Operation bubblegum is active. Repeat - operation bubblegum is now active",
      "title": "This case will self-destruct in 5 seconds",
      "status": "open",
      "tags": [
        "phishing",
        "social engineering",
        "bubblegum"
      ]
    },
    {
      "id": "2e3a54f0-6754-11ea-a1c2-e3a8bc9f7aca",
      "version": "WzM2LDFd",
      "comments": [],
      "comment_ids": [],
      "created_at": "2020-03-16T07:03:03.648Z",
      "created_by": {
        "full_name": "Rat Hustler",
        "username": "rhustler"
      },
      "updated_at": "2020-03-16T07:03:18.058Z",
      "updated_by": {
        "full_name": "Rat Hustler",
        "username": "rhustler"
      },
      "title": "The Long Game",
      "tags": [
        "windows",
        "phishing"
      ],
      "description": "Windows 95",
      "status": "closed"
    }
  ],
  "count_open_cases": 1,
  "count_closed_cases": 1
}
--------------------------------------------------