[[detection-engine-overview]]
[role="xpack"]
= Detection Engine

[partintro]
--

//Ben: placeholder
The detection engine automatically searches for threats and creates signals 
when they are detected. These threats are detected using rules that define the 
conditions required for a signal to be issued. The {siem-app} comes 
preconfigured with rules that search for suspicious activity on your network 
and hosts. Additionally, to meet your specific requirements,
you can <<rules-ui-create, create your own rules>>.

[float]
== Signals
*Ben: check with Garrett*
When a rule's criteria is matched, a signal is produced and displayed on the 
Detection Engine page. To view all signals created by a specific rule, click 
*Manage rules* and then the relevant rule in the All rules table.

[float]
== Rule activity
*Ben: check with Garrett*
To see whether a rule is active, when it last ran, and how far back it searched 
for signals, view the Activity monitor table (*Manage rules* ->
*Activity monitor*).

[float]
== Terminology

To ensure all terms are well-defined:

Signals::
Alway refer to a {siem-soln} produced detection. That is, signals are never 
received from third-party systems. When a detection engine rule's conditions 
are met, the {siem-app} writes one or more signals to an Elasticsearch 
`signals` index.

Alerts and events::
Always refer to data and detections {siem-soln} receives from data shippers and 
third-party tools, such as Suricata and Elastic Endpoint Security.

--