[[index-api-overview]]
[role="xpack"]
=== Index endpoint

You use the index endpoint to create, get, delete a signal index in a {kib} 
space.

You can only create a signal index when:

NOTE: When a rule's criteria is met, a document is created and stored in the 
signal index.

[float]
==== Create index

Creates a signal index.

[float]
===== Request URL

`POST  /api/detection_engine/index`

[float]
====== Example request

Creates a signal index in the {kib} `siem` space. The naming convention for the 
index is `.siem-signals-<space name>-*`.

[source, js]
--------------------------------------------------
POST /s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

[float]
===== Response code

`200`:: 
    Indicates a successful call.

[float]
==== Get index

Gets the signal index name for the {kib} space if it exists.

[float]
===== Request URL

`POST /api/detection_engine/index`

[float]
====== Example request

Gets the signal index for the {kib} `siem` space.

[source, js]
--------------------------------------------------
GET /s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

[float]
===== Response code

`200`:: 
    Indicates a successful call.
`404`::
    Indicates no index exists.
    
[float]
====== Example responses

Example response when index exists:

[source,json]
--------------------------------------------------
{
  "name": ".siem-signals-siem"
}
--------------------------------------------------

Example response when no index exists:

[source,json]
--------------------------------------------------
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "index for this space does not exist"
}
--------------------------------------------------