[[index-api-overview]]
[role="xpack"]
=== Index endpoint

You use the index endpoint to create, get, delete a signal index in a {kib} 
space.

You can only create a signal index when the user role has `manage` privileges 
for both the {ref}/security-privileges.html[{es} cluster and the signals index].

NOTE: To make sure administrators can always create indices, in the `Indices` 
field on the *Create role* page use a glob pattern to match indices from 
multiple spaces (*Management* -> *Roles* -> *Create role*). For example, `.siem-
signals-*`.

[float]
==== Create index

Creates a signal index.

[float]
===== Request URL

`POST  /api/detection_engine/index`

[float]
====== Example request

Creates a signal index in the {kib} `siem` space. The naming convention for the 
index is `.siem-signals-<space name>-*`.

[source, js]
--------------------------------------------------
POST /s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

[float]
===== Response code

`200`:: 
    Indicates a successful call.

[float]
==== Get index

Gets the signal index name if it exists.

[float]
===== Request URL

`GET /api/detection_engine/index`

[float]
====== Example request

Gets the signal index for the {kib} `siem` space.

[source, js]
--------------------------------------------------
GET /s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

[float]
===== Response code

`200`:: 
    Indicates a successful call.
`404`::
    Indicates no index exists.
    
[float]
====== Example responses

Example response when index exists:

[source,json]
--------------------------------------------------
{
  "name": ".siem-signals-siem"
}
--------------------------------------------------

Example response when no index exists:

[source,json]
--------------------------------------------------
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "index for this space does not exist"
}
--------------------------------------------------

[float]
==== Delete index

Deletes the signal index.

[float]
===== Request URL

`DELETE /api/detection_engine/index`

[float]
====== Example request

Deletes the signal index for the {kib} `siem` space.

[source, js]
--------------------------------------------------
DELETE /s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

[float]
===== Response code

`200`:: 
    Indicates a successful call.