[[prebuilt-rules]]
[role="xpack"]
=== Prebuilt rule reference

// Imported via script - needs work

The following prebuilt rules are available:

403 Response to a POST:: 403 Response to a POST

405 Response (Method Not Allowed):: 405 Response (Method Not Allowed)

500 Response on Admin page:: 500 Response on Admin page

Adding the Hidden File Attribute with via attrib.exe:: Adversaries can add the 'hidden' attribute to files to hide them from the user in an attempt to evade detection

Adobe Hijack Persistence:: Detects writing executable files that will be automatically launched by Adobe on launch.

Audio Capture via PowerShell:: An adversary can leverage a computer's peripheral devices or applications to capture audio recordings for the purpose of listening into sensitive conversations to gather information.

Audio Capture via SoundRecorder:: An adversary can leverage a computer's peripheral devices or applications to capture audio recordings for the purpose of listening into sensitive conversations to gather information.

Bypass UAC via CMSTP:: Identifies User Account Control (UAC) bypass via cmstp.  Attackers bypass UAC to stealthily execute code with elevated permissions.

Bypass UAC via Event Viewer:: Identifies User Account Control (UAC) bypass via eventvwr.  Attackers bypass UAC to stealthily execute code with elevated permissions.

Bypass UAC via SDCLT:: Identifies User Account Control (UAC) bypass via cmstp.  Attackers bypass UAC to stealthily execute code with elevated permissions.

Clearing Windows Event Logs:: Identifies attempts to clear Windows event log stores. This is often done by attackers in an attempt evade detection or destroy forensic evidence on a system.

Command shell started by Internet Explorer:: Command shell started by Internet Explorer

Command shell started by Powershell:: Command shell started by Powershell

Command shell started by Svchost:: Command shell started by Svchost

DLL Search Order Hijack:: Detects writing DLL files to known locations associated with Windows files vulnerable to DLL search order hijacking.

Delete Volume USN Journal with fsutil:: Identifies use of the fsutil command to delete the volume USNJRNL. This technique is used by attackers to eliminate evidence of files created during post-exploitation activities.

Deleting Backup Catalogs with wbadmin:: Identifies use of the wbadmin command to delete the backup catalog. Ransomware and other malware may do this to prevent system recovery.

Direct Outbound SMB Connection:: Identifies unexpected processes making network connections over port 445. Windows File Sharing is typically implemented over Server Message Block (SMB), which communicates between hosts using port 445. When legitimate, these network connections are established by the kernel. Processes making 445/tcp connections may be port scanners, exploits, or suspicious user-level processes moving laterally.

Disable Windows Firewall Rules with Netsh:: Identifies use of the netsh command to disable or weaken the local firewall. Attackers will use this command line tool to disable the firewall during troubleshooting or to enable network mobility.

EQL - Suspicious PDF Reader Child Process:: Identifies suspicious child processes of PDF reader applications. These child processes are often launched via exploitation of PDF applications or social engineering.

Encoding or Decoding Files via CertUtil:: Identifies the use of certutil.exe to encode or decode data. CertUtil is a native Windows component which is part of Certificate Services. CertUtil is often abused by attackers to encode or decode base64 data for stealthier command and control or exfiltration.

Linux Network - Anomalous Process Using HTTP/S Ports:: Linux Network - Anomalous Process Using HTTP/S Ports

Linux ld.so process activity:: Linux ld.so process activity

Linux lzop activity:: Linux lzop activity - possible @JulianRunnels

Linux: Hping Activity:: Linux: Hping Activity

Linux: Iodine Activity:: Linux: Iodine Activity

Linux: Mknod Activity:: Linux: Mknod Activity

Linux: Netcat Network Activity:: Linux: Netcat Network Connection

Linux: Nmap Activity:: Linux: Nmap Activity

Linux: Nping Activity:: Linux: Nping Activity

Linux: Ptrace Activity:: Linux: Ptrace Activity

Linux: Rawshark Activity:: Linux: Rawshark Activity

Linux: SSH Port Forwarding:: Detect ssh processes with the `-R` flag which can be used to forward a port on a local system to the local system so that someone on the remote system can connect to the local system. This is often used by attackers to create encrypted tunnels through firewalls for pivoting and persistence.

Linux: Shell Activity By Web Server:: Identifies suspicious commands executed via a web server, which may suggest a vulnerability and remote shell access.

Linux: Strace Activity:: Linux: Strace Activity

Linux: Tcpdump Activity:: Linux: Tcpdump Activity

Linux: User Discovery Via The Whoami Commmand:: The 'whoami' command was executed on a Linux host. This is often used by tools and persistence mechanisms to test for privlieged access.

Linux: Web Download:: Linux: Web Download

Linux: Whoami Commmand:: Linux: socat activity

Local Scheduled Task Commands:: A scheduled task can be used by an adversary to establish persistence, move laterally, and/or escalate privileges.

Local Service Commands:: Identifies use of sc.exe to create, modify, or start services on remote hosts. This could be indicative of adversary lateral movement but will be noisy if commonly done by admins.

Modification of Boot Configuration:: Identifies use of the bcdedit command to delete boot configuration data. This tactic is sometimes used as by malware or an attacker as a destructive technique.

MsBuild Making Network Connections:: Identifies MsBuild.exe making outbound network connections. This may indicate adversarial activity as MsBuild is often leveraged by adversaries to execute code and evade detection.

MsXsl Making Network Connections:: Identifies MsXsl.exe making outbound network connections. This may indicate adversarial activity as MsXsl is often leveraged by adversaries to execute malicious scripts and evade detection.

Mshta Making Network Connections:: Identifies Mshta.exe making outbound network connections. This may indicate adversarial activity as Mshta is often leveraged by adversaries to execute malicious scripts and evade detection.

Network - DNS Directly to the Internet:: Network - DNS Directly to the Internet	

Network - FTP (File Transfer Protocol) Activity to the Internet:: Network - FTP (File Transfer Protocol) Activity to the Internet	

Network - IRC (Internet Relay Chat) Protocol Activity to the Internet:: Network - IRC (Internet Relay Chat) Protocol Activity to the Internet	

Network - NAT Traversal Port Activity:: Network - NAT Traversal Port Activity	

Network - PPTP (Point to Point Tunneling Protocol) Activity:: Network - PPTP (Point to Point Tunneling Protocol) Activity	

Network - Port 26 Activity:: Network - Port 26 Activity	

Network - Port 8000 Activity:: Network - Port 8000 Activity

Network - Port 8000 Activity to the Internet:: Network - Port 8000 Activity to the Internet	

Network - Proxy Port Activity to the Internet:: Network - Proxy Port Activity to the Internet	

Network - RDP (Remote Desktop Protocol) from the Internet:: Network - RDP (Remote Desktop Protocol) from the Internet	

Network - RDP (Remote Desktop Protocol) to the Internet:: Network - RDP (Remote Desktop Protocol) to the Internet	

Network - RPC (Remote Procedure Call) from the Internet:: Network - RPC (Remote Procedure Call) from the Internet	

Network - RPC (Remote Procedure Call) to the Internet:: Network - RPC (Remote Procedure Call) to the Internet	

Network - SMB (Windows File Sharing) Activity to the Internet:: Network - SMB (Windows File Sharing) Activity to the Internet	

Network - SMTP to the Internet:: Network - SMTP to the Internet	

Network - SQL Server Port Activity to the Internet:: Network - SQL Server Port Activity to the Internet	

Network - SSH (Secure Shell) from the Internet:: Network - SSH (Secure Shell) from the Internet	

Network - SSH (Secure Shell) to the Internet:: Network - SSH (Secure Shell) to the Internet	

Network - Telnet Port Activity:: Network - Telnet Port Activity	

Network - Tor Activity to the Internet:: Network - Tor Activity to the Internet	

Network - VNC (Virtual Network Computing) From the Internet:: Network - VNC (Virtual Network Computing) From the Internet	

Network - VNC (Virtual Network Computing) To the Internet:: Network - VNC (Virtual Network Computing) To the Internet	

Null user agent:: Null user agent

PSexec activity:: PSexec activity

Persistence via Kernel Module Modification:: Identifies loadable kernel module errors, often indicative of potential persistence attempts.

Process Execution via WMI:: Process Execution via WMI

Process started by Acrobat reader - possible payload:: Process started by Acrobat reader - possible payload

Process started by MS Office program - possible payload:: Process started by MS Office program - possible payload

PsExec Lateral Movement Command:: Identifies use of the SysInternals tool PsExec to execute commands on a remote host. This is an indication of lateral movement and may detect adversaries.

SQLmap user agent:: SQLmap user agent

Suspicious MS Office Child Process:: Identifies suspicious child processes of frequently targeted Microsoft Office applications (Word, PowerPoint, Excel). These child processes are often launched during exploitation of Office applications or from documents with malicious macros.

Suspicious MS Outlook Child Process:: Identifies suspicious child processes of Microsoft Outlook. These child processes are often associated with spear phishing activity.

Suspicious process started by a script:: Suspicious process started by a script

System Shells via Services:: Windows services typically run as SYSTEM and can be used as a privilege escalation opportunity. Malware or penetration testers may run a shell as a service to gain SYSTEM permissions.

Unusual Network Connection via RunDLL32:: Identifies unusual instances of Rundll32.exe making outbound network connections. This may indicate adversarial activity and may identify malicious DLLs.

Unusual Parent-Child Relationship :: Identifies Windows programs run from unexpected parent processes. This could indicate masquerading or other strange activity on a system.

Unusual Process Execution - Temp:: Identifies processes running in a temporary folder. This is sometimes done by adversaries to hide malware.

Unusual Process Network Connection:: Identifies network activity from unexpected system applications. This may indicate adversarial activity as these applications are often leveraged by adversaries to execute code and evade detection.

User Account Creation:: Identifies attempts to create new local users. This is sometimes done by attackers to increase access to a system or domain.

User Added to Administrator Group:: Identifies attempts to add a user to an administrative group with the "net.exe" command. This is sometimes done by attackers to increase access of a compromised account or create new account.

Volume Shadow Copy Deletion via VssAdmin:: Identifies use of vssadmin.exe for shadow copy deletion on endpoints.  This commonly occurs in tandem with ransomware or other destructive attacks.

Volume Shadow Copy Deletion via WMIC:: Identifies use of wmic for shadow copy deletion on endpoints. This commonly occurs in tandem with ransomware or other destructive attacks.

WMIC Command Lateral Movement:: Identifies use of wmic.exe to run commands on remote hosts. This could be indicative of adversary lateral movement but will be noisy if commonly done by admins.

WinDump activity:: WinDump activity

Windows Burp CE activity:: Windows Burp CE activity

Windows Credential Dumping Commands:: Windows Credential Dumping Commands

Windows Credential Dumping via ImageLoad:: Windows Credential Dumping via ImageLoad

Windows Credential Dumping via Registry Save:: Windows Credential Dumping via Registry Save

Windows Data Compression Using Powershell:: Windows Data Compression Using Powershell

Windows Defense Evasion - Decoding Using Certutil:: Windows Defense Evasion - Decoding Using Certutil

Windows Defense Evasion or Persistence via Hidden Files:: Windows Defense Evasion or Persistence via Hidden Files

Windows Defense Evasion via Windows Event Log Tools:: Windows Defense Evasion via Windows Event Log Tools

Windows Defense evasion via Filter Manager:: Windows Defense evasion via Filter Manager

Windows Execution via .NET COM Assemblies:: Windows Execution via .NET COM Assemblies

Windows Execution via Compiled HTML File:: Windows Execution via Compiled HTML File

Windows Execution via Connection Manager:: Windows Execution via Connection Manager

Windows Execution via Microsoft HTML Application (HTA):: Windows Execution via Microsoft HTML Application (HTA)

Windows Execution via Regsvr32:: Windows Execution via Regsvr32

Windows Execution via Trusted Developer Utilities:: Windows Execution via Trusted Developer Utilities

Windows Indirect Command Execution:: Windows Indirect Command Execution

Windows Iodine activity:: Windows Iodine activity

Windows Management Instrumentation (WMI) Execution:: Windows Management Instrumentation (WMI) Execution

Windows Mimikatz activity:: Windows Mimikatz activity

Windows Netcat activity:: Windows Netcat activity

Windows Netcat network activity:: Windows Netcat network activity

Windows Network - Anomalous Windows Process Using HTTP/S Ports:: Windows Network - Anomalous Windows Process Using HTTP/S Ports

Windows Payload Obfuscation via Certutil:: Windows Payload Obfuscation via Certutil

Windows Persistence or Priv Escalation via Hooking:: Windows Persistence or Priv Escalation via Hooking

Windows Persistence via Application Shimming:: Windows Persistence via Application Shimming

Windows Persistence via BITS Jobs:: Windows Persistence via BITS Jobs

Windows Persistence via Modification of Existing Service:: Windows Persistence via Modification of Existing Service

Windows Persistence via Netshell Helper DLL:: Windows Persistence via Netshell Helper DLL

Windows Priv Escalation via Accessibility Features:: Windows Priv Escalation via Accessibility Features

Windows Process Discovery via Tasklist Command:: Windows Process Discovery via Tasklist Command

Windows Registry Query, Local:: Windows Registry Query, Local

Windows Registry Query, Network:: Windows Registry Query, Network

Windows Remote Management Execution:: Windows Remote Management Execution

Windows Scheduled Task Activity:: Windows Scheduled Task Activity

Windows Script Executing PowerShell:: Identifies a PowerShell process launched by either CScript or WScript. Observing Windows scripting processes executing a PowerShell script, may be indicative of malicious activity.

Windows Signed Binary Proxy Execution:: Windows Signed Binary Proxy Execution

Windows Signed Binary Proxy Execution Download:: Windows Signed Binary Proxy Execution Download

Windows Wireshark activity:: Windows Wireshark activity

Windows image load from a temp directory:: Windows image load from a temp directory

Windows net command activity by the SYSTEM account:: Windows net command activity by the SYSTEM account

Windows net user command activity:: Windows net user command activity

Windows nmap activity:: Windows nmap activity

Windows nmap scan activity:: Windows nmap scan activity

Windows process started by the Java runtime:: Windows process started by the Java runtime

Windows whoami command activity:: Windows whoami command activity

Windows: Background Intelligent Transfer Service (BITS) Connecting to the Internet:: Windows: Background Intelligent Transfer Service (BITS) Connecting to the Internet

Windows: Certutil Connecting to the Internet:: Windows: Certutil Connecting to the Internet

Windows: Command Prompt Connecting to the Internet:: Windows: Command Prompt Connecting to the Internet

Windows: HTML Help executable Program Connecting to the Internet:: Windows: HTML Help executable Program Connecting to the Internet

Windows: Microsoft HTML Application (HTA) Connecting to the Internet:: Windows: Microsoft HTML Application (HTA) Connecting to the Internet

Windows: Misc LOLBin Connecting to the Internet:: Windows: Misc LOLBin Connecting to the Internet

Windows: Powershell Connecting to the Internet:: Windows: Powershell Connecting to the Internet

Windows: Register Server Program Connecting to the Internet:: Windows: Register Server Program Connecting to the Internet

Windows: Script Interpreter Connecting to the Internet:: Windows: Script Interpreter Connecting to the Internet