[[prebuilt-rules]]
[role="xpack"]
=== Prebuilt rule reference

// Imported via script - needs work

The following prebuilt rules are available:

(Search) Windows 10:: (Search) Windows 10

403 Response to a POST:: 403 Response to a POST

405 Response (Method Not Allowed):: 405 Response (Method Not Allowed)

500 Response on Admin page:: 500 Response on Admin page

Command shell started by Internet Explorer:: Command shell started by Internet
Explorer

Command shell started by Internet Explorer:: Command shell started by Internet
Explorer

Command shell started by Powershell:: Command shell started by Powershell

Command shell started by Powershell:: Command shell started by Powershell

Command shell started by Svchost:: Command shell started by Svchost

Command shell started by Svchost:: Command shell started by Svchost

EQL -  MsBuild Making Network Connections:: EQL -  MsBuild Making Network
Connections

EQL -  Unusual Process Network Connection:: EQL -  Unusual Process Network
Connection

EQL - Audio Capture via PowerShell:: EQL - Audio Capture via PowerShell

EQL - Audio Capture via SoundRecorder:: EQL - Audio Capture via SoundRecorder

EQL - Bypass UAC via CMSTP:: EQL - Bypass UAC via CMSTP

EQL - Clearing Windows Event Logs:: EQL - Clearing Windows Event Logs

EQL - DLL Search Order Hijack:: EQL - DLL Search Order Hijack

EQL - Delete Volume USN Journal with fsutil:: EQL - Delete Volume USN Journal
with fsutil

EQL - Deleting Backup Catalogs with wbadmin:: EQL - Deleting Backup Catalogs
with wbadmin

EQL - Direct Outbound SMB Connection:: EQL - Direct Outbound SMB Connection

EQL - Encoding or Decoding Files via CertUtil:: EQL - Encoding or Decoding Files
via CertUtil

EQL - Local Service Commands:: EQL - Local Service Commands

EQL - PsExec Lateral Movement Command:: EQL - PsExec Lateral Movement Command

EQL - Suspicious MS Outlook Child Process:: EQL - Suspicious MS Outlook Child
Process

EQL - Suspicious PDF Reader Child Process:: EQL - Suspicious PDF Reader Child
Process

EQL - System Shells via Services:: EQL - System Shells via Services

EQL - User Account Creation:: EQL - User Account Creation

EQL - WMIC Command Lateral Movement:: EQL - WMIC Command Lateral Movement

EQL -Bypass UAC Event Viewer:: EQL -Bypass UAC Event Viewer

EQL -Bypass UAC Via sdclt:: EQL -Bypass UAC Via sdclt

Linux Network - Anomalous Process Using HTTP/S Ports:: Linux Network - Anomalous
Process Using HTTP/S Ports

Linux ld.so process activity:: Linux ld.so process activity

Linux lzop activity:: Linux lzop activity - possible @JulianRunnels

Linux lzop activity - possible @JulianRunnels:: Linux lzop activity - possible
@JulianRunnels

Linux unusual shell activity:: Linux unusual shell activity

Linux: Hping Activity:: Linux: Hping Activity

Linux: Java Process Connecting to the Internet:: Linux: Java Process Connecting
to the Internet

Linux: Kernel Module Activity:: Linux: Kernel Module Activity

Linux: Netcat Network Connection:: Linux: Netcat Network Connection

Linux: Nmap Activity:: Linux: Nmap Activity

Linux: Rawshark Activity:: Linux: Rawshark Activity

Linux: SSH Port Forwarding:: Detect ssh processes with the `-R` flag which can
be used to forward a port on a local system to the local system so that someone
on the remote system can connect to the local system. This is often used by
attackers to create encrypted tunnels through firewalls for pivoting and
persistence.

Linux: Shell Activity By Web Server:: Linux: Shell Activity By Web Server

Linux: Strace Activity:: Linux: Strace Activity

Linux: Tcpdump Activity:: Linux: Tcpdump Activity

Linux: Whoami Commmand:: Linux: Whoami Commmand

Linux: Whoami Commmand:: Linux: socat activity

Network - DNS Directly to the Internet  :: Network - DNS Directly to the
Internet

Network - Detect Large Outbound ICMP Packets:: Network - Detect Large Outbound
ICMP Packets

Network - Detect Long DNS TXT Record Response:: Network - Detect Long DNS TXT
Record Response

Network - FTP (File Transfer Protocol) Activity to the Internet :: Network - FTP
(File Transfer Protocol) Activity to the Internet

Network - IRC (Internet Relay Chat) Protocol Activity to the Internet   ::
Network - IRC (Internet Relay Chat) Protocol Activity to the Internet

Network - Port 26 Activity      :: Network - Port 26 Activity

Network - Port 8000 Activity:: Network - Port 8000 Activity

Network - Protocols passing authentication in cleartext:: Network - Protocols
passing authentication in cleartext

Network - RDP (Remote Desktop Protocol) from the Internet       :: Network - RDP
(Remote Desktop Protocol) from the Internet

Network - SQL Server Port Activity to the Internet      :: Network - SQL Server
Port Activity to the Internet

Network - VNC (Virtual Network Computing) From the Internet     :: Network - VNC
(Virtual Network Computing) From the Internet

Network - VNC (Virtual Network Computing) To the Internet       :: Network - VNC
(Virtual Network Computing) To the Internet

Null user agent:: Null user agent

PSexec activity:: PSexec activity

PSexec activity:: PSexec activity

Possible Bluekeep Inbound RDP Exploitation Attempt (CVE-2019-0708):: ET EXPLOIT
[NCC GROUP] Possible Bluekeep Inbound RDP Exploitation Attempt (CVE-2019-0708)

Powershell network connection:: Powershell network connection

Process Execution via WMI:: Process Execution via WMI

Process started by Acrobat reader - possible payload:: Process started by
Acrobat reader - possible payload

Process started by MS Office program - possible payload:: Process started by MS
Office program - possible payload

Process started by MS Office program - possible payload:: Process started by MS
Office program - possible payload

Process started by Windows Defender:: Process started by Windows Defender

SQLmap user agent:: SQLmap user agent

Splunk - Child Processes of Spoolsv.exe:: Splunk - Child Processes of
Spoolsv.exe

Splunk - Detect Long DNS TXT Record Response:: Splunk - Detect Long DNS TXT
Record Response

Splunk - Detect New Local Admin account:: Splunk - Detect New Local Admin
account

Splunk - Detect Use of cmd.exe to Launch Script Interpreters:: Splunk - Detect
Use of cmd.exe to Launch Script Interpreters

Splunk - Protocols passing authentication in cleartext:: Splunk - Protocols
passing authentication in cleartext

Suricata ATTACK [PTsecurity] Apache Tomcat RCE on Windows (CVE-2019-0232)::
ATTACK [PTsecurity] Apache Tomcat RCE on Windows (CVE-2019-0232)

Suricata ATTACK [PTsecurity] Arbitrary PHP RCE in Drupal 8 < 8.5.11,8.6.10 (CVE-2019-6340):: ATTACK [PTsecurity] Arbitrary PHP RCE in Drupal 8 <
8.5.11,8.6.10 (CVE-2019-6340)

Suricata ATTACK [PTsecurity] Oracle Weblogic _async deserialization RCE Attempt (CVE-2019-2725):: ATTACK [PTsecurity] Oracle Weblogic _async deserialization RCE
Attempt (CVE-2019-2725)

Suricata ATTACK [PTsecurity] Oracle Weblogic file upload RCE (CVE-2019-2618)::
ATTACK [PTsecurity] Oracle Weblogic file upload RCE (CVE-2019-2618)

Suricata ATTACK [PTsecurity] Possible Apache Axis RCE via SSRF (CVE-2019-0227)::
ATTACK [PTsecurity] Possible Apache Axis RCE via SSRF (CVE-2019-0227)

Suricata Base64 Encoded Invoke-Command Powershell Execution:: Suricata Base64
Encoded Invoke-Command Powershell Execution

Suricata Base64 Encoded New-Object Powershell Execution:: Suricata Base64
Encoded New-Object Powershell Execution

Suricata Category - A suspicious string was detected:: Suricata Category - A
suspicious string was detected

Suricata Category - Attempted Administrator Privilege Gain:: Suricata Category -
Attempted Administrator Privilege Gain

Suricata Category - Attempted Information Leak:: Suricata Category - Attempted
Information Leak

Suricata Category - Attempted Login with Suspicious Username:: Suricata Category - Attempted Login with Suspicious Username

Suricata Category - Client Using Unusual Port:: Suricata Category - Client Using
Unusual Port

Suricata Category - Crypto Currency Mining Activity:: Suricata Category - Crypto
Currency Mining Activity

Suricata Category - Decode of an RPC Query:: Suricata Category - Decode of an
RPC Query

Suricata Category - Default Username and Password Login Attempt:: Suricata
Category - Default Username and Password Login Attempt

Suricata Category - Denial of Service:: Suricata Category - Denial of Service

Suricata Category - Executable code was detected:: Suricata Category -
Executable code was detected

Suricata Category - Exploit Kit Activity:: Suricata Category - Exploit Kit
Activity

Suricata Category - Generic ICMP event:: Suricata Category - Generic ICMP event

Suricata Category - Generic Protocol Command Decode:: Suricata Category -
Generic Protocol Command Decode

Suricata Category - Information Leak:: Suricata Category - Information Leak

Suricata Category - Large Scale Information Leak:: Suricata Category - Large
Scale Information Leak

Suricata Category - Malware Command and Control Activity:: Suricata Category -
Malware Command and Control Activity

Suricata Category - Misc Attack:: Suricata Category - Misc Attack

Suricata Category - Network Scan Detected:: Suricata Category - Network Scan
Detected

Suricata Category - Network Trojan Detected:: Suricata Category - Network Trojan
Detected

Suricata Category - Non-Standard Protocol or Event:: Suricata Category - Non-
Standard Protocol or Event

Suricata Category - Not Suspicious Traffic:: Suricata Category - Not Suspicious
Traffic

Suricata Category - Possible Social Engineering Attempted:: Suricata Category -
Possible Social Engineering Attempted

Suricata Category - Potential Corporate Privacy Violation:: Suricata Category -
Potential Corporate Privacy Violation

Suricata Category - Potentially Bad Traffic:: Suricata Category - Potentially
Bad Traffic

Suricata Category - Successful Administrator Privilege Gain:: Suricata Category - Successful Administrator Privilege Gain

Suricata Category - Successful Credential Theft:: Suricata Category - Successful
Credential Theft

Suricata Category - Successful User Privilege Gain:: Suricata Category -
Successful User Privilege Gain

Suricata Category - System Call Detected:: Suricata Category - System Call
Detected

Suricata Category - TCP Connection Detected:: Suricata Category - TCP Connection
Detected

Suricata Category - Targeted Malicious Activity:: Suricata Category - Targeted
Malicious Activity

Suricata Category - Unknown Traffic:: Suricata Category - Unknown Traffic

Suricata Category - Web Application Attack:: Suricata Category - Web Application
Attack

Suricata Commonly Abused DNS Domain Detected:: Suricata Commonly Abused DNS
Domain Detected

Suricata DNS Traffic on Unusual UDP Port:: Suricata DNS Traffic on Unusual UDP
Port

Suricata Directory Reversal Characters in an HTTP Request:: Suricata Directory
Reversal Characters in an HTTP Request

Suricata Directory Traversal Characters in HTTP Response:: Suricata Directory
Traversal Characters in HTTP Response

Suricata Directory Traversal Characters in an HTTP Request Header:: Suricata
Directory Traversal Characters in an HTTP Request Header

Suricata Directory Traversal in Downloaded Zip File:: Suricata Directory
Traversal in Downloaded Zip File

Suricata Double Encoded Characters in a URI:: Suricata Double Encoded Characters
in a URI

Suricata ET EXPLOIT Attempted Remote Command Injection Outbound (CVE-2019-3929):: ET EXPLOIT Attempted Remote Command Injection Outbound
(CVE-2019-3929)

Suricata ET EXPLOIT Enigma Network Management Systems v65.0.0 CVE-2019-16072 (Outbound):: ET EXPLOIT Enigma Network Management Systems v65.0.0 CVE-2019-16072
(Outbound)

Suricata ET EXPLOIT IE Scripting Engine Memory Corruption Vulnerability (CVE-2019-0752):: ET EXPLOIT IE Scripting Engine Memory Corruption Vulnerability
(CVE-2019-0752)

Suricata ET EXPLOIT Linear eMerge E3 Unauthenticated Command Injection Inbound (CVE-2019-7256):: ET EXPLOIT Linear eMerge E3 Unauthenticated Command Injection
Inbound (CVE-2019-7256)

Suricata ET EXPLOIT Possible Cisco RV320 RCE Attempt (CVE-2019-1652):: ET
EXPLOIT Possible Cisco RV320 RCE Attempt (CVE-2019-1652)

Suricata ET EXPLOIT Possible Citrix Application Delivery Controller Arbitrary Code Execution Attempt (CVE-2019-19781) M2:: ET EXPLOIT Possible Citrix
Application Delivery Controller Arbitrary Code Execution Attempt
(CVE-2019-19781) M2

Suricata ET EXPLOIT Possible EXIM DoS (CVE-2019-16928):: ET EXPLOIT Possible
EXIM DoS (CVE-2019-16928)

Suricata ET EXPLOIT Possible EXIM RCE Inbound (CVE-2019-15846):: ET EXPLOIT
Possible EXIM RCE Inbound (CVE-2019-15846)

Suricata ET EXPLOIT Possible Exim 4.87-4.91 RCE Attempt Inbound (CVE-2019-10149:: ET EXPLOIT Possible Exim 4.87-4.91 RCE Attempt Inbound
(CVE-2019-10149

Suricata ET EXPLOIT Possible Zoom Client Auto-Join (CVE-2019-13450:: ET EXPLOIT
Possible Zoom Client Auto-Join (CVE-2019-13450

Suricata ET EXPLOIT Possible rConfig 3.9.2 Remote Code Execution PoC (CVE-2019-16662):: ET EXPLOIT Possible rConfig 3.9.2 Remote Code Execution PoC
(CVE-2019-16662)

Suricata ET EXPLOIT Pulse Secure SSL VPN - Arbitrary File Read (CVE-2019-11510):: ET EXPLOIT Pulse Secure SSL VPN - Arbitrary File Read
(CVE-2019-11510)

Suricata ET EXPLOIT VMware VeloCloud Authorization Bypass (CVE-2019-5533):: ET
EXPLOIT VMware VeloCloud Authorization Bypass (CVE-2019-5533)

Suricata ET EXPLOIT Yachtcontrol Webservers RCE CVE-2019-17270:: ET EXPLOIT
Yachtcontrol Webservers RCE CVE-2019-17270

Suricata ET EXPLOIT vBulletin 5.x Unauthenticated Remote Code Execution (CVE-2019-16759):: ET EXPLOIT vBulletin 5.x Unauthenticated Remote Code
Execution (CVE-2019-16759)

Suricata ET WEB_CLIENT Attempted RCE in Wordpress Social Warfare Plugin Inbound (CVE-2019-9978:: ET WEB_CLIENT Attempted RCE in Wordpress Social Warfare Plugin
Inbound (CVE-2019-9978

Suricata ET WEB_CLIENT Possible Confluence SSTI Exploitation Attempt - Leads to RCE/LFI (CVE-2019-3396):: ET WEB_CLIENT Possible Confluence SSTI Exploitation
Attempt - Leads to RCE/LFI (CVE-2019-3396)

Suricata ET WEB_SERVER Possible PHP Remote Code Execution CVE-2019-11043 PoC (Inbound):: ET WEB_SERVER Possible PHP Remote Code Execution CVE-2019-11043 PoC
(Inbound)

Suricata ET WEB_SERVER Webmin RCE CVE-2019-15107:: ET WEB_SERVER Webmin RCE
CVE-2019-15107

Suricata ET WEB_SPECIFIC_APPS Appointment Hour Booking - WordPress Plugin - Stored XSS (CVE-2019-13505):: ET WEB_SPECIFIC_APPS Appointment Hour Booking -
WordPress Plugin - Stored XSS (CVE-2019-13505)

Suricata ET WEB_SPECIFIC_APPS Atlassian Crowd Plugin Upload Attempt (CVE-2019-11580):: ET WEB_SPECIFIC_APPS Atlassian Crowd Plugin Upload Attempt
(CVE-2019-11580)

Suricata ET WEB_SPECIFIC_APPS Atlassian JIRA Template Injection RCE (CVE-2019-11581:: ET WEB_SPECIFIC_APPS Atlassian JIRA Template Injection RCE
(CVE-2019-11581

Suricata ET WEB_SPECIFIC_APPS Cisco Prime Infrastruture RCE - CVE-2019-1821:: ET
WEB_SPECIFIC_APPS Cisco Prime Infrastruture RCE - CVE-2019-1821

Suricata ET WEB_SPECIFIC_APPS Jenkins Chained Exploits CVE-2018-1000861 and CVE-2019-1003000:: ET WEB_SPECIFIC_APPS Jenkins Chained Exploits
CVE-2018-1000861 and CVE-2019-1003000

Suricata ET WEB_SPECIFIC_APPS Jenkins RCE CVE-2019-1003000:: ET
WEB_SPECIFIC_APPS Jenkins RCE CVE-2019-1003000

Suricata ET WEB_SPECIFIC_APPS Rails Arbitrary File Disclosure Attempt:: ET
WEB_SPECIFIC_APPS Rails Arbitrary File Disclosure Attempt

Suricata FTP Traffic on Unusual Port, Internet Destination:: Suricata FTP
Traffic on Unusual Port, Internet Destination

Suricata HTTP Traffic On Unusual Port, Internet Destination:: Suricata HTTP
Traffic On Unusual Port, Internet Destination

Suricata IMAP Traffic on Unusual Port, internet Destination:: Suricata IMAP
Traffic on Unusual Port, internet Destination

Suricata LaZagne Artifact in an HTTP POST:: Suricata LaZagne Artifact in an HTTP
POST

Suricata Mimikatz Artifacts in an HTTP POST:: Suricata Mimikatz Artifacts in an
HTTP POST

Suricata Possible Cobalt Strike Malleable C2 Null Response:: Suricata Possible
Cobalt Strike Malleable C2 Null Response

Suricata Possible SQL Injection - SQL Commands in HTTP Transactions:: Suricata
Possible SQL Injection - SQL Commands in HTTP Transactions

Suricata SSH Traffic Not on Port 22, Internet Destination:: Suricata SSH Traffic
Not on Port 22, Internet Destination

Suricata Serialized PHP Detected:: Suricata Serialized PHP Detected

Suricata non-HTTP Traffic on TCP Port 80:: Suricata non-HTTP Traffic on TCP Port
80

Suricata non-SMB Traffic on TCP Port 139 (SMB):: Suricata non-SMB Traffic on TCP
Port 139 (SMB)

Suricata non-SSH Traffic on Port 22:: Suricata non-SSH Traffic on Port 22

Suricata non-TLS on TLS Port:: Suricata non-TLS on TLS Port

Suricata shell_exec PHP Function in an HTTP POST:: Suricata shell_exec PHP
Function in an HTTP POST

Suspicious process started by a script:: Suspicious process started by a script

Suspicious process started by a script:: Suspicious process started by a script

WinDump activity:: WinDump activity

Windows - Child Processes of Spoolsv.exe:: Windows - Child Processes of
Spoolsv.exe

Windows - Detect New Local Admin account:: Windows - Detect New Local Admin
account

Windows - Detect PsExec With accepteula Flag:: Windows - Detect PsExec With
accepteula Flag

Windows - Detect Use of cmd.exe to Launch Script Interpreters:: Windows - Detect
Use of cmd.exe to Launch Script Interpreters

Windows - New External Device Attached:: Windows - New External Device Attached

Windows - Processes created by netsh:: Windows - Processes created by netsh

Windows - Processes launching netsh:: Windows - Processes launching netsh

Windows - Windows Event Log Cleared:: Windows - Windows Event Log Cleared

Windows Burp CE activity:: Windows Burp CE activity

Windows Defense Evasion - Decoding Using Certutil:: Windows Defense Evasion -
Decoding Using Certutil

Windows Defense Evasion via Windows Event Log Tools:: Windows Defense Evasion
via Windows Event Log Tools

Windows Defense evasion via Filter Manager:: Windows Defense evasion via Filter
Manager

Windows Execution via .NET COM Assemblies:: Windows Execution via .NET COM
Assemblies

Windows Execution via Compiled HTML File:: Windows Execution via Compiled HTML
File

Windows Execution via Connection Manager:: Windows Execution via Connection
Manager

Windows Execution via Microsoft HTML Application (HTA):: Windows Execution via
Microsoft HTML Application (HTA)

Windows Indirect Command Execution:: Windows Indirect Command Execution

Windows Management Instrumentation (WMI) Execution:: Windows Management
Instrumentation (WMI) Execution

Windows Netcat activity:: Windows Netcat activity

Windows Network - Anomalous Windows Process Using HTTP/S Ports:: Windows Network
- Anomalous Windows Process Using HTTP/S Ports

Windows Persistence via Application Shimming:: Windows Persistence via
Application Shimming

Windows Persistence via Modification of Existing Service:: Windows Persistence
via Modification of Existing Service

Windows Priv Escalation via Accessibility Features:: Windows Priv Escalation via
Accessibility Features

Windows Process Discovery via Tasklist Command:: Windows Process Discovery via
Tasklist Command

Windows Registry Query, Local:: Windows Registry Query, Local

Windows Registry Query, Network:: Windows Registry Query, Network

Windows Remote Management Execution:: Windows Remote Management Execution

Windows Signed Binary Proxy Execution Download:: Windows Signed Binary Proxy
Execution Download

Windows Wireshark activity:: Windows Wireshark activity

Windows net user command activity:: Windows net user command activity

Windows nmap activity:: Windows nmap activity

Windows nmap scan activity:: Windows nmap scan activity

Windows process started by the Java runtime:: Windows process started by the
Java runtime

Windows: Background Intelligent Transfer Service (BITS) Connecting to the Internet:: Windows: Background Intelligent Transfer Service (BITS) Connecting to
the Internet

Windows: Certutil Connecting to the Internet:: Windows: Certutil Connecting to
the Internet

Windows: Command Prompt Connecting to the Internet:: Windows: Command Prompt
Connecting to the Internet

Windows: HTML Help executable Program Connecting to the Internet:: Windows: HTML
Help executable Program Connecting to the Internet

Windows: Misc LOLBin Connecting to the Internet:: Windows: Misc LOLBin
Connecting to the Internet

Windows: Powershell Connecting to the Internet:: Windows: Powershell Connecting
to the Internet

Windows: Register Server Program Connecting to the Internet:: Windows: Register
Server Program Connecting to the Internet

Zeek Notice CaptureLoss::Too_Much_Loss:: Detected Zeek capture loss exceeds the
percentage threshold

Zeek Notice Conn::Content_Gap:: Data has sequence hole; perhaps due to
filtering.

Zeek Notice DNS::External_Name:: Raised when a non-local name is found to be
pointing at a local host.

Zeek Notice FTP::Bruteforcing:: Indicates a host bruteforcing FTP logins by
watching for too many rejected usernames or failed passwords.

Zeek Notice FTP::Site_Exec_Success:: Indicates that a successful response to a
“SITE EXEC” command/arg pair was seen.

Zeek Notice Heartbleed::SSL_Heartbeat_Attack:: Indicates that a host performed a
heartbleed attack or scan.

Zeek Notice Heartbleed::SSL_Heartbeat_Odd_Length:: Indicates we saw heartbeat
requests with odd length. Probably an attack or scan.

Zeek Notice Notice::Tally:: Zeek notice reporting a count of how often a notice
occurred.

Zeek Notice PacketFilter::Compile_Failure:: This notice is generated if a packet
filter cannot be compiled.

Zeek Notice PacketFilter::Dropped_Packets:: Indicates packets were dropped by
the packet filter.

Zeek Notice PacketFilter::Install_Failure:: Generated if a packet filter fails
to install.

Zeek Notice PacketFilter::No_More_Conn_Shunts_Available:: Indicative that
PacketFilter::max_bpf_shunts connections are already being shunted with BPF
filters and no more are allowed.

Zeek Notice ProtocolDetector::Protocol_Found:: Indicates a protocol was detected
on a non-standard port.

Zeek Notice ProtocolDetector::Server_Found:: Indicates a server was detected on
a non-standard port for the protocol.

Zeek Notice SSH::Password_Guessing:: Indicates that a host has been identified
as crossing the SSH::password_guesses_limit threshold with failed logins.

Zeek Notice SSH::Watched_Country_Login:: SSH login was seen to or from a
"watched" country based on the SSH::watched_countries variable

Zeek Notice SSL::Certificate_Expired:: Indicates that a certificate’s
NotValidAfter date has lapsed and the certificate is now invalid.

Zeek Notice SSL::Certificate_Expires_Soon:: Indicates that a certificate is
going to expire within SSL::notify_when_cert_expiring_in.

Zeek Notice SSL::Certificate_Not_Valid_Yet:: Indicates that a certificate’s
NotValidBefore date is future dated.

Zeek Notice SSL::Invalid_Server_Cert:: This notice indicates that the result of
validating the certificate along with its full certificate chain was invalid.

Zeek Notice SSL::Old_Version:: Indicates that a server is using a potentially
unsafe version

Zeek Notice SSL::Weak_Key:: Indicates that a server is using a potentially
unsafe key.

Zeek Notice Scan::Address_Scan:: Address scans detect that a host appears to be
scanning some number of destinations on a single port.

Zeek Notice Scan::Port_Scan:: Port scans detect that an attacking host appears
to be scanning a single victim host on several ports.

Zeek Notice Signatures::Count_Signature:: The same signature has triggered
multiple times for a host.

Zeek Notice Signatures::Multiple_Sig_Responders:: Host has triggered the same
signature on multiple hosts.

Zeek Notice Signatures::Multiple_Signatures:: Host has triggered many signatures
on the same host.

Zeek Notice Signatures::Sensitive_Signature:: Generic notice type for notice-
worthy signature matches.

Zeek Notice Software::Software_Version_Change:: Indicates that an interesting
software application changed versions on a host.

Zeek Notice Software::Vulnerable_Version:: Indicates that a vulnerable version
of software was detected.

Zeek Notice Traceroute::Detected:: Indicates that a host was seen running
traceroutes.