[[privileges-api-overview]]
[role="xpack"]
=== Privileges endpoint

Retrieves whether or not the user is authenticated, and the user's {kib} space 
and index privileges, which determine if the  user can create an index for the 
SIEM signals generated by detection engine rules. To create the index, users 
require `manage` privileges for both the  {ref}/security-privileges.html[{es} 
cluster and the `.siem-signals-<Kibana space>` index].

==== Get privileges

Returns user privileges for the {kib} space.

===== Request URL

`GET /api/detection_engine/privileges`

====== Example requests

Gets user privileges for the {kib} default space:

[source,console]
--------------------------------------------------
GET api/detection_engine/privileges
--------------------------------------------------
// KIBANA

Gets user privileges the the {kib} `siem` space:

[source,console]
--------------------------------------------------
GET s/siem/api/detection_engine/privileges
--------------------------------------------------
// KIBANA

===== Response code

`200`:: 
    Indicates a successful call.

====== Example response

[source,js]
--------------------------------------------------
{
  "username": "detection-engine-admin",
  "has_all_requested": false,
  "cluster": {
    "monitor_ml": true,
    "manage_ccr": false,
    "manage_index_templates": true,
    "monitor_watcher": true,
    "monitor_transform": true,
    "read_ilm": true,
    "manage_api_key": false,
    "manage_security": false,
    "manage_own_api_key": false,
    "manage_saml": false,
    "all": false,
    "manage_ilm": true,
    "manage_ingest_pipelines": true,
    "read_ccr": false,
    "manage_rollup": true,
    "monitor": true,
    "manage_watcher": true,
    "manage": true,
    "manage_transform": true,
    "manage_token": false,
    "manage_ml": true,
    "manage_pipeline": true,
    "monitor_rollup": true,
    "transport_client": true,
    "create_snapshot": true
  },
  "index": {
    ".siem-signals-detection-engine": {
      "all": false,
      "manage_ilm": true,
      "read": false,
      "create_index": true,
      "read_cross_cluster": false,
      "index": false,
      "monitor": true,
      "delete": false,
      "manage": true,
      "delete_index": true,
      "create_doc": false,
      "view_index_metadata": true,
      "create": false,
      "manage_follow_index": true,
      "manage_leader_index": true,
      "write": false
    }
  },
  "application": {}
  "is_authenticated": true <1>
  "has_encryption_key": true <2>
}
--------------------------------------------------
<1> Indicates whether the user can log in to the {es} deployment.
<2> Indicates whether the 
<<detections-permissions, `xpack.encryptedSavedObjects.encryptionKey`>> is
set.