[[rule-api-overview]]
[role="xpack"]
== SIEM rules API

You can create rules that automatically turn events and alerts sent to the
{siem-app} into signals, which are displayed on the Engine Detection page. 
Signals can be defined in numerous ways, from a single alert sent from a
third-party system to detecting malicious intent from a complex series of 
seemingly harmless events.

For more information on signals, and the difference between signals, events, 
and alerts, see <<detection-engine-overview>>.

The RESTful API supports the standard HTTP methods: `GET`, `POST`, `PUT`, and `DELETE`. It is accessed via `<kibana URL>/api/detection_engine/rules`, where `<kibana URL>` is the URL and port number of your Kibana instance.

NOTE: By default, the Kibana server runs behind a proxy which adds a random 
path component to its URL.
{kibana-ref}/development-basepath.html[Considerations for basePath] describes 
how to work with and disable the random path.

[float]
=== Kibana role requirements

To create and run rules, you must create a user role for your Kibana space with 
at least:

* the {ref}/security-privileges.html[`manage_api_key` privilege].
* `read` and `write` permissions for the signals index (the system index used 
  for storing signals created from rules).
* `all` privileges for {kibana-ref}/xpack-spaces.html[`SIEM`, `Actions`, and 
`Alerting`] features.


[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the API.

[float]
=== API calls

All calls to the API are stateless. Each call must include all the information {siem-soln} needs to perform the request.

The API methods are:

* `GET`: Retrieves existing rules
* `POST`: Creates new rules
* `PUT`: Updates existing rules
* `DELETE`: Deletes rules

All requests must contain these headers:

* `Content-Type: application/json`
* `kbn-xsrf: <value>`, where `<value>` can be any text (for example, `kbn-xsrf: kibana`)

For example, the following call retrieves the first 20 detection engine rules:

[source,js]
--------------------------------------------------
curl -X GET "<kibana URL>/api/detection_engine/rules/_find"
-H 'kbn-xsrf: kibana' -H 'Content-Type: application/json'
-u <username>:<password>
--------------------------------------------------