[[rule-api-overview]]
[role="xpack"]
== Detection engine API

You can create rules that automatically turn events and alerts sent to the
{siem-app} into signals, which are displayed on the Engine Detection page. 

For more information on signals, and the difference between signals, events, 
and alerts, see <<det-engine-terminology, detection engine terminology>>.

The RESTful API has these endpoints:

* `<kibana URL>/api/detection_engine/rules` - Detection engine rule CRUD 
functions 
* `<kibana URL>/api/detection_engine/index` - Signal index operations
* `<kibana URL>/api/detection_engine/tags` - Aggregates and returns rule tags
* `<kibana URL>/api/detection_engine/privileges` - Returns the user's 
permissions for the {kib} space
* `<kibana URL>/api/detection_engine/signals` - Aggregates and returns signals, 
and updates their statuses

Where `<kibana URL>` is the URL and port number of your Kibana instance.

NOTE: By default, the Kibana server runs behind a proxy which adds a random 
path component to its URL.
{kibana-ref}/development-basepath.html[Considerations for basePath] describes 
how to work with and disable the random path component.

[float]
==== {kib} space API calls

If you are making calls to a {kib} space *other than* the `Default` space, the 
space identifier is part of the endpoint's URL:

`<kibana URL>/s/<space URL>/api/detection_engine/rules`

Where `<space URL>` is the URL identifier for the space.

NOTE: You can find space URL identifiers on
{kibana-ref}/xpack-spaces.html[*Edit space*] pages (Management -> Spaces -> 
<space name>) or by calling
{kibana-ref}/spaces-api-get-all.html[`GET /api/spaces/space`].

[float]
=== Kibana role requirements

To create and run rules, you must use a user role for your Kibana space with 
at least:

* the {ref}/security-privileges.html[`manage_api_key` privilege].
* `read`, `write`, `create`, and `view_index_metadata` privileges for the 
signals index (the system index used for storing signals created from rules).
* `all` privileges for {kibana-ref}/xpack-spaces.html[`SIEM`, `Actions`, and 
`Alerting`] features.


[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the API.

[float]
=== API calls

All calls to the API are stateless. Each call must include all the information {siem-soln} needs to perform the request.

All requests must contain these headers:

* `Content-Type: application/json`
* `kbn-xsrf: <value>`, where `<value>` can be any alphanumeric string (for 
example, `kbn-xsrf: kibana`)

For example, the following call retrieves the first 20 detection engine rules 
from the {kib} `siem` space:

[source,js]
--------------------------------------------------
curl -X GET "<kibana URL>/s/siem/api/detection_engine/rules/_find"
-H 'kbn-xsrf: kibana' -H 'Content-Type: application/json'
-u <username>:<password>
--------------------------------------------------