[[rule-api-overview]]
[role="xpack"]
== SIEM rules API

You can create rules that automatically turn events and alerts sent to the
{siem-app} into signals, which notify you when something potentially important
occurs. Signals can be defined in numerous ways, from a single alert sent from 
a third-party system to detecting malicious intent from a complex series 
of seemingly harmless events.

For more information on signals, and the difference between signals and alerts,
see *ben:xref*.

The RESTful API supports the standard HTTP methods: `GET`, `POST`, `PUT`, and `DELETE`. It is accessed via `<kibana URL>/api/detection_engine/rules`, where `<kibana URL>` is the URL and port number of your Kibana instance.

[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the API.
*Frank: required user roles?*

[float]
=== API calls

All calls to the API are stateless. Each call must include all the information {siem-soln} needs to perform the request.

The API methods are:

* `GET`: Retrieves existing rules
* `POST`: Creates new rules
* `PUT`: Updates existing rules
* `DELETE`: Deletes rules

All requests must contain these headers:

* `Content-Type: application/json`
* `kbn-xsrf: <value>`, where `<value>` can be any text (for example, `kbn-xsrf: kibana`)

For example, the following call retrieves all existing detection engine rules:

[source,js]
--------------------------------------------------
curl -X GET "<kibana URL>/api/detection_engine/rules/_find"
-H 'kbn-xsrf: kibana' -H 'Content-Type: application/json'
-u <username>:<password>
--------------------------------------------------