[role="xpack"]
[[siem-apis]]
= SIEM APIs

You can use these APIs to interface with {siem-soln} features:

* <<rule-api-overview>>: Manage detection rules and signals
* <<cases-api-overview>>: Open and manage cases

Additionally, the {kib} <<actions-api-overview, Actions API>> is partially
documented to enable opening and updating cases in external ticketing systems.
For more information on {kib} Actions, see
{kibana-ref}/alerting-getting-started.html[Alerting and Actions] and
https://github.com/elastic/kibana/tree/master/x-pack/plugins/actions.

[float]
=== API URLs

For calls to the `Default` {kib} space, API endpoints are as follows:

`<kibana host>:<port>/api/<endpoint>`

Where:

* `<kibana host>` is the host name of your {kib} instance.
* `<port>` is port number of your {kib} instance.
* `<endpoint>` is the API endpoint, such as `detection_engine/rules` or
`cases/configure`.

If you are making calls to a {kib} space *other than* the `Default` space, the 
space identifier is part of the endpoint's URL:

`<kibana host>:<port>/s/<space URL>/api/<endpoint>`

Where `<space URL>` is the URL identifier for the {kib} space.

NOTE: You can find space URL identifiers on
{kibana-ref}/xpack-spaces.html[*Edit space*] pages (Management -> Spaces -> 
<space name>) or by calling
{kibana-ref}/spaces-api-get-all.html[`GET /api/spaces/space`].

[float]
=== Authentication

Token-based authentication, using the same username and password used to log in
to the Kibana UI, is required to access the APIs.

[float]
=== API calls

All calls to APIs are stateless. Each call must include all the information {siem-soln} needs to perform the request.

Requests must contain these headers:

* `kbn-xsrf: <value>`, where `<value>` can be any alphanumeric string (for 
example, `kbn-xsrf: kibana`)
* `Content-Type: application/json` (when the request contains a JSON payload)

For example, the following call uses the Detections API to retrieve the first
20 signal detection rules from the {kib} `siem` space:

[source,js]
--------------------------------------------------
curl -X GET "<kibana host>:<port>/s/siem/api/detection_engine/rules/_find"
-H 'kbn-xsrf: kibana' -u <username>:<password>
--------------------------------------------------

NOTE: In dev mode, the Kibana server runs behind a proxy which adds a random 
path component to its URL.
{kibana-ref}/development-basepath.html[Considerations for basePath] describes 
how to work with and disable the random path component.

include::detections/api/det-api-index.asciidoc[]

include::cases/api/cases-api/cases-api-index.asciidoc[]

include::cases/api/actions-api/cases-actions-api-index.asciidoc[]