[[siem-ui-overview]]
[role="xpack"]
== SIEM UI

beta[]

After you have security monitoring <<install-siem,up and
running>> and data is streaming to {es}, use the {siem-ui} in {kib} to monitor
and identify security problems in real time.

[[hosts-ui]]
=== Hosts

Hosts UI


[[network-ui]]
=== Network

Network UI

[[timelines-ui]]
=== Timelines

Timelines UI Timeline allows you to collect pieces of evidence during an
investigation. It's also great for handing off to another team member or team,
and something to link to from a ticketing system.

==== How Timelines work

drag and drop any highlightable pieces in the SIEM app (Does not work outside the SIEM app.)
including hostnames, IPs, user and process names

AND and OR

Horizontal filters are ANDed together

Vertical filters (or set of filters) are ORed together

Additional filtering or search with the KQL bar in Timeline

Ability to expand events to look at raw data incl. raw Elasticsearch JSON

Ability to add/remove columns

Short blurb on row renderers, but maybe not go into detail on each

Save/Open and list of saved timeline

Notes

===== Filter
.

===== Search
.

===== Expand your search
.

===== Narrow your search
.


=== Sample workflow
Include 2-3 examples of a possible workflow  (videos???)



