[[siem-ui-overview]]
[role="xpack"]
== SIEM UI

beta[]

After you have security monitoring <<install-siem,up and running>> and data is
streaming to {es}, use the {siem-ui} in {kib} to monitor, identify, and track
security problems in real time.

[float]
[[hosts-ui]]
=== Hosts

Hosts UI

[float]
[[network-ui]]
=== Network

Network UI

[float]
[[timelines-ui]]
=== Timeline

Timelines help you to collect pieces of evidence during an investigation. You
can hand a timeline off to another person or team, and  link to them from a ticketing
system.

[float]
[[narrow-expand]]
==== Narrow or expand your search with drag and drop 



AND and OR

Horizontal filters are ANDed together

Vertical filters (or set of filters) are ORed together

Additional filtering or search with the KQL bar in Timeline

Ability to expand events to look at raw data incl. raw Elasticsearch JSON

Ability to add/remove columns

Short blurb on row renderers, but maybe not go into detail on each

Save/Open and list of saved timeline

Notes

[float]
===== Highlight
Works in SIEM app

any highlightable pieces in the SIEM app (Does not work outside the SIEM app.)
including hostnames, IPs, user and process names

[float]
=== Sample workflow
Include 2-3 examples of a possible workflow  (videos for GA???)



