// tag::cloud[]
To enable {ingest-manager} on {ecloud}:

. Go to your deployment in the user console.

. Under the deployment name in the side navigation, click **Edit**.

. In the {kib} section, expand **User setting overrides** and enter the
following setting:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
----

. Click **Save**.

{kib} will restart automatically. When {kib} is available, refresh the browser
to see the {ingest-manager} app in the navigation menu.
// end::cloud[]

// tag::self-managed[]
To enable {ingest-manager} on a self-managed cluster:

. In the {es} configuration file, `config/elasticsearch.yml`, set the following
security settings to enable security and API keys:
+
[source,yaml]
----
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
----

. In the {kib} configuration file, `config/kibana.yml`, enable {ingest-manager}
and specify user credentials:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
xpack.ingestManager.fleet.tlsCheckDisabled: true <1>
xpack.security.enabled: true
elasticsearch.username: "elastic" <2>
elasticsearch.password: "abc123iUnbRftkABC123"
----
<1> This setting is not required if you configure TLS checking.
<2> Specify a user who is authorized to use {ingest-manager}.

[TIP]
=====
To set up passwords, you can use the documented {es} APIs or the
`elasticsearch-setup-passwords` command. For example:

`./bin/elasticsearch-setup-passwords auto`

After running the command, copy the Elastic user name to the {kib} config file.
Then restart {kib}.
=====

// end::self-managed[]
