[[release-notes-kibana-9.0.0-beta1]]
= {kib} version 9.0.0-beta1
++++
<titleabbrev>{kib}</titleabbrev>
++++

coming::[9.0.0-beta1]

For information about the {kib} 9.0.0 release, review the following information.

[float]
[[breaking-changes-9.0.0]]
== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 9.0.0, review the breaking changes, then mitigate the impact to your application.

[discrete]
[[breaking-207906]]
* Remove deprecated bulk endpoints from v9.0.0.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}207906[#207906]).
====
      
[discrete]
[[breaking-203927]]
* Disable search sessions by default.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}203927[#203927]).
====
      
[discrete]
[[breaking-202863]]
* Rework saved query privileges.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}202863[#202863]).
====
      
[discrete]
[[breaking-202679]]
* Remove discover:searchFieldsFromSource setting.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}202679[#202679]).
====
      
[discrete]
[[breaking-202278]]
* Switch to 19Hz sampling frequency.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}202278[#202278]).
====
      
[discrete]
[[breaking-202250]]
* Disable scripted field creation in the Data Views management page.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}202250[#202250]).
====
      
[discrete]
[[breaking-201254]]
* Remove the legacy table.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}201254[#201254]).
====
      
[discrete]
[[breaking-200834]]
* Use Kibana feature privileges only to control access to reporting.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}200834[#200834]).
====
      
[discrete]
[[breaking-200633]]
* Refactor timeline HTTP API.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}200633[#200633]).
====
      
[discrete]
[[breaking-200163]]
* Adding kibana upgrade deprecation warning apm_user removed.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}200163[#200163]).
====
      
[discrete]
[[breaking-199598]]
* Remove deprecated APIs.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}199598[#199598]).
====
      
[discrete]
[[breaking-199226]]
* Remove deprecated topics property for kafka output in favor of topic.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}199226[#199226]).
====
      
[discrete]
[[breaking-199033]]
* Remove "download CSV" export type functionality.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}199033[#199033]).
====
      
[discrete]
[[breaking-198799]]
* Remove deprecated settings API endpoints.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}198799[#198799]).
====
      
[discrete]
[[breaking-198435]]
* Remove 7.x deprecated kibana.yml settings.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}198435[#198435]).
====
      
[discrete]
[[breaking-198434]]
* Remove deprecated epm APIs.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}198434[#198434]).
====
      
[discrete]
[[breaking-198313]]
* Remove deprecated APIs for agents endpoints.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}198313[#198313]).
====
      
[discrete]
[[breaking-197422]]
* Disable deprecated rules bulk CRUD API endpoints in Serverless and 9.0.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}197422[#197422]).
====
      
[discrete]
[[breaking-196887]]
* Limit pagination size when retrieving full policy or withAgentCount.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}196887[#196887]).
====
      
[discrete]
[[breaking-193792]]
* Globally enforce internal API restriction.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}193792[#193792]).
====
      
[float]
[[deprecations-9.0.0]]
== Deprecations

The following functionality is deprecated in 9.0.0, and will be removed in 10.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 9.0.0.

[discrete]
[[deprecation-208208]]
* Removed deprecated get case status API.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}208208[#208208]).
====
      
[discrete]
[[deprecation-208086]]
* Removed deprecated get user actions API.
[%collapsible]
====
*Details* +
or more information, refer to ({kibana-pull}208086[#208086]).
====
      
[discrete]
[[deprecation-207926]]
* Removed deprecated get all comments API.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}207926[#207926]).
====
      
[discrete]
[[deprecation-207325]]
* Rename plugin to automatic import.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}207325[#207325]).
====
      
[discrete]
[[deprecation-203996]]
* Disable log stream and settings pages.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}203996[#203996]).
====
      
[discrete]
[[deprecation-203856]]
* Removed `TLSv1.1` from default set of supported protocols.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}203856[#203856]).
====
      
[discrete]
[[deprecation-203685]]
* Remove Logs Explorer.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}203685[#203685]).
====
      
[discrete]
[[deprecation-203148]]
* Deleted deprecated alerts routes.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}203148[#203148]).
====
      
[discrete]
[[deprecation-201810]]
* Remove all legacy risk engine code and features.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}201810[#201810]).
====
      
[discrete]
[[deprecation-201313]]
* Remove ephemeral tasks from task manager plugin.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}201313[#201313]).
====
      
[discrete]
[[deprecation-199598]]
* Remove deprecated API's.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}199598[#199598]).
====
      
[discrete]
[[deprecation-197802]]
* Remove `visualization:colorMapping` advanced setting.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}197802[#197802]).
====
      
[discrete]
[[deprecation-197684]]
* Remove no longer used feature flags for GA features.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}197684[#197684]).
====
      
[discrete]
[[deprecation-197421]]
* Remove ephemeral tasks from action and alerting plugins.
[%collapsible]
====
*Details* +
For more information, refer to ({kibana-pull}197421[#197421]).
====
      
[float]
[[features-9.0.0]]
== Features
{kib} 9.0.0 adds the following new and notable features.

Data ingestion and Fleet::
* Delete unenrolled agents task ({kibana-pull}195544[#195544]).
Elastic Security solution::
For the Elastic Security 9.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Kibana security::
* Update CEL flow to UX design ({kibana-pull}206491[#206491]).

For more information about the features introduced in 9.0.0, refer to <<whats-new,What's new in 9.0>>.

[[enhancements-and-bug-fixes-v9.0.0]]
== Enhancements and bug fixes

For detailed information about the 9.0.0 release, review the enhancements and bug fixes.    

[float]
[[enhancement-v9.0.0]]
=== Enhancements
Dashboards & Visualizations::
* [Vega] Update default basemaps to adapt to the Borealis theme refresh ({kibana-pull}208114[#208114]).
////
!!TODO!! The above PR had a lengthy release note description:
Elastic Maps Service basemaps shown in the Custom Visualization component (Vega) and in the Maps application and components alighn with the new dark and light theme.
////
Data ingestion and Fleet::
* Show reason for agent/endpoint uninstall ({kibana-pull}205815[#205815]).
////
!!TODO!! The above PR had a lengthy release note description:
Improves filtering & visibility of `Uninstalled` and `Orphaned` Agents in Fleet, by differentiating them from `Offline` agents. Status filters have been added for both `Uninstalled` and `Orphaned` agents. Agent `status` runtime field has been updated to return accordingly when an agent is `uninstalled` or `orphaned`. Additionally, improved UI by hiding agent labels with `0` agent matches.
////
* Update max supported package version ({kibana-pull}196675[#196675]).
* Remove old bundled.yaml from oas, fixed tags ({kibana-pull}194788[#194788]).
Elastic Security solution::
For the Elastic Security 9.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Kibana security::
* Use setup and troubleshooting templates in readme ({kibana-pull}206477[#206477]).
* Update Kibana Security components to use new EUI Borealis theme ({kibana-pull}201795[#201795]).
* Updated `js-yaml` to `4.1.0` ({kibana-pull}190678[#190678]).
Machine Learning::
* Removing use of ignore_throttled ({kibana-pull}199107[#199107]).
Management::
* Change bytes field title to Bytes and Bits ({kibana-pull}204346[#204346]).
Platform::
* Adds warning header to deprecated endpoints ({kibana-pull}205926[#205926]).
* Set HTTP2 as default if SSL is enabled and add deprecation log if SSL is not enabled or protocol is set to HTTP1 ({kibana-pull}204384[#204384]).
Other::
* Switch to 19Hz sampling frequency ({kibana-pull}202278[#202278]).
* Adds keyword builder pipeline ({kibana-pull}201616[#201616]).

[float]
[[fixes-v9.0.0]]
=== Bug fixes
Dashboards & Visualizations::
* [Partition] Fix behind text coloring for `syncColors` in *Lens* ({kibana-pull}209632[#209632]).
////
!!TODO!! The above PR had a lengthy release note description:
This fixes and issues where behind text colors were not correctly assigned, such as in `Pie`, `Treemap` and `Mosaic` charts.
////
* Fixes issue with `Amsterdam` theme where charts render with the incorrect background color ({kibana-pull}209595[#209595]).
* Persist `runPastTimeout` setting ({kibana-pull}208611[#208611]).
* Force return 0 on empty buckets on count if null flag is disabled ({kibana-pull}207308[#207308]).
* Fixes eslint error ({kibana-pull}204972[#204972]).
* Avoid rerendering loop due to search context reload ({kibana-pull}203150[#203150]).
* Assign test files to presentation team ({kibana-pull}200209[#200209]).
Data ingestion and Fleet::
* Updates removed params of the Fleet -> Logstash output configurations ({kibana-pull}210115[#210115]).
* Fixes required validation for multi text input field ({kibana-pull}205768[#205768]).
* Introduce airgapped config for bundled packages ({kibana-pull}202435[#202435]).
* Added `eventIngestedEnabled` flag ({kibana-pull}199733[#199733]).
Elastic Observability solution::
* Fixes chat on the Alerts page ({kibana-pull}197126[#197126]).
Elastic Search solution::
* Removing errors ({kibana-pull}202437[#202437]).
Elastic Security solution::
For the Elastic Security 9.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Platform::
* Added versioning to inventory_view_saved_object ({kibana-pull}207007[#207007]).
Other::
* Update java.ts - removing serverless link ({kibana-pull}204571[#204571]).
* Disable O11y features in Security Serverless project ({kibana-pull}203990[#203990]).
* Trim down PR template ({kibana-pull}198617[#198617]).
* Small UI fixes for new Space creation/settings page ({kibana-pull}197303[#197303]).
* Fixes code scanning alert no. 456: Incomplete string escaping or encoding ({kibana-pull}193909[#193909]).
* Fixes code scanning alert : Incomplete string escaping or encoding ({kibana-pull}193365[#193365]).