[[release-notes-kibana-9.0.0-rc1]]
= {kib} version 9.0.0-rc1

coming::[9.0.0-rc1]

For information about the {kib} 9.0.0 release, review the following information.

// [float]
// [[highlights-9.0.0-rc1]]
// == Highlights


[float]
[[breaking-changes-9.0.0-rc1]]
== Breaking changes

**Kibana security**

//Needs to be added to upgrade notes and detailed
[discrete]
[[breaking-213123]]
.Removed default `--openssl-legacy-provider`.
[%collapsible]
====
*Details* +
Legacy OpenSSL algorithms have been disabled by default. Further information on which algorithms can be found at https://docs.openssl.org/3.0/man7/OSSL_PROVIDER-legacy. These can be re-enabled by adding `--openssl-legacy-provider` to $KBN_PATH_CONF/node.options. For more information, refer to ({kibana-pull}213123[#213123]).
====
      
// [float]
// [[deprecations-9.0.0-rc1]]
// == Deprecations

// The following functionality is deprecated in 9.0.0, and will be removed in 10.0.0.
// Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
// you make the necessary updates after you upgrade to 9.0.0.


// [float]
// [[features-9.0.0-rc1]]
// == Features
// {kib} 9.0.0 adds the following new and notable features.

//For more information about the features introduced in 9.0.0, refer to <<whats-new,What's new in 9.0>>.

[[enhancements-and-bug-fixes-v9.0.0-rc1]]
== Enhancements and bug fixes

//For detailed information about the 9.0.0 release, review the enhancements and bug fixes.    

[float]
[[enhancement-v9.0.0-rc1]]
=== Enhancements

Elastic Observability solution::
* Split Up SLO Details from Overview. Static data that describes the SLO definition has been moved to a separate tab, making charts and valuable information about SLIs faster to access. ({kibana-pull}212826[#212826]).
* Adds the reason message to the rules recovery context ({kibana-pull}211411[#211411]).
* Adds a link to the location badge on synthetics SLOs that sends to the Monitors page with a filter applied that matches the location of the origin SLO ({kibana-pull}210695[#210695]).

[float]
[[fixes-v9.0.0-rc1]]
=== Bug fixes

Elastic Observability solution::
* Fixes an issue where clicking on the name badge for a synthetics monitor on an SLO details page would lead to a page that failed to load monitor details ({kibana-pull}210695[#210695]).
* Allows to use wildcard filters in SLO queries when DSL filters are also used ({kibana-pull}213119[#213119]).
