[role="xpack"]
[[configure-metrics-source]]

=== Configure metrics source data

If your metrics have custom index patterns, or use non-default field settings, you can override the default configuration settings.

The default source configuration for metrics is specified in the {kibana-ref}/infrastructure-ui-settings-kb.html[Metrics app settings] in the {kibana-ref}/settings.html[Kibana configuration file].
The default configuration uses the `metricbeat-*` index pattern to query the data.
The default configuration also defines field settings for things like timestamps and container names.

To change the configuration settings, click the *Settings* tab.

NOTE: These settings are shared with logs. Changes you make here may also affect the settings used by the {logs-app}.

In the *Settings* tab, you can change the values in these sections:

* *Name*: the name of the source configuration
* *Indices*: the index pattern or patterns in the Elasticsearch indices to read metrics data and log data from
* *Fields*: the names of specific fields in the indices that are used to query and interpret the data correctly

When you have completed your changes, click *Apply*.

If the fields are greyed out and cannot be edited, you may not have sufficient privileges to change the source configuration.
For more information see {kibana-ref}/xpack-security-authorization.html[Granting access to Kibana].

TIP: If {kibana-ref}/xpack-spaces.html[Spaces] are enabled in your Kibana instance, any configuration changes you make here are specific to the current space.
You can make different subsets of data available by creating multiple spaces with different data source configurations.