instances:
  - name: es-node01
    dns:
      - es-node01
      - localhost
    ip:
      - 127.0.0.1

  - name: es-node02
    dns:
      - es-node02
      - localhost
    ip:
      - 127.0.0.1

  - name: es-node03
    dns:
      - es-node03
      - localhost
    ip:
      - 127.0.0.1

  - name: "kib01"
    dns:
      - kib01
      - localhost
