[role="xpack"]
[[esms]]
== {esms}

The {esms} ({esms-init}) is a monitoring cluster on {ecloud}. Elastic provides
and maintains {esms-init} for self-managed commercial customers. If you send
your monitoring data to {esms-init}, it can also be used by Elastic support to
provide better and faster incident resolution.

NOTE: You must obtain your {esms-init} cluster URLs and credentials from the
Elastic support team.

[discrete]
[[esms-elasticsearch]]
=== Collecting monitoring data about {es}

There are two methods for collecting and sending data about the health of your
production cluster to {esms-init}: {metricbeat} or collectors and exporters.

TIP: If you want to monitor {ls}, you must use collectors and exporters to route
data from the production cluster to {esms-init}. Otherwise, it is simplest to
use {metricbeat}. 

To use {metricbeat}:

. Enable the collection of monitoring data on your cluster.
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=enable-collection]

For more information about these settings, see
{ref}/monitoring-settings.html[Monitoring settings in {es}].
--

. Disable the default collection of {es} monitoring metrics.
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=disable-default-collection]
--

. {metricbeat-ref}/metricbeat-installation.html[Install {metricbeat}] on each
node.

. Enable the {es} {xpack} module in {metricbeat} on each node. +
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=enable-es-module]
--

. Configure the {es} {xpack} module in {metricbeat} on each node. +
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=configure-es-module]

include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=remote-monitoring-user]
--

. Optional: Disable the system module in {metricbeat}. +
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=disable-system-module]
--

. Identify where to send the {es} monitoring data and supply the necessary
security information. Add the following settings in the {metricbeat}
configuration file (`metricbeat.yml`):
+
--
[source,yaml]
----------------------------------
output.elasticsearch:
  hosts: ["MONITORING_ELASTICSEARCH_URL"] <1>
  username: cloud_monitoring_agent <2>
  password: MONITORING_AGENT_PASSWORD <3>
----------------------------------
<1> Replace `MONITORING_ELASTICSEARCH_URL` with the appropriate URL for {esms-init}.
<2> The Elastic support team creates this user in {esms-init} and grants it the
{stack-ov}/built-in-roles.html[`remote_monitoring_agent` built-in role]. 
<3> Replace `MONITORING_AGENT_PASSWORD` with the value provided to you by the
Elastic support team.
--

. {metricbeat-ref}/metricbeat-starting.html[Start {metricbeat}].

. Verify that your monitoring data exists in {esms-init}.
+
--
Open {kib} in your web browser. Use the {kib} URL and the administrator user ID
that was provided to you by the Elastic support team.
{kibana-ref}/elasticsearch-metrics.html[View the {es} metrics] on the
*Stack Monitoring* page.

If you do not see your metrics yet, see
<<monitoring-troubleshooting,Troubleshooting {monitor-features}>>.
--

[discrete]
[[esms-kibana]]
=== Collecting monitoring data about {kib}

There are two methods for sending monitoring data about {kib} to {esms-init}.
You can send it directly to {esms-init} by using {metricbeat} or you can route
it through exporters on the production cluster.

TIP: It is simplest to use {metricbeat}. 

To use {metricbeat}:

. Disable the default collection of {kib} monitoring metrics. +
+
--
include::{kib-repo-dir}/user/monitoring/monitoring-metricbeat.asciidoc[tag=disable-kibana-collection]

For more information, see 
{kibana-ref}/monitoring-settings-kb.html[Monitoring settings in {kib}].
--

. {kibana-ref}/start-stop.html[Start {kib}].

. Ensure that the `xpack.monitoring.collection.enabled` setting is `true` on 
each node in the production cluster.

. {metricbeat-ref}/metricbeat-installation.html[Install {metricbeat}] on the 
same server as {kib}.

. Enable the {kib} {xpack} module in {metricbeat}. +
+
--
include::{kib-repo-dir}/user/monitoring/monitoring-metricbeat.asciidoc[tag=enable-kibana-module]
--

. Configure the {kib} {xpack} module in {metricbeat}. +
+
--
include::{kib-repo-dir}/user/monitoring/monitoring-metricbeat.asciidoc[tag=configure-kibana-module]

include::{kib-repo-dir}/user/monitoring/monitoring-metricbeat.asciidoc[tag=remote-monitoring-user]
--

. Optional: Disable the system module in {metricbeat}. +
+
--
include::{kib-repo-dir}/user/monitoring/monitoring-metricbeat.asciidoc[tag=disable-system-module]
--

. Identify where to send the {kib} monitoring data and supply the necessary
security information. Add the following settings in the {metricbeat}
configuration file (`metricbeat.yml`):
+
--
[source,yaml]
----------------------------------
  output.elasticsearch:
    hosts: ["MONITORING_ELASTICSEARCH_URL"] <1>
    username: cloud_monitoring_agent <2>
    password: MONITORING_AGENT_PASSWORD <3>
----------------------------------
<1> Replace `MONITORING_ELASTICSEARCH_URL` with the appropriate URL for {esms-init}.
<2> The Elastic support team creates this user in {esms-init} and grants it the
{stack-ov}/built-in-roles.html[`remote_monitoring_agent` built-in role]. 
<3> Replace `MONITORING_AGENT_PASSWORD` with the value provided to you by the
  Elastic support team.
--

. {metricbeat-ref}/metricbeat-starting.html[Start {metricbeat}]. 

. Verify that your monitoring data exists in {esms-init}.
+
--
Open {kib} in your web browser. Use the {kib} URL and the administrator user ID
that was provided to you by the Elastic support team.
{kibana-ref}/kibana-page.html[View the {kib} metrics] on the *Stack Monitoring* page.

If you do not see your metrics yet, see
<<monitoring-troubleshooting,Troubleshooting {monitor-features}>>.
--
