[role="xpack"]
[[esms]]
== {stack} Monitoring Service

The {stack} Monitoring Service (ESMS) is a monitoring cluster on Cloud that
Elastic provides to self-managed commercial customers. If you send your
monitoring data to the ESMS, it can also be used by Elastic support to provide
better and faster incident resolution. 

NOTE: You must obtain your ESMS cluster URLs and credentials from the Elastic
support team.

[discrete]
[[esms-elasticsearch]]
=== Collecting monitoring data about {es}

There are two methods for collecting and sending data about the health of your
production cluster to ESMS: {metricbeat} or collectors and exporters.

TIP: If you want to monitor {ls}, you must use collectors and exporters to
route data from the production cluster to ESMS. Otherwise, it is simplest to use
{metricbeat}. 

To use {metricbeat}:

. If your production cluster is stopped, {ref}/starting-elasticsearch.html[start it].

. Configure the following settings on each node in the production cluster:
+
--
[source,js]
----------------------------------
PUT _cluster/settings
{
  "persistent": {
    "xpack.monitoring.collection.enabled": true,
    "xpack.monitoring.elasticsearch.collection.enabled": false
  }
}
----------------------------------
// CONSOLE

Alternatively, you can put those settings in the `elasticsearch.yml` file on
each node. This method, however, requires you to restart each node.

The `xpack.monitoring.enabled` setting must also have a value of `true`, which
is its default value. If you have set it to `false` in the `elasticsearch.yml`
file on any node, you must change or remove it.

For more information about these settings, see
{ref}/monitoring-settings.html[Monitoring settings in {es}].
--

. {metricbeat-ref}/metricbeat-installation.html[Install {metricbeat}] on each
node.

. Enable the {es} {xpack} module in {metricbeat} on each node. +
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=enable-es-module]
--

. Configure the {es} {xpack} module in {metricbeat} on each node. +
+
--
include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=configure-es-module]

include::{es-repo-dir}/monitoring/configuring-metricbeat.asciidoc[tag=remote-monitoring-user]
--

. Identify where to send the {es} monitoring data and supply the necessary
security information. Add the following settings in the {metricbeat}
configuration file (`metricbeat.yml`):
+
--
[source,yaml]
----------------------------------
output.elasticsearch:
  hosts: ["MONITORING_ELASTICSEARCH_URL"] <1>
  username: cloud_monitoring_agent <2>
  password: MONITORING_AGENT_PASSWORD <3>
----------------------------------
<1> Replace `MONITORING_ELASTICSEARCH_URL` with the appropriate URL from the ESMS.
<2> The Elastic support team creates this user in ESMS and grants it the
{stack-ov}/built-in-roles.html[`remote_monitoring_agent` built-in role]. 
<3> Replace `MONITORING_AGENT_PASSWORD` with the value provided to you by the
Elastic support team.
--

. {metricbeat-ref}/metricbeat-starting.html[Start {metricbeat}].

. Verify that your monitoring data exists in ESMS.
+
--
Open {kib} in your web browser. Use the {kib} URL and the administrator user ID
that was provided to you by the Elastic support team.
{kibana-ref}/elasticsearch-metrics.html[View the {es} metrics] on the
*Monitoring* page.

If you do not see your metrics yet, see
<<monitoring-troubleshooting,Troubleshooting {monitor-features}>>.
--

[discrete]
[[esms-kibana]]
=== Collecting monitoring data about {kib}

There are two methods for sending monitoring data about {kib} to ESMS. You can
send it directly to ESMS by using {metricbeat} or you can route it through
exporters on the production cluster.

TIP: It is simplest to use {metricbeat}. 

To use {metricbeat}:

. Disable the default collection of {kib} monitoring metrics. +
+
--
include::{kib-repo-dir}/monitoring/monitoring-metricbeat.asciidoc[tag=disable-kibana-collection]

For more information, see 
{kibana-ref}/monitoring-settings-kb.html[Monitoring settings in {kib}].
--

. {kibana-ref}/start-stop.html[Start {kib}].

. Ensure that the `xpack.monitoring.collection.enabled` setting is `true` on 
each node in the production cluster.

. {metricbeat-ref}/metricbeat-installation.html[Install {metricbeat}] on the 
same server as {kib}.

. Enable the {kib} {xpack} module in {metricbeat}. +
+
--
include::{kib-repo-dir}/monitoring/monitoring-metricbeat.asciidoc[tag=enable-kibana-module]
--

. Configure the {kib} {xpack} module in {metricbeat}. +
+
--
include::{kib-repo-dir}/monitoring/monitoring-metricbeat.asciidoc[tag=configure-kibana-module]

include::{kib-repo-dir}/monitoring/monitoring-metricbeat.asciidoc[tag=remote-monitoring-user]
--

. Identify where to send the {kib} monitoring data and supply the necessary
security information. Add the following settings in the {metricbeat}
configuration file (`metricbeat.yml`):
+
--
[source,yaml]
----------------------------------
  output.elasticsearch:
    hosts: ["MONITORING_ELASTICSEARCH_URL"] <1>
    username: cloud_monitoring_agent <2>
    password: MONITORING_AGENT_PASSWORD <3>
----------------------------------
<1> Replace `MONITORING_ELASTICSEARCH_URL` with the appropriate URL from the ESMS.
<2> The Elastic support team creates this user in ESMS and grants it the
{stack-ov}/built-in-roles.html[`remote_monitoring_agent` built-in role]. 
<3> Replace `MONITORING_AGENT_PASSWORD` with the value provided to you by the
  Elastic support team.
--

. {metricbeat-ref}/metricbeat-starting.html[Start {metricbeat}]. 

. Verify that your monitoring data exists in ESMS.
+
--
Open {kib} in your web browser. Use the {kib} URL and the administrator user ID
that was provided to you by the Elastic support team.
{kibana-ref}/kibana-page.html[View the {kib} metrics] on the *Monitoring* page.

If you do not see your metrics yet, see
<<monitoring-troubleshooting,Troubleshooting {monitor-features}>>.
--
