[role="xpack"]
[[xpack-monitoring]]
= Monitoring the {stack}

[partintro]
--

{stack-monitor-features} give you insight into the operation of {es}, {ls}, and {kib}.
All of the monitoring metrics are stored in {es}, which enables you to easily
visualize the data from {kib}. From the {kib} Monitoring UI, you can spot issues
at a glance and delve into the system behavior over time to diagnose operational
issues. In addition to the built-in status warnings, you can set up custom alerts
based on the data in the monitoring indices.

For more information, see:

* <<how-monitoring-works>>
* <<monitoring-production>>
* {ref}/es-monitoring.html[Monitoring {es}]
* {kibana-ref}/xpack-monitoring.html[Monitoring {kib}]
* {logstash-ref}/monitoring-logstash.html[Monitoring Logstash]
* Monitoring Beats:
** {auditbeat-ref}/monitoring.html[Auditbeat]
** {filebeat-ref}/monitoring.html[Filebeat]
** {heartbeat-ref}/monitoring.html[Heartbeat]
** {metricbeat-ref}/monitoring.html[Metricbeat]
** {packetbeat-ref}/monitoring.html[Packetbeat]
** {winlogbeat-ref}/monitoring.html[Winlogbeat] 



--
