[role="xpack"]
[[monitoring-production]]
== Monitoring in a production environment

By default, {metricbeat} and the {monitoring} agents on {es} index data
into the cluster where they're running. In production, you should
send data to a separate _monitoring cluster_ so that historical monitoring
data is available even if the nodes you are monitoring are not. 

If you have at least a gold license, using a dedicated monitoring cluster also 
enables you to monitor multiple clusters from a central location.

To store monitoring data in a separate cluster:

. Set up the {es} cluster you want to use as the monitoring cluster. 
For example, you might set up a two host cluster with the nodes `es-mon-1` and 
`es-mon-2`.
+
--
NOTE: To monitor an {es} 7.x cluster, you must run {es}
7.x on the monitoring cluster.

--

.. (Optional) Verify that the collection of monitoring data is disabled on the 
monitoring cluster. By default, the `xpack.monitoring.collection.enabled` setting 
is `false`. 
+ 
--
For example, you can use the following APIs to review and change this setting:

[source,js]
----------------------------------
GET _cluster/settings

PUT _cluster/settings
{
  "persistent": {
    "xpack.monitoring.collection.enabled": false
  }
}
----------------------------------
// CONSOLE
--

. (Optional) Create a dedicated {kib} instance for monitoring, rather than using 
a single {kib} instance to access both your production cluster and monitoring 
cluster. 

.. Set the `elasticsearch.url` setting in the `kibana.yml` file such that it 
contains the appropriate URL for your monitoring cluster. For more information 
about this setting, see {kibana-ref}/settings.html[Configuring {kib}]. 

.. (Optional) Disable the collection of monitoring data in this {kib} instance. 
Set the `xpack.monitoring.kibana.collection.enabled` setting to `false` in the 
`kibana.yml` file. For more information about this setting, see 
{kibana-ref}/monitoring-settings-kb.html[Monitoring settings in {kib}]. 

. Configure your production cluster to collect data and send it to the 
monitoring cluster. 

** beta[] To use {metricbeat}, see 
{ref}/configuring-metricbeat.html[Monitoring {es} with {metricbeat}]. This option 
is available in 6.5 and later versions. 

** To use HTTP exporters, see {ref}/configuring-monitoring.html[Configuring monitoring in {es}].

. (Optional)
{logstash-ref}/configuring-logstash.html[Configure {ls} to collect data and send it to the monitoring cluster]. 
+
--
NOTE: You must configure HTTP exporters in the production cluster to route this 
data to the monitoring cluster. It cannot be accomplished by using {metricbeat}. 

--

. (Optional) Configure {kib} to collect data and send it to the monitoring cluster:

** beta[] To use {metricbeat}, see 
{kibana-ref}/monitoring-metricbeat.html[Monitoring {kib} with {metricbeat}]. This 
option is available in 6.4 and later versions. 

** To use HTTP exporters, see 
{kibana-ref}/monitoring-xpack-kibana.html[Configuring monitoring in {kib}].

. {kibana-ref}/monitoring-data.html[View the monitoring data in {kib}]. 
+
--
NOTE: {kib} makes requests to the monitoring cluster as the logged in user.
The username and password credentials must therefore be valid on both the {kib}
server and the monitoring cluster.

--
