[role="xpack"]
[[monitoring-production]]
== Monitoring in a production environment

By default, {metricbeat} and the {monitoring} agents on {es} index data
into the cluster where they're running. In production, you should
send data to a separate monitoring cluster so that historical monitoring
data is available even if the nodes you are monitoring are not. Using
a dedicated _monitoring cluster_ also enables you to monitor multiple
clusters from a central location.

To store monitoring data in a separate cluster:

. Set up the {es} cluster you want to use as the monitoring cluster. 
For example, you might set up a two host cluster with the nodes `es-mon-1` and 
`es-mon-2`.
+
--
NOTE: To monitor an {es} 7.x cluster, you must run {es}
7.x on the monitoring cluster.

--

. If you want to collect monitoring data about your production cluster, 
configure it to send its data to the monitoring cluster. 

** To use {metricbeat} to collect and send the data, see 
{ref}/configuring-metricbeat.html[Monitoring {es} with {metricbeat}].

** To use exporters, see {ref}/configuring-monitoring.html[Configuring monitoring in {es}].

. (Optional) {logstash-ref}/configuring-logstash.html[Configure monitoring in {ls}]. 

. (Optional) {kibana-ref}/monitoring-xpack-kibana.html[Configure {kib} to collect and send 
monitoring data].

. {kibana-ref}/monitoring-data.html[View the monitoring data in {kib}]. 
+
--
NOTE: {kib} makes requests to the monitoring cluster as the logged in user.
The username and password credentials must therefore be valid on both the {kib}
server and the monitoring cluster.

--
