[role="xpack"]
[[monitoring-production]]
== Monitoring in a production environment

By default, {metricbeat} and the {monitoring} agents on {es} index data
into the cluster where they're running. In production, you should
send data to a separate _monitoring cluster_ so that historical monitoring
data is available even if the nodes you are monitoring are not. 

If you have at least a gold license, using a dedicated monitoring cluster also 
enables you to monitor multiple clusters from a central location.

To store monitoring data in a separate cluster:

. Set up the {es} cluster you want to use as the monitoring cluster. 
For example, you might set up a two host cluster with the nodes `es-mon-1` and 
`es-mon-2`.
+
--
NOTE: To monitor an {es} 7.x cluster, you must run {es}
7.x on the monitoring cluster.

--

. Configure your production cluster to collect data and send it to the 
monitoring cluster. 

** beta[] To use {metricbeat}, see 
{ref}/configuring-metricbeat.html[Monitoring {es} with {metricbeat}]. This option 
is available in 6.5 and later versions. 

** To use HTTP exporters, see {ref}/configuring-monitoring.html[Configuring monitoring in {es}].

. (Optional)
{logstash-ref}/configuring-logstash.html[Configure {ls} to collect data and send it to the monitoring cluster]. 
+
--
NOTE: You must configure HTTP exporters in the production cluster to route this 
data to the monitoring cluster. It cannot be accomplished by using {metricbeat}. 

--

. (Optional) Configure {kib} to collect data and send it to the monitoring cluster:

** beta[] To use {metricbeat}, see 
{kibana-ref}/monitoring-metricbeat.html[Monitoring {kib} with {metricbeat}]. This 
option is available in 6.4 and later versions. 

** To use HTTP exporters, see 
{kibana-ref}/monitoring-xpack-kibana.html[Configuring monitoring in {kib}].

. {kibana-ref}/monitoring-data.html[View the monitoring data in {kib}]. 
+
--
NOTE: {kib} makes requests to the monitoring cluster as the logged in user.
The username and password credentials must therefore be valid on both the {kib}
server and the monitoring cluster.

--
