[float]
[[xpack-6.0.0-beta1]]
=== 6.0.0-beta1
August 8, 2017

[float]
[[breaking-6.0.0-beta1]]
==== Breaking Changes
Reporting::
* When {security} is enabled, reports will only be accessible to the user that created them.
* When {security} is enabled, user authorization is controlled by the
`xpack.reporting.roles.allow` setting in the `kibana.yml` which defaults to
`['reporting_user']`. Users will no longer have access to the underlying {reporting}
indices in {es} when assigned to the built-in `reporting_user` role. If using
custom reporting roles, the privileges to the indices will need to be removed, and the
role will need to be added to the `xpack-reporting.roles.allow` setting.

Security::
* A new bootstrap check enforces that TLS/SSL is required for inter-node
communication when running in
{ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
See <<encrypting-communications>>.
* A new bootstrap check enforces that HTTPS is used by the built-in token
service when running in
{ref}/bootstrap-checks.html#_development_vs_production_mode[production mode].
To disable the token service, set `xpack.security.authc.token.enabled`
to `false` in your `elasticsearch.yml`. See
{ref}/security-settings.html#token-service-settings[Token Service Settings].
