[[elastic-stack]]
= Installation and Upgrade Guide

:es-repo-dir:        {docdir}/../../elasticsearch/docs
:kib-repo-dir:       {docdir}/../../kibana/docs

include::{asciidoc-dir}/../../shared/attributes.asciidoc[]
include::{es-repo-dir}/Versions.asciidoc[]

== Overview

The products in the https://www.elastic.co/products[{stack}]
are designed to be used together and releases are synchronized
to simplify the installation and upgrade process. The full stack
consists of:

* {beats-ref}/index.html[Beats {branch}]
* {apm-server-ref}/index.html[APM Server {branch}]
* {ref}/index.html[Elasticsearch {branch}]
* {hadoop-ref}/index.html[Elasticsearch Hadoop {branch}]
* {kibana-ref}/index.html[Kibana {branch}]
* {logstash-ref}/index.html[Logstash {branch}]

This guide provides information about installing and upgrading
when you are using more than one {stack} product. It specifies
the recommended order of installation and the steps you need to take
to prepare for a stack upgrade.

For detailed information about breaking changes in {version} and install
and upgrade instructions for specific components, see the individual
product reference guides.

include::installing-stack.asciidoc[]

include::upgrading-stack.asciidoc[]

include::en/install-upgrade/breaking.asciidoc[]