[[installing-elastic-stack]]
== Installing the Elastic Stack

When installing the Elastic Stack, you must use the same version
across the entire stack. For example, if you are using Elasticsearch
{version}, you install Beats {version}, Elasticsearch Hadoop {version},
Kibana {version}, Logstash {version}, and {xpack} {version}.

If you're upgrading an existing installation, see <<upgrading-elastic-stack, Up, Upgrading the Elastic Stack>> for information about how to ensure compatibility with {version}.

[[install-order-elastic-stack]]
=== Installation Order

Install the Elastic Stack products you want to use in the following order:

. Elasticsearch ({esref}/install-elasticsearch.html[install instructions])
. {xpack} for Elasticsearch ({esref}/install-elasticsearch.html[install instructions])
. Kibana ({esref}/install-elasticsearch.html[install])
. {xpack} for Kibana ({esref}/install-elasticsearch.html[install instructions])
. Logstash ({esref}/install-elasticsearch.html[install])
. {xpack} for Logstash ({esref}/install-elasticsearch.html[install instructions])
. Beats ({esref}/install-elasticsearch.html[install instructions])
. Elasticsearch Hadoop ({esref}/install-elasticsearch.html[install instructions])

Installing in this order ensures that the components each product depends
on are in place.

[[install-elastic-stack-for-elastic-cloud]]
=== Installing on Elastic Cloud

Elastic Cloud is the official hosted Elasticsearch and Kibana offering from Elastic. Installing on Elastic Cloud is easy: a single click creates an Elasticsearch cluster configured to the size you want, with or without high availability. {xpack} is always installed, so you automatically have the ability to secure and monitor your cluster. Kibana can be enabled on a cluster with a click, and a number of popular plugins are readily available.

Some Elastic Cloud features can be used only with a specific  link:https://www.elastic.co/cloud/as-a-service/subscriptions[subscription level]. For example, installing custom plugins, dictionaries, and scripts requires a Gold or Platinum subscription.

To learn more, see {cloudref}/getting-started.html[Getting Started with Elastic Cloud]. Or just link:https://www.elastic.co/cloud/as-a-service/signup[sign up for a free trial] and start exploring hosted Elasticsearch in minutes.
