[[upgrading-elastic-stack]]
== Upgrading the Elastic Stack

You must upgrade all of the Elastic Stack products you are using
when upgrading to a new major version. You can perform a rolling upgrade when
upgrading from 5.6 to 6.x, a full cluster restart is not required.

We recommend upgrading to 5.6 before upgrading to {version}.
Upgrading from any other version than 5.6 requires a full cluster
restart. {xpack} 5.6 also provides free migration assistance and
upgrade tools that simplify the upgrade process.

IMPORTANT: 2.x indices are not compatible with {version}. You must
remove or reindex them on 5.x before upgrading to {version}. In addition,
the internal Kibana and {xpack} indices need to be upgraded to work
with {version}.

=== Preparing to upgrade

Before upgrading the Elastic Stack to {version}:

. Back up your data. You **cannot roll back** to an earlier version unless
you have a backup of your data. For information about creating snapshots, see
{ref}/modules-snapshots.html[Snapshot and Restore].

. Check the Elasticsearch {ref}/settings.html[deprecation log] to see if
you're using any deprecated features and update your code accordingly.
By default, deprecation log messages are enabled at the `WARN` level.

. Review the breaking changes for each product you use
and make the necessary changes so your code is compatible with {version}:
+
--
** {beats-ref}/breaking-changes.html[Beats {version} breaking changes]
** {ref}/breaking-changes.html[Elasticsearch {version} breaking changes]
** {hadoop-ref}/breaking-changes.html[Elasticsearch Hadoop {version} breaking changes]
** {kibana-ref}/breaking-changes.html[Kibana {version} breaking changes]
** {logstash-ref}/breaking-changes.html[Logstash {version} breaking changes]
** {xpack-ref}/xpack-breaking-changes.html[{xpack} {version} breaking changes]

IMPORTANT: If you're upgrading from 2.x, make sure you
check the breaking changes from 2.x to 5.x, as well as from 5.x to 6.x!
--

. {ref}/docs-reindex.html[Reindex] or delete all 2.x indices. We recommend
upgrading to 5.6 and using the {xpack} Reindex Helper to reindex 2.x indices.

. If Kibana and {xpack} are part of your stack, upgrade the internal Kibana
and {xpack} indices. We recommend using the {xpack} 5.6 Reindex Helper to
upgrade the internal indices. If you're performing a full cluster restart upgrade
from an earlier version, you can also <<upgrade-internal-indices,use the
 `_xpack/migration/upgrade` API>> directly to upgrade the
internal indices after you install Elasticsearch {version}.

. If you use {xpack} to secure your cluster:
.. Make sure TLS is enabled to encrypt communications between nodes. TLS must
be enabled to upgrade to {version}. For more information, see
{xpack-ref}/encrypting-communications.html[Encrypting Communications].
+
NOTE: Enabling TLS requires a full cluster restart. Nodes that have TLS
enabled cannot communicate with nodes that do not have TLS enabled. You must
restart all nodes to maintain communication across the cluster.

.. Make sure real passwords are configured for the built-in `elasticsearch`,
`kibana`, and `logstash_system` users. They cannot use the 5.x default
password (`changeme`). For more information, see
{xpack-ref}/setting-up-authentication.html[Setting Up User Authentication].

. Stop any {xpack} machine learning jobs that are running before starting the
upgrade process. See
{xpack-ref}/stopping-ml.html[Stopping Machine Learning].

IMPORTANT: Test upgrades in a dev environment before upgrading your
production cluster.


[[upgrade-order-elastic-stack]]
=== Upgrade order

Upgrade the Elastic Stack products you use in the following order:

// TODO: Add link to x-pack upgrade doc

. Elasticsearch Hadoop: {hadoop-ref}/install.html[install instructions]
. Elasticsearch: {ref}/setup-upgrade.html[upgrade instructions]
. {xpack} for Elasticsearch
. Kibana: {kibana-ref}/upgrade.html[upgrade instructions]
. {xpack} for Kibana
. Logstash: {logstash-ref}/upgrading-logstash.html[upgrade instructions]
. {xpack} for Logstash
. Beats: {beats-ref}/upgrading.html[upgrade instructions]

NOTE: Logstash 6.0+ and Beats 6.0+ are compatible with all 6.x versions of
Elasticsearch. This provides flexibility in when you schedule the upgrades
for your Logstash instances and Beats agents. We recommend upgrading Logstash
and Beats as soon as possible to take advantage of performance improvements
and other enhancements.

[role="xpack"]
[[xpack-stack-upgrade]]
=== Upgrading from 5.6

{xpack} 5.6 provides migration and upgrade APIs for Elasticsearch and a
Upgrade Assistant UI for Kibana. These tools are included with the {xpack}
trial license and the free https://register.elastic.co/[Basic license].

To upgrade to {version} from 5.6:

. {ref}/setup-upgrade.html[Upgrade Elasticsearch] to 5.6 and
install {xpack} on all nodes in your cluster. If you are upgrading from an
earlier 5.x release, you can perform a rolling upgrade. To upgrade from older
versions you must perform a full cluster restart.
+
If your trial license to use {xpack} expires, register for a free
https://register.elastic.co/[Basic license]. To apply the license, upload
the license file with the `license` API:
+
[source,json]
----------------------------------------------------------
license -d @license.json
----------------------------------------------------------

. If {xpack} **IS NOT** normally a part of your Elastic Stack, disable Security
in `elasticsearch.yml`:
+
[source,yaml]
----------------------------------------------------------
xpack.security.enabled: false
----------------------------------------------------------

. Upgrade Kibana to 5.6 and install {xpack}.

. If you disabled {xpack} security in `elasticsearch.yml`, also disable
Security in `kibana.yml`:
+
[source,yaml]
----------------------------------------------------------
xpack.security.enabled: false
----------------------------------------------------------

. Use the Upgrade Assistant in Kibana to
view incompatibilities that you need to fix, identify any 2.x indices that
need to be migrated or deleted, and upgrade the internal indices to the
{major-version} index format.
+
You can also call the Elasticsearch migration APIs directly:
+
`/_xpack/migration/assistance`:: Runs a series of checks on your cluster,
nodes, and indices and returns a list of issues that need to be
fixed before you can upgrade to {version}.
+
`/_xpack/migration/upgrade`:: Upgrades the Watcher and Security indices to a
single-type format compatible with Elasticsearch 6.x.

. Once you've resolved all of the migration issues, perform
a {ref}/rolling-upgrades.html[rolling upgrade] from Elasticsearch 5.6 to {version}.

[[oss-stack-upgrade]]
=== Upgrading from a pre-5.6 installation

It is possible to upgrade directly to {major-version} from a pre-5.6 installation,
but it requires a {ref}/restart-upgrade.html[full cluster restart] and you must
manually reindex any 2.x indices you need to carry forward to {major-version}.

IMPORTANT: If you use Kibana or {xpack}, you also need to upgrade the
internal Kibana and X-Pack indices. For information about upgrading them
after you install Elasticsearch {version}, see
<<upgrade-internal-indices, Upgrading internal indices>>.

To manually reindex a 2.x index:

. Create an index with 6.x compatible mappings.
. Use the {ref}/docs-reindex.html[reindex API] to copy documents from the
2.x index into the new index. You can use a script to perform any necessary
modifications to the document data and metadata during reindexing.
. Use the {ref}/indices-aliases.html[_aliases] API to add the name of the 2.x
index as alias for the new index and delete the 2.x index.

[[upgrade-internal-indices]]
==== Upgrading internal indices for {major-version}

The format used for the internal indices used by Kibana and {xpack} has
changed in {major-version}. Before you can run Kibana and {xpack} in {version},
these indices must be upgraded to the new format. If you are upgrading from a
version prior to 5.6, you must upgrade them after after installing
Elasticsearch {version}.

To get a list of the indices that need to be upgraded, install {xpack} and use
the {ref}/migration-api-assistance.html[`_xpack/migration/assistance` API]:

[source,json]
----------------------------------------------------------
GET /_xpack/migration/assistance
----------------------------------------------------------
// CONSOLE

To upgrade the `.security` index:

. On a single node, add a temporary superuser account to the `file` realm.
. Use the {ref}/migration-api-upgrade.html[`_xpack/migration/upgrade`]
API to upgrade the security index, submitting the request with the credentials
for the temporary superuser:
+
--
[source,json]
----------------------------------------------------------
POST /_xpack/migration/upgrade/.security
----------------------------------------------------------
// CONSOLE
--

. Delete the temporary superuser account from the file realm.

You can use your regular administration credentials to upgrade the other
internal indices using the `_xpack/migration/upgrade` API.

TIP: Once you upgrade the `.kibana` index, you can run Kibana and use the
X-Pack Reindex Helper UI to upgrade the other indices.

[[upgrade-elastic-stack-for-elastic-cloud]]
=== Upgrading on Elastic Cloud

A single click in the Elastic Cloud console can upgrade a cluster to a newer
version, add more processing capacity, change plugins, and enable or disable
high availability, all at the same time. During the upgrade process,
Elasticsearch, Kibana, {xpack} and the officially included plugins are
upgraded simultaneously.

Although upgrading your Elastic Cloud clusters is easy, you still need to
address breaking changes that affect your application. Minor version upgrades,
upgrades from 5.6 to {major-version}, and all other cluster configuration
changes can be performed with no downtime.

To avoid downtime when a full cluster restart is required:

. Provision an additional cluster with the new Elasticsearch version, reindex
your data, and send index requests to both clusters temporarily.

. Verify that the new cluster performs as expected, fix any problems, and then
permanently swap in the new cluster.

. Delete the old cluster to stop incurring additional costs. You are billed
only for the time that the new cluster runs in parallel with your old cluster.
Usage is billed on an hourly basis.

To learn more about the upgrade process on Elastic Cloud, see {cloudref}/upgrading.html[
Upgrade Versions] and {cloudref}/cluster-config.html[Configuring Elastic Cloud].

NOTE: Elastic Cloud only supports upgrades to released versions. Preview
releases and master snapshots are not supported.
