[[rule-api-overview]]
[role="xpack"]
== Detections API

beta[]

You can create rules that automatically turn events and alerts sent to the
{siem-app} into signals. These signals are displayed on the Detections page. 

For more information on signals, and the difference between signals, events, 
and alerts, see <<det-engine-terminology, detections terminology>>.

The API has these endpoints:

* `<kibana host>:<port>/api/detection_engine/rules` - Signal detection rules
CRUD functions
* `<kibana host>:<port>/api/detection_engine/index` - Signal index operations
* `<kibana host>:<port>/api/detection_engine/tags` - Aggregates and returns
rule tags
* `<kibana host>:<port>/api/detection_engine/_import` - Imports rules from an
ndjson file
* `<kibana host>:<port>/api/detection_engine/_export` - Exports rules to an
ndjson file
* `<kibana host>:<port>/api/detection_engine/privileges` - Returns the user's
{kib} space and signal index permissions, and whether the user is authenticated
* `<kibana host>:<port>/api/detection_engine/signals` - Aggregates, queries, and
returns signals, and updates their statuses
* `<kibana host>:<port>/api/detection_engine/prepackaged` - Loads and retrieves
the status of Elastic <<prebuilt-rules, prebuilt rules>>

TIP: You can view and download a Detections API Postman collection
https://github.com/elastic/examples/tree/master/Security%20Analytics/SIEM-examples/Detections-API[here].

[float]
=== Kibana role requirements

To create and run rules, the user role for the {kib} space must have:

* the {ref}/security-privileges.html[`manage_api_key` privilege].
* `read`, `write`, `create`, and `view_index_metadata` privileges for the 
signals index (the system index used for storing signals created from rules).
* `all` privileges for {kibana-ref}/xpack-spaces.html[`SIEM` features].
